export const TRANSACTION_VIEWS = Object.freeze(['history', 'register', 'party-stock']);
export const TRANSACTION_TYPES = Object.freeze(['SUPPLY_ASSIGN', 'TRANSFER_PARTY']);

export const resolveTransactionView = (value) => TRANSACTION_VIEWS.includes(value) ? value : 'history';
export const updateTransactionViewSearch = (search, view) => { const next = new URLSearchParams(search || ''); if (view === 'history') next.delete('txnView'); else next.set('txnView', view); return next; };
const remarkLabel = (key) => String(key || '').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/[_-]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const remarkValue = (value) => value == null || value === '' ? '—' : typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value);
const remarkInline = (value) => Object.entries(value || {}).map(([key, item]) => `${remarkLabel(key)}: ${Array.isArray(item) ? item.map((row) => typeof row === 'object' ? remarkInline(row) : remarkValue(row)).join(', ') : typeof item === 'object' && item ? remarkInline(item) : remarkValue(item)}`).join(' · ');
export function transactionRemarkPoints(remarks) {
    if (remarks == null || String(remarks).trim() === '') return [];
    let source = remarks;
    if (typeof remarks === 'string') {
        const text = remarks.trim();
        try { source = JSON.parse(text); } catch { return text.split(/\r?\n|\s*;\s*/).map((item) => item.trim()).filter(Boolean); }
    }
    if (typeof source !== 'object') return [remarkValue(source)];
    return Object.entries(source).flatMap(([key, value]) => {
        const label = remarkLabel(key);
        if (Array.isArray(value)) return value.length ? value.map((item, index) => `${label} ${index + 1}: ${typeof item === 'object' && item ? remarkInline(item) : remarkValue(item)}`) : [`${label}: —`];
        if (typeof value === 'object' && value) return [`${label}: ${remarkInline(value)}`];
        return [`${label}: ${remarkValue(value)}`];
    });
}
export const signedQuantity = (direction, quantity) => (direction === 'OUT' ? -1 : 1) * Math.abs(Number(quantity) || 0);
export const isSupplierParty = (party) => String(party?.category || '').toLowerCase().includes('supplier');
export const availableStock = ({ party, stockMap, partyId, resourceId }) => isSupplierParty(party) ? Infinity : Number(stockMap?.[`${partyId}_${resourceId}`] || 0);
export const resourceUomId = (resource, units = []) => { const code = String(resource?.base_unit_code || '').toLowerCase(); return units.find((unit) => String(unit.code || unit.symbol || unit.name || '').toLowerCase() === code)?.id || null; };
export const lineBalance = (lines = []) => lines.reduce((result, line) => { const key = String(line.projectResourceId || line.project_resource_id || ''); if (key) result[key] = (result[key] || 0) + signedQuantity(line.direction || (Number(line.signed_qty) < 0 ? 'OUT' : 'IN'), line.qty ?? line.signed_qty); return result; }, {});
export const buildTransactionPayload = ({ projectId, orgId, txnType, remarks, lines }) => ({ org_id: orgId, project_id: projectId, txn_type: txnType, txn_date: new Date(), status: 'CONFIRMED', remarks: remarks || `Transfer (${lines.length} lines)`, lines: lines.map((line) => ({ party_id: Number(line.partyId), project_resource_id: Number(line.projectResourceId), signed_qty: signedQuantity(line.direction, line.qty), uom_id: line.uomId ? Number(line.uomId) : null, role: line.role || (line.direction === 'OUT' ? 'SENDER' : 'RECEIVER') })) });
export function validateLedgerLines(lines, parties, stockMap) { if (lines.length < 2) return 'A valid double-entry transaction requires at least 2 lines.'; const balances = lineBalance(lines); for (const line of lines) { if (!line.partyId || !line.projectResourceId || Number(line.qty) <= 0) return 'Please complete all line fields with valid quantities.'; const party = parties.find((item) => String(item.pv_id) === String(line.partyId)); if (line.direction === 'OUT' && Number(line.qty) > availableStock({ party, stockMap, partyId: line.partyId, resourceId: line.projectResourceId })) return 'Cannot submit: One or more outflow parties do not have sufficient stock.'; } return Object.values(balances).some((value) => Math.abs(value) > 1e-6) ? 'Double-entry imbalance: All material quantities must balance to 0.' : null; }
export async function saveRegisterSequential(rows, create) { const saved = []; for (let index = 0; index < rows.length; index += 1) { try { await create(rows[index], index); saved.push(index); } catch (error) { return { saved, failed: index, unattempted: rows.slice(index + 1).map((_, position) => index + position + 1), error }; } } return { saved, failed: null, unattempted: [], error: null }; }
export const createRegisterRow = () => ({ id: `reg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`, date: new Date().toISOString().slice(0, 10), txn_type: 'SUPPLY_ASSIGN', from_party_id: '', to_party_id: '', project_resource_id: '', qty: '', uom_id: '', remarks: '', status: 'CONFIRMED' });
export const validateRegisterRow = (row, parties = [], resources = [], stockMap = {}) => { const from = parties.find((party) => String(party.pv_id) === String(row.from_party_id)); const to = parties.find((party) => String(party.pv_id) === String(row.to_party_id)); const resource = resources.find((item) => String(item.project_resource_id) === String(row.project_resource_id)); if (!from || !to) return 'From Party and To Party must resolve to project parties.'; if (String(from.pv_id) === String(to.pv_id)) return 'Source (From) and Destination (To) cannot be the same party.'; if (!resource) return 'Material / Resource must resolve to a project resource.'; if (!(Number(row.qty) > 0)) return 'Quantity must be greater than 0.'; const available = availableStock({ party: from, stockMap, partyId: from.pv_id, resourceId: resource.project_resource_id }); if (!isSupplierParty(from) && Number(row.qty) > available) return `Insufficient stock. Available: ${available}, Requested: ${Number(row.qty)}.`; return null; };
export const registerRowToPayload = ({ row, projectId, orgId, parties = [], resources = [], units = [] }) => { const from = parties.find((party) => String(party.pv_id) === String(row.from_party_id)); const to = parties.find((party) => String(party.pv_id) === String(row.to_party_id)); const resource = resources.find((item) => String(item.project_resource_id) === String(row.project_resource_id)); const unit = units.find((item) => String(item.id) === String(row.uom_id)); const type = row.txn_type || (isSupplierParty(from) ? 'SUPPLY_ASSIGN' : 'TRANSFER_PARTY'); const qty = Math.abs(Number(row.qty)); return { org_id: orgId, project_id: projectId, txn_type: type, txn_date: row.date ? new Date(row.date) : new Date(), status: row.status || 'CONFIRMED', remarks: row.remarks ? `[Entry Register] ${row.remarks}` : '[Entry Register Batch]', lines: [{ party_id: Number(from.pv_id), project_resource_id: Number(resource.project_resource_id), signed_qty: -qty, uom_id: unit ? Number(unit.id) : null, role: 'OWNER' }, { party_id: Number(to.pv_id), project_resource_id: Number(resource.project_resource_id), signed_qty: qty, uom_id: unit ? Number(unit.id) : null, role: 'OWNER' }] }; };
export async function saveRegisterSequentialGuarded(rows, create, isCurrent) { const saved = []; for (let index = 0; index < rows.length; index += 1) { if (!isCurrent()) return { saved, failed: null, unattempted: rows.slice(index).map((_, position) => index + position), stale: true, error: null }; try { await create(rows[index], index); saved.push(index); } catch (error) { return { saved, failed: index, unattempted: rows.slice(index + 1).map((_, position) => index + position + 1), stale: false, error }; } } return { saved, failed: null, unattempted: [], stale: false, error: null }; }
export const partyPositionParams = (projectId, partyId, orgId) => ({ party_id: partyId, project_id: projectId, org_id: orgId });
export const partyStatementParams = (projectId, orgId) => ({ project_id: projectId, org_id: orgId });
export const reducedStatementDetail = (row, partyId) => ({ id: row?.transaction_id || row?.id, txn_date: row?.txn_date, txn_type: row?.txn_type, status: row?.status || 'CONFIRMED', remarks: row?.remarks || '', lines: row?.project_resource_id == null ? [] : [{ party_id: partyId, project_resource_id: row.project_resource_id, signed_qty: row.signed_qty, role: 'Passbook Record' }] });
export const createPartyRequestGuard = () => { let generation = 0; let projectId = null; let partyId = null; return { begin(project, party) { projectId = String(project); partyId = String(party); generation += 1; return { generation, projectId, partyId }; }, isCurrent(token, project, party) { return token?.generation === generation && token?.projectId === String(project) && token?.partyId === String(party); }, invalidate() { generation += 1; } }; };
export const createTransactionRequestGuard = () => { let generation = 0; let projectId = null; return { begin(id) { projectId = String(id); generation += 1; return { generation, projectId }; }, isCurrent(token) { return token?.generation === generation && token?.projectId === projectId; }, invalidate() { generation += 1; } }; };
