import React, { useMemo, useState } from 'react';
import { Building, MoreVertical, Plus, SlidersHorizontal, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';
import api from '../../../services/api.js';
import clientApi from '../../../services/clientApi.js';
import { customToast } from '../../../utils/toast';
import MobileBottomSheet, { MobileActionSheet } from '../../components/MobileBottomSheet';
import MobileCard from '../../components/MobileCard';
import MobileConfirmModal from '../../components/MobileConfirmModal';
import MobileEmptyState from '../../components/MobileEmptyState';
import MobileFAB from '../../components/MobileFAB';
import MobileFilterSheet from '../../components/MobileFilterSheet';
import MobileLoadingState from '../../components/MobileLoadingState';
import MobileMetadataManager from '../../components/MobileMetadataManager';
import MobilePageHeader from '../../components/MobilePageHeader';
import MobileSearchBar from '../../components/MobileSearchBar';
import useMobileClients from '../../hooks/useMobileClients.js';
import MobileClientDetail from './MobileClientDetail';
import MobileClientForm from './MobileClientForm';
import { filterClients, normalizeClient } from './clientModel.js';

const Choices = ({ values, selected, onChange }) => <div className="flex flex-wrap gap-2">{values.map((value) => <button key={value} type="button" aria-pressed={selected.includes(value)} onClick={() => onChange(selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value])} className={`min-h-11 rounded-xl border px-3 text-xs font-bold ${selected.includes(value) ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/40' : 'border-gray-200 dark:border-gh-border'}`}>{value}</button>)}</div>;

export default function MobileClients({ authOverride, service = clientApi, loadClients, loadMetadata, metadataService, interactionRequest = (id, payload) => api.post(`/clients/${id}/interactions`, payload).then(({ data }) => data), onNavigate }) {
    const auth = useAuth(); const activeAuth = authOverride || auth; const navigate = useNavigate();
    const { clients: raw, jobNatures, sectors, loading, error, refresh } = useMobileClients({ loadClients, loadMetadata });
    const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ jobs: [], sectors: [] }); const [draft, setDraft] = useState(filters); const [filtersOpen, setFiltersOpen] = useState(false);
    const [selected, setSelected] = useState(null); const [actions, setActions] = useState(null); const [editing, setEditing] = useState(undefined); const [remove, setRemove] = useState(null); const [pending, setPending] = useState(false); const [metadataType, setMetadataType] = useState(null);
    const canWrite = activeAuth.hasPermission('clients', 2); const isAdmin = Boolean(activeAuth.isAdmin); const clients = useMemo(() => raw.map(normalizeClient), [raw]); const filtered = useMemo(() => filterClients(clients, { query, ...filters }), [clients, filters, query]);
    const jobValues = useMemo(() => [...new Set(jobNatures.map((item) => item.job_name || item.name || item).filter(Boolean))], [jobNatures]); const sectorValues = useMemo(() => [...new Set(sectors.map((item) => item.sector_name || item.name || item).filter(Boolean))], [sectors]); const go = (path) => onNavigate ? onNavigate(path) : navigate(path);
    const save = async (payload) => { setPending(true); try { const result = editing ? await service.updateClient(editing.id, payload) : await service.createClient(payload); if (result?.success === false) throw new Error(result.message); customToast.success(editing ? 'Client updated' : 'Client created'); setEditing(undefined); await refresh(); } catch (nextError) { customToast.error(nextError?.response?.data?.message || nextError.message || 'Client save failed'); } finally { setPending(false); } };
    const destroy = async () => { if (!canWrite || !remove) return; setPending(true); try { await service.deleteClient(remove.id); setRemove(null); setSelected(null); customToast.success('Client deleted'); await refresh(); } catch (nextError) { customToast.error(nextError?.response?.data?.message || nextError.message || 'Client delete failed'); } finally { setPending(false); } };
    const addInteraction = async (payload) => { if (!canWrite || !selected) return false; setPending(true); try { const result = await interactionRequest(selected.id, payload); if (result?.success === false) throw new Error(result.message); const detail = await service.getClientById(selected.id); setSelected(normalizeClient(detail?.client || selected)); customToast.success('Interaction logged'); return true; } catch (nextError) { customToast.error(nextError?.response?.data?.message || nextError.message || 'Interaction failed'); return false; } finally { setPending(false); } };

    return <div data-mobile-page="clients" className="mx-auto w-full max-w-2xl space-y-4 px-4 pb-28">
        <MobilePageHeader eyebrow="Relationships" title="Clients" subtitle={`${clients.length} client${clients.length === 1 ? '' : 's'}`} actions={<>{isAdmin && <button aria-label="Manage client metadata" onClick={() => setMetadataType('job_natures')} className="min-h-11 min-w-11"><SlidersHorizontal className="mx-auto" size={19} /></button>}{canWrite && <button aria-label="Client bulk upload" onClick={() => go('/clients/bulk-upload')} className="min-h-11 min-w-11"><Upload className="mx-auto" size={19} /></button>}</>} />
        <div className="flex gap-2"><div className="min-w-0 flex-1"><MobileSearchBar value={query} onChange={setQuery} placeholder="Search clients" /></div><button onClick={() => { setDraft(filters); setFiltersOpen(true); }} className="min-h-11 rounded-xl border border-gray-200 px-3 text-xs font-bold dark:border-gh-border">Filters</button></div>
        {loading ? <MobileLoadingState label="Loading clients" rows={5} /> : error ? <MobileEmptyState title="Clients unavailable" description="The client list could not be loaded." action={<button onClick={refresh} className="min-h-11 rounded-xl bg-blue-600 px-4 text-white">Try again</button>} /> : filtered.length === 0 ? <MobileEmptyState title="No clients found" description="Try another search or filter." /> : <div className="space-y-3">{filtered.map((client) => <MobileCard key={client.id} className="p-0"><div className="flex gap-3 p-4"><button onClick={async () => { try { const detail = await service.getClientById(client.id); setSelected(normalizeClient(detail?.client || client)); } catch { setSelected(client); } }} className="flex min-h-11 min-w-0 flex-1 items-start gap-3 text-left"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-purple-50 text-purple-700 dark:bg-purple-950/50"><Building size={20} /></span><span className="min-w-0"><span className="block truncate text-sm font-black">{client.name}</span><span className="block truncate text-xs text-gray-500 dark:text-gh-muted">{client.sector || 'No sector'} · {client.jobNature || 'No job nature'}</span><span className="mt-1 block truncate text-xs">{client.contactNumber || client.email || client.location || 'No contact details'}</span></span></button><button aria-label={`Actions for ${client.name}`} onClick={() => setActions(client)} className="min-h-11 min-w-11"><MoreVertical className="mx-auto" size={20} /></button></div></MobileCard>)}</div>}
        <MobileFilterSheet open={filtersOpen} onClose={() => setFiltersOpen(false)} onReset={() => setDraft({ jobs: [], sectors: [] })} onApply={() => { setFilters(draft); setFiltersOpen(false); }}><div><p className="mb-2 text-xs font-bold uppercase text-gray-500">Job natures</p><Choices values={jobValues} selected={draft.jobs} onChange={(jobs) => setDraft((current) => ({ ...current, jobs }))} /></div><div><p className="mb-2 text-xs font-bold uppercase text-gray-500">Sectors</p><Choices values={sectorValues} selected={draft.sectors} onChange={(nextSectors) => setDraft((current) => ({ ...current, sectors: nextSectors }))} /></div></MobileFilterSheet>
        <MobileActionSheet open={Boolean(actions)} onClose={() => setActions(null)} title={actions?.name} actions={actions ? [{ label: 'View details', onSelect: async () => { const detail = await service.getClientById(actions.id); setSelected(normalizeClient(detail?.client || actions)); } }, ...(canWrite ? [{ label: 'Edit client', onSelect: () => setEditing(actions) }, { label: 'Delete client', danger: true, onSelect: () => setRemove(actions) }] : [])] : []} />
        <MobileClientDetail client={selected} open={Boolean(selected)} onClose={() => setSelected(null)} canWrite={canWrite} onEdit={(item) => { setSelected(null); setEditing(item); }} onDelete={(item) => setRemove(item)} onAddInteraction={addInteraction} pending={pending} />
        <MobileBottomSheet open={editing !== undefined} onClose={() => setEditing(undefined)} title={editing ? 'Edit client' : 'Create client'}>{editing !== undefined && <MobileClientForm client={editing || null} jobNatures={jobNatures} sectors={sectors} pending={pending} onCancel={() => setEditing(undefined)} onSave={save} />}</MobileBottomSheet>
        <MobileConfirmModal open={Boolean(remove)} onClose={() => setRemove(null)} onConfirm={destroy} pending={pending} danger title={`Delete ${remove?.name || 'client'}?`} message="This also removes related client interactions according to the existing ERP contract." confirmLabel="Delete client" />
        <MobileMetadataManager open={Boolean(metadataType)} onClose={() => setMetadataType(null)} type={metadataType || 'job_natures'} isAdmin={isAdmin} service={metadataService} onChanged={refresh} />
        {isAdmin && <div className="flex gap-2"><button onClick={() => setMetadataType('job_natures')} className="min-h-11 flex-1 rounded-xl border border-gray-200 text-xs font-bold dark:border-gh-border">Manage job natures</button><button onClick={() => setMetadataType('sectors')} className="min-h-11 flex-1 rounded-xl border border-gray-200 text-xs font-bold dark:border-gh-border">Manage sectors</button></div>}
        {canWrite && <MobileFAB label="Create client" icon={Plus} onClick={() => setEditing(null)} />}
    </div>;
}
