import React from 'react';
import { X, Sparkles, Loader2 } from 'lucide-react';

const AISummaryDrawer = ({ isOpen, onClose, reportData, reportType }) => {
    if (!isOpen || !reportData) return null;

    // Simulate dummy AI summarization data based on the report type
    // In the future, this will be replaced by an actual AI backend call
    const title = `${reportType} AI Analysis`;
    const dummyAiSummary = `This is a simulated AI-generated summary for the ${reportType} report dated ${reportData.date || reportData.week || reportData.month}.
    
Key Insights:
- The overall progress aligns with the expected timeline and critical path metrics.
- Workforce allocation indicates a high focus on operational efficiency.
- Potential bottleneck identified in material procurement; proactive monitoring is advised.
    
Suggested Action Items:
1. Review vendor delivery schedules for the upcoming period.
2. Conduct a brief safety alignment meeting for newly inducted personnel.
3. Optimize resource distribution based on weather forecasts.`;

    return (
        <div className="fixed inset-0 z-[3000] flex justify-end overflow-hidden anim-fade-in group/ai-drawer">
            <div
                className="absolute inset-0 bg-black/60 backdrop-blur-sm transition-opacity duration-300"
                onClick={onClose}
            ></div>
            <div className="relative w-full max-w-lg bg-white dark:bg-[#0d1117] shadow-2xl anim-slide-left flex flex-col h-full border-l border-gray-200 dark:border-white/5">

                {/* Drawer Header */}
                <div className="p-10 bg-gradient-to-br from-indigo-600/10 to-transparent dark:from-indigo-900/20 border-b border-gray-100 dark:border-white/5 relative overflow-hidden text-left">
                    <button
                        onClick={onClose}
                        className="absolute top-8 right-8 p-2 text-gray-400 hover:text-gray-900 dark:hover:text-white transition-all hover:rotate-90"
                    >
                        <X size={20} />
                    </button>

                    <div className="flex items-center space-x-3 mb-4">
                        <div className="p-3 bg-indigo-500 rounded-2xl shadow-lg shadow-indigo-500/20 text-white flex items-center justify-center">
                            <Sparkles size={24} />
                        </div>
                        <span className="text-[10px] font-bold text-indigo-500 tracking-[0.2em] uppercase">AI Summarization</span>
                    </div>

                    <h2 className="text-3xl font-bold text-gray-900 dark:text-white tracking-tight">{title}</h2>
                    <p className="text-gray-500 text-sm mt-2">Executive automated synthesis & insights</p>
                </div>

                {/* Drawer Content */}
                <div className="flex-1 overflow-y-auto custom-scrollbar p-10 space-y-8 text-left">
                    <div className="p-6 rounded-2xl bg-indigo-50/50 dark:bg-indigo-900/10 border border-indigo-100 dark:border-indigo-500/20">
                        <div className="flex items-center space-x-2 mb-4 text-indigo-600 dark:text-indigo-400">
                            <Sparkles size={16} />
                            <h3 className="text-sm font-bold tracking-wide">Analysis Results</h3>
                        </div>
                        <div className="prose prose-sm dark:prose-invert max-w-none text-gray-600 dark:text-gray-300 whitespace-pre-line leading-relaxed">
                            {dummyAiSummary}
                        </div>
                    </div>

                    <div className="p-6 rounded-2xl bg-gray-50 dark:bg-white/[0.02] border border-gray-100 dark:border-white/5">
                        <p className="text-[10px] font-bold text-gray-400 tracking-widest mb-3 uppercase">AI Confidence Score</p>
                        <div className="flex items-center space-x-3">
                            <div className="flex-1 h-2 bg-gray-200 dark:bg-gray-800 rounded-full overflow-hidden">
                                <div className="h-full bg-indigo-500 w-[92%]"></div>
                            </div>
                            <span className="text-sm font-bold text-gray-900 dark:text-white">92%</span>
                        </div>
                    </div>
                </div>

                {/* Drawer Footer */}
                <div className="p-6 bg-gray-50 dark:bg-[#0a0d11] border-t border-gray-100 dark:border-white/5 text-center">
                    <p className="text-[10px] text-gray-400 tracking-widest uppercase">Generated by MANO-ERP Intelligence Engine</p>
                </div>
            </div>
        </div>
    );
};

export default AISummaryDrawer;
