import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, Milestone, Plus } from 'lucide-react';
import { projectApi } from '../../../../services/projectApi';
import { MobileCard, MobileStatCard } from '../../../components/MobileCard';
import MobileConfirmModal from '../../../components/MobileConfirmModal';
import MobileEmptyState from '../../../components/MobileEmptyState';
import MobileFAB from '../../../components/MobileFAB';
import MobileSearchBar from '../../../components/MobileSearchBar';
import MobileTabs from '../../../components/MobileTabs';
import MobilePhaseEditor from './MobilePhaseEditor';
import { buildPhasesProjectPayload, normalizePhases, phaseMetrics, phaseStatus } from './mobilePhaseModel';

export default function MobileProjectPhases({ project, canWrite, refreshProject, projectService = projectApi }) {
    const [phases, setPhases] = useState(() => normalizePhases(project)); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [editor, setEditor] = useState(null); const [confirm, setConfirm] = useState(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const metrics = phaseMetrics(phases);
    const activeProjectRef = useRef(project.id); activeProjectRef.current = project.id;
    useEffect(() => { setPhases(normalizePhases(project)); setEditor(null); setConfirm(null); setPending(false); setMessage(''); }, [project.id]);
    const visible = useMemo(() => phases.filter((phase) => (!query || [phase.name, phase.description].join(' ').toLowerCase().includes(query.toLowerCase())) && (filter === 'ALL' || phaseStatus(phase) === filter)), [filter, phases, query]);
    const persist = async (next, success) => { const operationProject = project; const operationProjectId = String(project.id); setPending(true); setMessage(''); try { const response = await projectService.updateProject(operationProject.id, buildPhasesProjectPayload(operationProject, next)); if (response?.success === false) throw new Error(response.message || 'Phase update failed'); if (String(activeProjectRef.current) !== operationProjectId) return false; setPhases(next); setMessage(success); await refreshProject?.(); return true; } catch (error) { if (String(activeProjectRef.current) !== operationProjectId) return false; setMessage(error?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : error?.response?.data?.message || error?.message || 'Phase update failed.'); return false; } finally { if (String(activeProjectRef.current) === operationProjectId) setPending(false); } };
    const save = async (form) => { const next = editor?.phase ? phases.map((phase) => phase.id === editor.phase.id ? { ...phase, ...form, name: form.name.trim(), description: form.description.trim() } : phase) : [...phases, { ...form, id: Date.now(), name: form.name.trim(), description: form.description.trim() }]; if (await persist(next, editor?.phase ? 'Phase updated.' : 'Phase created.')) setEditor(null); };
    const move = (phase, offset) => { const index = phases.findIndex((item) => item.id === phase.id); const target = index + offset; if (target < 0 || target >= phases.length) return; const next = [...phases]; [next[index], next[target]] = [next[target], next[index]]; persist(next, 'Phase order updated.'); };
    const remove = async () => { const next = phases.filter((phase) => phase.id !== confirm.id); if (await persist(next, 'Phase deleted.')) setConfirm(null); };
    const quickProgress = (phase, progress) => persist(phases.map((item) => item.id === phase.id ? { ...item, progress } : item), 'Phase progress updated.');
    return <div data-m5-module="Phases" className="min-w-0 space-y-4 px-4 pb-28">{message && <p role="status" className="rounded-xl bg-blue-50 p-3 text-xs dark:bg-blue-950/40">{message}</p>}<div className="grid grid-cols-2 gap-3"><MobileStatCard label="Weighted completion" value={`${metrics.completion}%`} icon={Milestone} /><MobileStatCard label="Total weight" value={`${metrics.totalWeight}%`} detail={`${metrics.completed}/${phases.length} completed`} tone={metrics.totalWeight === 100 ? 'green' : 'amber'} /></div><MobileSearchBar value={query} onChange={setQuery} placeholder="Search phases" /><MobileTabs segmented label="Phase status" value={filter} onChange={setFilter} items={[['ALL', 'All'], ['NOT_STARTED', 'Not started'], ['IN_PROGRESS', 'In progress'], ['COMPLETED', 'Completed']].map(([value, label]) => ({ value, label }))} />
        <div className="space-y-3">{visible.map((phase, index) => <MobileCard key={phase.id} className="relative pl-6"><span className="absolute left-0 top-6 h-3 w-3 -translate-x-1/2 rounded-full bg-blue-600" /><button className="w-full text-left" onClick={() => canWrite && setEditor({ phase })}><p className="text-[10px] font-bold uppercase text-blue-600">Phase {phases.findIndex((item) => item.id === phase.id) + 1} · {phaseStatus(phase).replace('_', ' ')}</p><h3 className="mt-1 text-sm font-black">{phase.name}</h3><p className="mt-1 text-xs text-gray-500">{phase.startDate || 'No start'} → {phase.endDate || 'No end'} · Weight {Number(phase.weight) || 0}%</p>{phase.description && <p className="mt-2 text-xs leading-5 text-gray-600 dark:text-gh-muted">{phase.description}</p>}<div className="mt-3 h-2 overflow-hidden rounded-full bg-gray-100 dark:bg-gh-hover"><div className="h-full bg-blue-600" style={{ width: `${Math.min(100, Number(phase.progress) || 0)}%` }} /></div></button>{canWrite && <div className="mt-3 flex flex-wrap gap-1"><button disabled={pending || index === 0} onClick={() => move(phase, -1)} className="min-h-9 px-3 text-xs"><ArrowUp size={14} className="inline" /> Up</button><button disabled={pending || index === visible.length - 1} onClick={() => move(phase, 1)} className="min-h-9 px-3 text-xs"><ArrowDown size={14} className="inline" /> Down</button><button disabled={pending} onClick={() => quickProgress(phase, Math.min(100, (Number(phase.progress) || 0) + 10))} className="min-h-9 px-3 text-xs">+10%</button><button onClick={() => setConfirm(phase)} className="min-h-9 px-3 text-xs text-red-600">Delete</button></div>}</MobileCard>)}{visible.length === 0 && <MobileEmptyState title="No matching phases" />}</div>{canWrite && <MobileFAB label="Create phase" extended icon={Plus} onClick={() => setEditor({ phase: null })} />}<MobilePhaseEditor open={editor !== null} phase={editor?.phase} defaultWeight={Math.max(0, 100 - metrics.totalWeight)} pending={pending} onClose={() => setEditor(null)} onSave={save} /><MobileConfirmModal open={confirm !== null} onClose={() => setConfirm(null)} onConfirm={remove} pending={pending} danger title="Delete phase" message={`Delete ${confirm?.name || 'this phase'} and its progress data?`} /></div>;
}
