import React, { useEffect, useState } from 'react';
import MobileBottomSheet from '../../../components/MobileBottomSheet';
import MobileDatePicker from '../../../components/MobileDatePicker';

const inputClass = 'mt-1 min-h-9 w-full rounded-lg border border-gray-200 bg-white px-2.5 text-xs dark:border-gh-border dark:bg-gh-input';
export default function MobilePhaseEditor({ open, phase, defaultWeight, pending, onClose, onSave }) {
    const [form, setForm] = useState({}); useEffect(() => { if (open) setForm({ name: phase?.name || '', startDate: phase?.startDate || new Date().toISOString().slice(0, 10), endDate: phase?.endDate || '', weight: String(phase?.weight ?? defaultWeight ?? 10), progress: String(phase?.progress ?? 0), description: phase?.description || '' }); }, [defaultWeight, open, phase]); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    return <MobileBottomSheet open={open} onClose={onClose} title={phase ? 'Edit phase' : 'Create phase'} footer={<div className="flex gap-2"><button className="min-h-9 flex-1 rounded-lg border text-xs font-semibold dark:border-gh-border" onClick={onClose}>Cancel</button><button disabled={pending || !form.name?.trim()} className="min-h-9 flex-1 rounded-lg bg-blue-600 text-xs font-semibold text-white disabled:opacity-50" onClick={() => onSave({ ...form, weight: Number(form.weight) || 0, progress: Math.min(100, Math.max(0, Number(form.progress) || 0)) })}>{pending ? 'Saving…' : 'Save'}</button></div>}><div className="space-y-2.5"><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Phase name<input value={form.name || ''} onChange={(event) => update('name', event.target.value)} className={inputClass} /></label><div className="grid grid-cols-2 gap-2"><MobileDatePicker label="Start date" value={form.startDate || ''} onChange={(event) => update('startDate', event.target.value)} /><MobileDatePicker label="End date" value={form.endDate || ''} onChange={(event) => update('endDate', event.target.value)} /></div><div className="grid grid-cols-2 gap-2"><label className="text-xs font-medium text-gray-700 dark:text-gray-300">Weight %<input type="number" min="0" max="100" step="0.5" value={form.weight || ''} onChange={(event) => update('weight', event.target.value)} className={inputClass} /></label><label className="text-xs font-medium text-gray-700 dark:text-gray-300">Progress %<input type="number" min="0" max="100" value={form.progress || ''} onChange={(event) => update('progress', event.target.value)} className={inputClass} /></label></div><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Notes<textarea rows="3" value={form.description || ''} onChange={(event) => update('description', event.target.value)} className={`${inputClass} py-2`} /></label></div></MobileBottomSheet>;
}

