import React from 'react';
import MobileCard from '../../../components/MobileCard';
import MobilePageHeader from '../../../components/MobilePageHeader';
import { reportTotalLabour } from './mobileReportsModel';

const List = ({ rows, empty = 'None recorded', render }) => <div className="space-y-2">{rows?.length ? rows.map((row, index) => <div key={index} className="rounded-xl bg-gray-50 p-3 text-sm dark:bg-gh-hover">{render ? render(row) : String(row)}</div>) : <p className="text-sm text-gray-500">{empty}</p>}</div>;
export default function MobileDailyReportDetail({ report, onBack, onAI, onAudit }) {
    return <div data-m10-view="daily-details" className="space-y-3 px-4 pb-28"><MobilePageHeader title="Daily Progress Report" subtitle={report.date} onBack={onBack}/><MobileCard><dl className="grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-gray-500">Report date</dt><dd className="font-bold">{report.date}</dd></div><div><dt className="text-xs text-gray-500">Ledger status</dt><dd className="font-bold">{report.audit?.approval?.status || '—'}</dd></div></dl></MobileCard><MobileCard><h3 className="mb-3 font-black">Project &amp; Site</h3><p className="text-sm">{report.weather === 'rainy' ? 'Rainy' : 'Normal Day'} · {report.siteCondition || '—'}</p><List rows={report.timeSlots} render={(row) => `${row.from || '—'} → ${row.to || '—'}`}/></MobileCard><MobileCard><h3 className="mb-3 font-black">Labour summary</h3><p className="mb-2 text-sm font-bold">Total manpower: {reportTotalLabour(report)}</p><List rows={report.labourData} render={(row) => `${row.agency || 'Agency'} · ${Object.entries(row).filter(([key]) => !['agency','remarks'].includes(key)).reduce((sum,[,value])=>sum+(Number(value)||0),0)} · ${row.remarks || 'No remarks'}`}/></MobileCard><MobileCard><h3 className="mb-3 font-black">Today’s Progress</h3><List rows={report.todayProgress} render={(row) => <><b>{row.item || 'Free-text item'}</b><p>{row.description || '—'}</p><span>{row.qty || 0} {row.unit || ''}</span></>}/></MobileCard><MobileCard><h3 className="mb-3 font-black">Tomorrow’s Plan</h3><List rows={report.tomorrowPlan} render={(row) => <><b>{row.item || 'Free-text item'}</b><p>{row.description || '—'}</p><span>{row.qty || 0} {row.unit || ''}</span></>}/></MobileCard><MobileCard><h3 className="mb-3 font-black">Events / Visits</h3><List rows={report.eventsList}/></MobileCard><MobileCard><h3 className="mb-3 font-black">Remarks &amp; Bottlenecks</h3><List rows={report.remarksList}/></MobileCard><MobileCard><h3 className="mb-2 font-black">Distribution</h3><p className="text-sm">{report.distribution || '—'}</p><h3 className="mb-2 mt-4 font-black">Prepared By</h3><p className="text-sm">{report.preparedBy || '—'}</p></MobileCard><div className="grid grid-cols-2 gap-2"><button type="button" onClick={onAI} className="min-h-11 rounded-xl bg-blue-600 font-bold text-white">AI Summary</button><button type="button" onClick={onAudit} className="min-h-11 rounded-xl border font-bold dark:border-gh-border">Audit</button></div></div>;
}
