import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Image, Save } from 'lucide-react';
import { projectApi } from '../../../../services/projectApi';
import { customToast } from '../../../../utils/toast';
import MobileDatePicker from '../../../components/MobileDatePicker';
import MobileFormSection from '../../../components/MobileFormSection';
import MobileSelect from '../../../components/MobileSelect';
import MobileStickyActions from '../../../components/MobileStickyActions';
import { PROJECT_STATUS_OPTIONS, projectSettingsForm, saveProjectSettingsWorkflow, validateProjectLogo } from './mobileProjectSettingsModel';

const inputClass = 'mt-1 min-h-9 w-full rounded-lg border border-gray-200 bg-white px-2.5 text-xs font-normal disabled:opacity-60 dark:border-gh-border dark:bg-gh-input';
export default function MobileProjectSettings({ project, canWrite, refreshProject, projectService = projectApi }) {
    const initial = useMemo(() => projectSettingsForm(project), [project]); const [form, setForm] = useState(initial); const [logoFile, setLogoFile] = useState(null); const [logoPreview, setLogoPreview] = useState(project.logo_url || ''); const [pending, setPending] = useState(false); const [message, setMessage] = useState(''); const fileRef = useRef(null);
    useEffect(() => { setForm(initial); setLogoPreview(project.logo_url || ''); setLogoFile(null); }, [initial, project.logo_url]);
    useEffect(() => () => { if (logoFile && logoPreview?.startsWith('blob:')) URL.revokeObjectURL(logoPreview); }, [logoFile, logoPreview]);
    const dirty = JSON.stringify(form) !== JSON.stringify(initial) || Boolean(logoFile) || logoPreview !== (project.logo_url || ''); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    const selectLogo = (file) => { const error = validateProjectLogo(file); if (error) { customToast.error(error, 'Invalid Logo'); setMessage(error); return; } if (logoPreview?.startsWith('blob:')) URL.revokeObjectURL(logoPreview); setLogoFile(file); setLogoPreview(URL.createObjectURL(file)); setMessage(''); };
    const discard = () => { setForm(initial); setLogoFile(null); setLogoPreview(project.logo_url || ''); if (fileRef.current) fileRef.current.value = ''; setMessage('Changes discarded.'); customToast.info('Changes discarded.', 'Settings'); };
    const save = async () => { if (!canWrite || pending) return; if (!form.name.trim()) { setMessage('Project name is required.'); customToast.error('Project name is required.', 'Validation Error'); return; } setPending(true); setMessage(''); try { const result = await saveProjectSettingsWorkflow({ project, form, logoFile, removeLogo: !logoPreview && Boolean(project.logo_url), projectService }); if (result.partial) { const reason = result.error?.response?.data?.message || result.error?.message || 'Logo change failed'; const text = `Project settings were saved, but the logo change failed: ${reason}`; setMessage(text); customToast.warning(text, 'Partial Save'); return; } await refreshProject?.(); setMessage('Project settings saved.'); customToast.success('Project settings saved.', 'Settings Updated'); } catch (error) { const text = error?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : error?.response?.data?.message || error?.message || 'Project settings could not be saved.'; setMessage(text); customToast.error(text, 'Settings Error'); } finally { setPending(false); } };
    return <div data-m5-module="Settings" className="w-full min-w-0 space-y-2 px-2 sm:px-3 pb-24">{!canWrite && <p className="rounded-lg bg-amber-50 p-2.5 text-xs font-normal text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">Read-only view</p>}{message && <p role="status" className="rounded-lg bg-blue-50 p-2.5 text-xs font-normal dark:bg-blue-950/40">{message}</p>}
        <MobileFormSection title="General information"><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Project name *<input disabled={!canWrite} value={form.name} onChange={(event) => update('name', event.target.value)} className={inputClass} /></label><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Project code<input disabled={!canWrite} value={form.projectCode} onChange={(event) => update('projectCode', event.target.value)} className={inputClass} /></label><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Location<input disabled={!canWrite} value={form.location} onChange={(event) => update('location', event.target.value)} className={inputClass} /></label><label className="block text-xs font-medium text-gray-700 dark:text-gray-300">Description<textarea disabled={!canWrite} rows="3" value={form.description} onChange={(event) => update('description', event.target.value)} className={`${inputClass} py-2`} /></label></MobileFormSection>
        <MobileFormSection title="Organisation logo" description="PNG, JPG, WEBP, or SVG. Maximum 5MB."><input ref={fileRef} type="file" hidden accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={!canWrite} onChange={(event) => event.target.files?.[0] && selectLogo(event.target.files[0])} />{logoPreview ? <img src={logoPreview} alt="Project logo preview" className="mx-auto max-h-36 max-w-full rounded-lg object-contain" /> : <div className="flex min-h-24 items-center justify-center rounded-lg border border-dashed border-gray-300 text-gray-400 dark:border-gh-border"><Image size={24} /></div>}{canWrite && <div className="grid grid-cols-2 gap-2"><button className="min-h-9 rounded-lg border border-gray-200 text-xs font-semibold dark:border-gh-border" onClick={() => fileRef.current?.click()}>{logoPreview ? 'Replace' : 'Select logo'}</button><button className="min-h-9 rounded-lg border border-red-300 text-xs font-semibold text-red-600 dark:border-red-900" onClick={() => { setLogoFile(null); setLogoPreview(''); }}>Remove</button></div>}</MobileFormSection>
        <MobileFormSection title="Timeline & lifecycle"><div className="grid grid-cols-2 gap-2"><MobileDatePicker disabled={!canWrite} label="Start date" value={form.startDate} onChange={(event) => update('startDate', event.target.value)} /><MobileDatePicker disabled={!canWrite} label="Target end date" value={form.endDate} onChange={(event) => update('endDate', event.target.value)} /></div><MobileSelect disabled={!canWrite} label="Project status" value={form.status} onChange={(event) => update('status', event.target.value)} options={PROJECT_STATUS_OPTIONS} /></MobileFormSection>
        {canWrite && dirty && <MobileStickyActions><button disabled={pending} onClick={discard} className="min-h-9 flex-1 rounded-lg border border-gray-200 text-xs font-semibold dark:border-gh-border">Discard</button><button disabled={pending} onClick={save} className="min-h-9 flex-1 rounded-lg bg-blue-600 text-xs font-semibold text-white disabled:opacity-50"><Save size={14} className="inline mr-1" /> {pending ? 'Saving…' : 'Save'}</button></MobileStickyActions>}
    </div>;
}
