import React, { useEffect, useMemo, useState } from 'react';
import { resourceApi } from '../../../services/resourceApi.js';
import MobileCard from '../../components/MobileCard';
import MobileConfirmModal from '../../components/MobileConfirmModal';
import MobileEmptyState from '../../components/MobileEmptyState';
import MobileSearchBar from '../../components/MobileSearchBar';
import MobileSelect from '../../components/MobileSelect';
import { UNIT_GROUPS, UNIT_REGISTRY, convert } from '../../../pages/Resources/resourceConstants.js';
import { areUnitsCompatible, isAccessDenied } from './resourceModel.js';

export default function MobileResourceConversions({ resources = [], canWrite, service = resourceApi, onRefresh, onAccessDenied }) {
    const [query, setQuery] = useState(''); const [resourceId, setResourceId] = useState(''); const [detail, setDetail] = useState(null); const [form, setForm] = useState({ name: '', quantity: '', unit_code: '' }); const [calc, setCalc] = useState({ quantity: '1', from: '', to: '' }); const [pending, setPending] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [remove, setRemove] = useState(null);
    const filtered = useMemo(() => resources.filter((item) => !query || `${item.name} ${item.code || ''}`.toLowerCase().includes(query.toLowerCase())), [query, resources]); const selected = resources.find((item) => String(item.id) === resourceId); const baseType = UNIT_REGISTRY[selected?.base_unit_code]?.type; const units = baseType ? UNIT_GROUPS[baseType] || [] : [];
    const fail = (nextError, fallback) => { if (isAccessDenied(nextError)) onAccessDenied?.(nextError); else setError(nextError?.response?.data?.message || nextError?.message || fallback); };
    useEffect(() => { if (!resourceId && resources[0]) setResourceId(String(resources[0].id)); }, [resourceId, resources]);
    useEffect(() => { if (!selected) return; setForm({ name: '', quantity: '', unit_code: selected.base_unit_code || '' }); setCalc({ quantity: '1', from: selected.base_unit_code || '', to: units.find((item) => item.code !== selected.base_unit_code)?.code || selected.base_unit_code || '' }); }, [selected, baseType]);
    const load = async () => { if (!resourceId) return; setLoading(true); setError(''); try { const response = await service.getResourceById(resourceId); setDetail(response?.resource || response); } catch (nextError) { fail(nextError, 'Conversions could not be loaded'); } finally { setLoading(false); } };
    useEffect(() => { load(); }, [resourceId]);
    const add = async (event) => { event.preventDefault(); if (!canWrite || !form.name.trim() || Number(form.quantity) <= 0) return; if (!areUnitsCompatible(selected.base_unit_code, form.unit_code)) { setError('Conversion unit must match the resource base-unit category.'); return; } setPending(true); setError(''); try { await service.addConversion(resourceId, { name: form.name.trim(), quantity: Number(form.quantity), unit_code: form.unit_code }); setForm((current) => ({ ...current, name: '', quantity: '' })); await load(); await onRefresh?.(); } catch (nextError) { fail(nextError, 'Conversion could not be added'); } finally { setPending(false); } };
    const destroy = async () => { if (!canWrite || !remove) return; setPending(true); setError(''); try { await service.removeConversion(resourceId, remove.id); setRemove(null); await load(); await onRefresh?.(); } catch (nextError) { fail(nextError, 'Conversion could not be removed'); } finally { setPending(false); } };
    let result = null; let calcError = ''; try { if (calc.quantity !== '' && calc.from && calc.to) result = convert(calc.from, calc.to, Number(calc.quantity)); } catch (nextError) { calcError = nextError.message; }
    if (resources.length === 0) return <MobileEmptyState title="No resources" description="Create a resource before defining conversions." />;
    return <div className="space-y-2" data-resource-workspace="conversions">
        <MobileSearchBar value={query} onChange={setQuery} placeholder="Search resources" /><MobileSelect label="Resource" value={resourceId} onChange={(event) => setResourceId(event.target.value)} options={filtered.map((item) => ({ value: String(item.id), label: `${item.name} · ${item.base_unit_code}` }))} />
        {error && <p role="alert" className="rounded-xl bg-red-50 p-2.5 text-xs font-normal text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
        {canWrite && <MobileCard><h3 className="text-xs font-semibold text-gray-900 dark:text-gh-text">Add named conversion</h3><p className="mt-0.5 text-[11px] font-normal text-gray-500">Example: 1 Bag = 50 kg</p><form onSubmit={add} className="mt-2.5 space-y-2.5"><label className="text-xs font-medium">Scale name<input required value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} className="mt-1 min-h-10 w-full rounded-xl border border-gray-200 bg-white px-3 dark:border-gh-border dark:bg-gh-input" /></label><label className="text-xs font-medium">Equivalent quantity<input required min="0" step="any" type="number" value={form.quantity} onChange={(event) => setForm((current) => ({ ...current, quantity: event.target.value }))} className="mt-1 min-h-10 w-full rounded-xl border border-gray-200 bg-white px-3 dark:border-gh-border dark:bg-gh-input" /></label><MobileSelect label="Unit" value={form.unit_code} onChange={(event) => setForm((current) => ({ ...current, unit_code: event.target.value }))} options={units.map((item) => ({ value: item.code, label: `${item.symbol} — ${item.name}` }))} /><button disabled={pending} className="min-h-10 w-full rounded-xl bg-blue-600 text-xs font-semibold text-white disabled:opacity-50">Add conversion</button></form></MobileCard>}
        <MobileCard><h3 className="text-xs font-semibold text-gray-900 dark:text-gh-text">Current conversions</h3>{loading ? <div className="mt-2 space-y-1.5 py-1"><div className="h-4 w-28 animate-pulse rounded bg-gray-200 dark:bg-white/10" /><div className="h-3 w-40 animate-pulse rounded bg-gray-200 dark:bg-white/10" /></div> : !detail?.conversions?.length ? <p className="mt-1.5 text-xs font-normal text-gray-500">No named conversions.</p> : <div className="mt-1.5 divide-y divide-gray-100 dark:divide-gh-border">{detail.conversions.map((item) => <div key={item.id} className="flex min-h-12 items-center gap-2"><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-gray-900 dark:text-gh-text">1 {item.name}</p><p className="text-[11px] font-normal text-gray-500">{item.quantity} {item.unit_code}</p></div>{canWrite && <button onClick={() => setRemove(item)} className="min-h-8 px-2 text-xs font-normal text-red-600">Delete</button>}</div>)}</div>}</MobileCard>
        <MobileCard><h3 className="text-xs font-semibold text-gray-900 dark:text-gh-text">Unit calculator</h3><div className="mt-2.5 space-y-2.5"><label className="text-xs font-medium">Quantity<input min="0" step="any" type="number" value={calc.quantity} onChange={(event) => setCalc((current) => ({ ...current, quantity: event.target.value }))} className="mt-1 min-h-10 w-full rounded-xl border border-gray-200 bg-white px-3 dark:border-gh-border dark:bg-gh-input" /></label><MobileSelect label="From" value={calc.from} onChange={(event) => setCalc((current) => ({ ...current, from: event.target.value }))} options={units.map((item) => ({ value: item.code, label: `${item.symbol} — ${item.name}` }))} /><MobileSelect label="To" value={calc.to} onChange={(event) => setCalc((current) => ({ ...current, to: event.target.value }))} options={units.map((item) => ({ value: item.code, label: `${item.symbol} — ${item.name}` }))} />{calcError ? <p className="text-xs font-normal text-red-600">{calcError}</p> : <p className="rounded-xl bg-blue-50 p-2.5 text-xs font-semibold text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{result === null ? 'Enter a quantity' : `${Number(result).toLocaleString('en-IN', { maximumFractionDigits: 6 })} ${calc.to}`}</p>}</div></MobileCard>
        <MobileConfirmModal open={Boolean(remove)} onClose={() => setRemove(null)} onConfirm={destroy} pending={pending} danger title={`Delete ${remove?.name || 'conversion'}?`} message="This removes the current named conversion. No conversion history is stored by the existing ERP." confirmLabel="Delete conversion" />
    </div>;
}
