import React, { useMemo, useState } from 'react';
import MobileDatePicker from '../../components/MobileDatePicker';
import MobileFormSection from '../../components/MobileFormSection';
import MobileSelect from '../../components/MobileSelect';
import MobileStickyActions from '../../components/MobileStickyActions';
import { UNIT_GROUPS, UNIT_REGISTRY } from '../../../pages/Resources/resourceConstants.js';
import { areUnitsCompatible, buildResourcePayload } from './resourceModel.js';

const today = () => new Date().toISOString().slice(0, 10);
const Field = ({ label, required, as: Component = 'input', ...props }) => <label className="block text-xs font-semibold text-gray-700 dark:text-gh-text">{label}{required && <span className="text-red-500"> *</span>}<Component required={required} className="mt-1.5 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm dark:border-gh-border dark:bg-gh-input dark:text-gh-text" {...props} /></label>;
const unitOptions = [{ value: '', label: 'Select unit' }, ...Object.entries(UNIT_GROUPS).flatMap(([type, units]) => units.map((unit) => ({ value: unit.code, label: `${unit.symbol} — ${unit.name} (${type})` })))];

export default function MobileResourceForm({ resource, resources = [], onSave, onCancel, pending = false }) {
    const editing = Boolean(resource);
    const [form, setForm] = useState({ name: resource?.name || '', code: resource?.code || '', type: resource?.type || 'material', base_unit_code: resource?.base_unit_code || '', description: resource?.description || '', remarks: resource?.remarks || '' });
    const [conversions, setConversions] = useState(() => (resource?.conversions || []).map((row) => ({ name: row.name || '', quantity: row.quantity || '', unit_code: row.unit_code || '' })));
    const [compositions, setCompositions] = useState(() => (resource?.compositions || []).map((row) => ({ component_resource_id: row.component_resource_id || '', quantity: row.quantity || '', unit_code: row.unit_code || '' })));
    const [effectiveFrom, setEffectiveFrom] = useState(today()); const [error, setError] = useState('');
    const components = useMemo(() => resources.filter((item) => item.type === 'material' || item.type === 'labour'), [resources]);
    const change = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
    const updateRow = (setter, index, key, nextValue) => setter((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: nextValue } : row));
    const submit = async (event) => {
        event.preventDefault(); setError('');
        if (!form.name.trim() || !form.base_unit_code) { setError('Resource name and base unit are required.'); return; }
        if (editing && resource.base_unit_code !== form.base_unit_code && !areUnitsCompatible(resource.base_unit_code, form.base_unit_code)) { setError('Base unit changes must remain in the original measurement category.'); return; }
        const invalidConversion = conversions.find((row) => row.name && (!Number(row.quantity) || !areUnitsCompatible(form.base_unit_code, row.unit_code)));
        if (invalidConversion) { setError('Every conversion needs a positive quantity and a unit compatible with the base unit.'); return; }
        await onSave(buildResourcePayload(form, { conversions, compositions, includeComposition: form.type === 'item', effectiveFrom }));
    };
    return <form onSubmit={submit} className="space-y-4" data-mobile-form="resource">
        {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
        <MobileFormSection title="Resource"><Field label="Name" required value={form.name} onChange={change('name')} /><Field label="Code" value={form.code} onChange={change('code')} /><MobileSelect label="Type" disabled={editing} value={form.type} onChange={change('type')} options={[{ value: 'material', label: 'Material' }, { value: 'item', label: 'Item (composite)' }, { value: 'labour', label: 'Labour' }]} hint={editing ? 'Type cannot be changed after creation.' : undefined} /><MobileSelect label="Base unit" value={form.base_unit_code} onChange={change('base_unit_code')} options={unitOptions.map((option) => ({ ...option, disabled: editing && option.value && !areUnitsCompatible(resource.base_unit_code, option.value) }))} /><Field label="Description" as="textarea" rows={3} value={form.description} onChange={change('description')} /><Field label="Remarks" as="textarea" rows={2} value={form.remarks} onChange={change('remarks')} /></MobileFormSection>
        <MobileFormSection title="Named conversions" description="For example, 1 Bag = 50 kg." actions={<button type="button" onClick={() => setConversions((current) => [...current, { name: '', quantity: '', unit_code: form.base_unit_code }])} className="min-h-11 px-2 text-xs font-bold text-blue-600">Add</button>}>{conversions.length === 0 ? <p className="text-xs text-gray-500">No named conversions.</p> : conversions.map((row, index) => <div key={index} className="space-y-2 rounded-xl bg-gray-50 p-3 dark:bg-gh-bg"><Field label="Name" value={row.name} onChange={(event) => updateRow(setConversions, index, 'name', event.target.value)} /><Field label="Quantity" type="number" min="0" step="any" value={row.quantity} onChange={(event) => updateRow(setConversions, index, 'quantity', event.target.value)} /><MobileSelect label="Unit" value={row.unit_code} onChange={(event) => updateRow(setConversions, index, 'unit_code', event.target.value)} options={unitOptions.filter((option) => !option.value || !form.base_unit_code || areUnitsCompatible(form.base_unit_code, option.value))} /><button type="button" onClick={() => setConversions((current) => current.filter((_, rowIndex) => rowIndex !== index))} className="min-h-11 text-xs font-bold text-red-600">Remove draft conversion</button></div>)}</MobileFormSection>
        {form.type === 'item' && <MobileFormSection title="Composition" description="A new effective-dated recipe version is created when saved." actions={<button type="button" onClick={() => setCompositions((current) => [...current, { component_resource_id: '', quantity: '', unit_code: '' }])} className="min-h-11 px-2 text-xs font-bold text-blue-600">Add</button>}><MobileDatePicker label="Effective from" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} />{compositions.map((row, index) => <div key={index} className="space-y-2 rounded-xl bg-gray-50 p-3 dark:bg-gh-bg"><MobileSelect label="Component" value={row.component_resource_id} onChange={(event) => { const component = components.find((item) => String(item.id) === event.target.value); setCompositions((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, component_resource_id: event.target.value, unit_code: component?.base_unit_code || item.unit_code } : item)); }} options={[{ value: '', label: 'Select component' }, ...components.map((item) => ({ value: String(item.id), label: `${item.name} (${item.type})` }))]} /><Field label="Quantity" type="number" min="0" step="any" value={row.quantity} onChange={(event) => updateRow(setCompositions, index, 'quantity', event.target.value)} /><MobileSelect label="Unit" value={row.unit_code} onChange={(event) => updateRow(setCompositions, index, 'unit_code', event.target.value)} options={unitOptions} /><button type="button" onClick={() => setCompositions((current) => current.filter((_, rowIndex) => rowIndex !== index))} className="min-h-11 text-xs font-bold text-red-600">Remove ingredient</button></div>)}</MobileFormSection>}
        <MobileStickyActions><button type="button" disabled={pending} onClick={onCancel} className="min-h-11 flex-1 rounded-xl border border-gray-200 text-sm font-bold dark:border-gh-border">Cancel</button><button disabled={pending} className="min-h-11 flex-[1.3] rounded-xl bg-blue-600 text-sm font-bold text-white disabled:opacity-50">{pending ? 'Saving…' : editing ? 'Save resource' : 'Create resource'}</button></MobileStickyActions>
    </form>;
}
