import React, { useMemo, useState } from 'react';
import { Boxes, MoreVertical, Plus } from 'lucide-react';
import { resourceApi } from '../../../services/resourceApi.js';
import { customToast } from '../../../utils/toast';
import MobileBottomSheet, { MobileActionSheet } from '../../components/MobileBottomSheet';
import MobileCard from '../../components/MobileCard';
import MobileConfirmModal from '../../components/MobileConfirmModal';
import MobileEmptyState from '../../components/MobileEmptyState';
import MobileFAB from '../../components/MobileFAB';
import MobileFilterSheet from '../../components/MobileFilterSheet';
import MobileSearchBar from '../../components/MobileSearchBar';
import MobileResourceDetail from './MobileResourceDetail';
import MobileResourceForm from './MobileResourceForm';
import { filterResources, isAccessDenied, normalizeResource } from './resourceModel.js';

const Choices = ({ values, selected, onChange }) => <div className="flex flex-wrap gap-2">{values.map((value) => <button key={value} type="button" aria-pressed={selected.includes(value)} onClick={() => onChange(selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value])} className={`min-h-11 rounded-xl border px-3 text-xs font-bold ${selected.includes(value) ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/40' : 'border-gray-200 dark:border-gh-border'}`}>{value}</button>)}</div>;

export default function MobileResourceDirectory({ resources: raw = [], canWrite, loading, service = resourceApi, onRefresh, onAccessDenied, onOpenTab }) {
    const [query, setQuery] = useState(''); const [filters, setFilters] = useState({ types: [], units: [] }); const [draft, setDraft] = useState(filters); const [filtersOpen, setFiltersOpen] = useState(false); const [selected, setSelected] = useState(null); const [actions, setActions] = useState(null); const [editing, setEditing] = useState(undefined); const [remove, setRemove] = useState(null); const [pending, setPending] = useState(false);
    const resources = useMemo(() => raw.map(normalizeResource), [raw]); const filtered = useMemo(() => filterResources(resources, { query, ...filters }), [filters, query, resources]); const units = useMemo(() => [...new Set(resources.map((item) => item.baseUnit).filter(Boolean))], [resources]);
    const fail = (error, fallback) => { if (isAccessDenied(error)) onAccessDenied?.(error); else customToast.error(error?.response?.data?.message || error?.message || fallback); };
    const openDetail = async (item) => { try { const response = await service.getResourceById(item.id); setSelected(normalizeResource(response?.resource || response || item)); } catch (error) { fail(error, 'Resource detail could not be loaded'); } };
    const save = async (payload) => { setPending(true); try { const result = editing ? await service.updateResource(editing.id, payload) : await service.createResource(payload); if (result?.success === false) throw new Error(result.message); setEditing(undefined); customToast.success(editing ? 'Resource updated' : 'Resource created'); await onRefresh?.(); } catch (error) { fail(error, 'Resource save failed'); } finally { setPending(false); } };
    const destroy = async () => { if (!canWrite || !remove) return; setPending(true); try { await service.deleteResource(remove.id); setRemove(null); setSelected(null); customToast.success('Resource deleted'); await onRefresh?.(); } catch (error) { fail(error, 'Resource delete failed'); } finally { setPending(false); } };
    return <div className="space-y-4" data-resource-workspace="directory">
        <div className="flex gap-2"><div className="min-w-0 flex-1"><MobileSearchBar value={query} onChange={setQuery} placeholder="Search name, code or type" /></div><button onClick={() => { setDraft(filters); setFiltersOpen(true); }} className="min-h-11 rounded-xl border border-gray-200 px-3 text-xs font-bold dark:border-gh-border">Filters</button></div>
        {loading ? <p className="py-10 text-center text-sm text-gray-500">Loading resources…</p> : filtered.length === 0 ? <MobileEmptyState title="No resources found" description="Try another search or filter." /> : <div className="space-y-3">{filtered.map((resource) => <MobileCard key={resource.id} className="p-0"><div className="flex gap-3 p-4"><button onClick={() => openDetail(resource)} className="flex min-h-11 min-w-0 flex-1 items-start gap-3 text-left"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-700 dark:bg-amber-950/40"><Boxes size={20} /></span><span className="min-w-0"><span className="block truncate text-sm font-black">{resource.name}</span><span className="block truncate font-mono text-xs text-gray-500">{resource.code || 'No code'}</span><span className="mt-1 block text-xs capitalize">{resource.type} · {resource.baseUnit}</span></span></button><button aria-label={`Actions for ${resource.name}`} onClick={() => setActions(resource)} className="min-h-11 min-w-11"><MoreVertical className="mx-auto" size={20} /></button></div></MobileCard>)}</div>}
        <MobileFilterSheet open={filtersOpen} onClose={() => setFiltersOpen(false)} onReset={() => setDraft({ types: [], units: [] })} onApply={() => { setFilters(draft); setFiltersOpen(false); }}><div><p className="mb-2 text-xs font-bold uppercase text-gray-500">Types</p><Choices values={['material', 'item', 'labour']} selected={draft.types} onChange={(types) => setDraft((current) => ({ ...current, types }))} /></div><div><p className="mb-2 text-xs font-bold uppercase text-gray-500">Base units</p><Choices values={units} selected={draft.units} onChange={(nextUnits) => setDraft((current) => ({ ...current, units: nextUnits }))} /></div></MobileFilterSheet>
        <MobileActionSheet open={Boolean(actions)} onClose={() => setActions(null)} title={actions?.name} actions={actions ? [{ label: 'View details', onSelect: () => openDetail(actions) }, ...(canWrite ? [{ label: 'Edit resource', onSelect: async () => { try { const response = await service.getResourceById(actions.id); setEditing(normalizeResource(response?.resource || response || actions)); } catch (error) { fail(error, 'Resource detail could not be loaded'); } } }, { label: 'Delete resource', danger: true, onSelect: () => setRemove(actions) }] : [])] : []} />
        <MobileResourceDetail resource={selected} open={Boolean(selected)} onClose={() => setSelected(null)} canWrite={canWrite} onEdit={(item) => { setSelected(null); setEditing(item); }} onDelete={setRemove} onOpenTab={(tab) => { setSelected(null); onOpenTab(tab); }} />
        <MobileBottomSheet open={editing !== undefined} onClose={() => setEditing(undefined)} title={editing ? 'Edit resource' : 'Create resource'}>{editing !== undefined && <MobileResourceForm resource={editing || null} resources={resources} pending={pending} onCancel={() => setEditing(undefined)} onSave={save} />}</MobileBottomSheet>
        <MobileConfirmModal open={Boolean(remove)} onClose={() => setRemove(null)} onConfirm={destroy} pending={pending} danger title={`Delete ${remove?.name || 'resource'}?`} message="The current ERP will reject deletion when this resource is still referenced." confirmLabel="Delete resource" />
        {canWrite && <MobileFAB label="Create resource" icon={Plus} onClick={() => setEditing(null)} />}
    </div>;
}
