import React, { useEffect, useMemo, useState } from 'react';
import { resourceApi } from '../../../services/resourceApi.js';
import { projectApi } from '../../../services/projectApi.js';
import { loadMobileProjects } from '../../hooks/useMobileProjects.js';
import MobileBottomSheet from '../../components/MobileBottomSheet';
import MobileCard from '../../components/MobileCard';
import MobileConfirmModal from '../../components/MobileConfirmModal';
import MobileDatePicker from '../../components/MobileDatePicker';
import MobileEmptyState from '../../components/MobileEmptyState';
import MobileSearchBar from '../../components/MobileSearchBar';
import MobileSelect from '../../components/MobileSelect';
import { UNIT_OPTIONS } from '../../../pages/Resources/resourceConstants.js';
import { isAccessDenied } from './resourceModel.js';
import { resourceRateServices } from './resourceContracts.js';

const today = () => new Date().toISOString().slice(0, 10);
const dateOnly = (value) => value ? String(value).slice(0, 10) : '';
const productionRateServices = resourceRateServices(resourceApi, projectApi);

export default function MobileResourceRates({ resources = [], canWrite, service = productionRateServices.master, projectService = productionRateServices.project, loadProjects = loadMobileProjects, onRefresh, onAccessDenied }) {
    const [query, setQuery] = useState(''); const [resourceId, setResourceId] = useState(''); const [projectId, setProjectId] = useState(''); const [projects, setProjects] = useState([]); const [asOf, setAsOf] = useState(today()); const [resolved, setResolved] = useState(null); const [history, setHistory] = useState([]); const [form, setForm] = useState({ rate: '', unit_code: '', effective_from: today(), remarks: '' }); const [editing, setEditing] = useState(null); const [confirmClear, setConfirmClear] = useState(false); const [loading, setLoading] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState('');
    const filtered = useMemo(() => resources.filter((item) => !query || `${item.name} ${item.code || ''}`.toLowerCase().includes(query.toLowerCase())), [query, resources]); const selected = resources.find((item) => String(item.id) === resourceId); const active = history.find((item) => Number(item.is_active) === 1);
    const fail = (nextError, fallback) => { if (isAccessDenied(nextError)) onAccessDenied?.(nextError); else setError(nextError?.response?.data?.message || nextError?.message || fallback); };
    useEffect(() => { loadProjects().then((result) => setProjects(result?.projects || [])).catch(() => setProjects([])); }, [loadProjects]);
    useEffect(() => { if (!resourceId && resources[0]) setResourceId(String(resources[0].id)); }, [resourceId, resources]);
    useEffect(() => { if (selected) setForm((current) => ({ ...current, unit_code: selected.base_unit_code || '' })); }, [selected]);
    const load = async () => {
        if (!resourceId) return; setLoading(true); setError('');
        try { const [rateResult, historyResult] = await Promise.all(projectId ? [projectService.resolved(projectId, resourceId, asOf), projectService.history(projectId, resourceId)] : [service.resolved(resourceId, asOf), service.history(resourceId)]); setResolved(rateResult?.rate || null); setHistory(historyResult?.rates || []); }
        catch (nextError) { fail(nextError, 'Rate information could not be loaded'); } finally { setLoading(false); }
    };
    useEffect(() => { load(); }, [asOf, projectId, resourceId]);
    const saveNew = async (event) => { event.preventDefault(); if (!canWrite || !resourceId || form.rate === '') return; setPending(true); setError(''); try { const payload = { rate: Number(form.rate), unit_code: form.unit_code || selected?.base_unit_code, effective_from: form.effective_from, remarks: form.remarks || undefined }; if (projectId) await projectService.add(projectId, resourceId, payload); else await service.add(resourceId, payload); setForm((current) => ({ ...current, rate: '', remarks: '' })); await load(); await onRefresh?.(); } catch (nextError) { fail(nextError, 'Rate could not be saved'); } finally { setPending(false); } };
    const saveEdit = async (event) => { event.preventDefault(); if (!canWrite || !editing) return; setPending(true); setError(''); try { const payload = { mode: editing.mode, rate: editing.mode === 'computed' ? null : Number(editing.rate), unit_code: editing.unit_code, effective_from: editing.effective_from, effective_to: editing.effective_to || null, remarks: editing.remarks || undefined }; if (projectId) await projectService.update(projectId, resourceId, editing.id, payload); else await service.update(resourceId, editing.id, payload); setEditing(null); await load(); await onRefresh?.(); } catch (nextError) { fail(nextError, 'Rate version could not be updated'); } finally { setPending(false); } };
    const clear = async () => { if (!canWrite || !resourceId) return; setPending(true); setError(''); try { if (projectId) await projectService.clear(projectId, resourceId, form.effective_from); else await service.clear(resourceId, form.effective_from); setConfirmClear(false); await load(); await onRefresh?.(); } catch (nextError) { fail(nextError, 'Rate could not be reverted'); } finally { setPending(false); } };
    if (resources.length === 0) return <MobileEmptyState title="No resources" description="Create a resource before managing rates." />;
    return <div className="space-y-4" data-resource-workspace="rates">
        <MobileSearchBar value={query} onChange={setQuery} placeholder="Search resources" /><MobileSelect label="Resource" value={resourceId} onChange={(event) => setResourceId(event.target.value)} options={filtered.map((item) => ({ value: String(item.id), label: `${item.name}${item.code ? ` · ${item.code}` : ''}` }))} /><MobileSelect label="Scope" value={projectId} onChange={(event) => setProjectId(event.target.value)} options={[{ value: '', label: 'Master / Organization' }, ...projects.map((item) => ({ value: String(item.id), label: item.name }))]} /><MobileDatePicker label="Resolve as of" value={asOf} onChange={(event) => setAsOf(event.target.value)} />
        {error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300">{error}</p>}
        <MobileCard>{loading ? <p className="text-sm text-gray-500">Resolving rate…</p> : <><p className="text-xs font-bold uppercase text-gray-500">Effective rate</p><p className="mt-2 text-2xl font-black">{resolved?.rate === null || resolved?.rate === undefined ? 'Unavailable' : `₹${Number(resolved.rate).toLocaleString('en-IN')}`}</p><p className="mt-1 text-xs text-gray-500">{resolved?.source || 'No active manual or computed rate'}{resolved?.unitCode ? ` · ${resolved.unitCode}` : ''}</p></>}</MobileCard>
        {canWrite && <MobileCard><h3 className="text-sm font-black">Add rate version</h3><form onSubmit={saveNew} className="mt-3 space-y-3"><label className="text-xs font-semibold">Rate<input required min="0" step="any" type="number" value={form.rate} onChange={(event) => setForm((current) => ({ ...current, rate: event.target.value }))} className="mt-1 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 dark:border-gh-border dark:bg-gh-input" /></label><MobileSelect label="Unit" value={form.unit_code} onChange={(event) => setForm((current) => ({ ...current, unit_code: event.target.value }))} options={UNIT_OPTIONS.map((item) => ({ value: item.code, label: `${item.symbol} — ${item.name}` }))} /><MobileDatePicker label="Effective from" value={form.effective_from} onChange={(event) => setForm((current) => ({ ...current, effective_from: event.target.value }))} /><label className="text-xs font-semibold">Remarks<textarea value={form.remarks} onChange={(event) => setForm((current) => ({ ...current, remarks: event.target.value }))} className="mt-1 min-h-20 w-full rounded-xl border border-gray-200 bg-white p-3 dark:border-gh-border dark:bg-gh-input" /></label><button disabled={pending} className="min-h-11 w-full rounded-xl bg-blue-600 text-sm font-bold text-white disabled:opacity-50">Save new version</button>{active && <button type="button" disabled={pending} onClick={() => setConfirmClear(true)} className="min-h-11 w-full text-sm font-bold text-red-600">{projectId ? 'Revert to master' : 'Revert to computed/unset'}</button>}</form></MobileCard>}
        <MobileCard><h3 className="text-sm font-black">Rate history</h3>{history.length === 0 ? <p className="mt-2 text-xs text-gray-500">No manual rate versions.</p> : <div className="mt-3 space-y-2">{history.map((item) => <div key={item.id} className="rounded-xl border border-gray-100 p-3 text-xs dark:border-gh-border"><div className="flex justify-between"><span className="font-black">{item.rate === null ? 'Computed' : `₹${Number(item.rate).toLocaleString('en-IN')}`}</span><span>{dateOnly(item.effective_from)}</span></div><p className="mt-1 text-gray-500">{item.effective_to ? `through ${dateOnly(item.effective_to)}` : 'Current'} · {item.unit_code}</p>{canWrite && Number(item.is_active) === 1 && <button onClick={() => setEditing({ ...item, rate: item.rate ?? '', mode: item.rate === null ? 'computed' : 'manual', effective_from: dateOnly(item.effective_from), effective_to: dateOnly(item.effective_to) })} className="mt-2 min-h-11 text-xs font-bold text-blue-600">Edit active version</button>}</div>)}</div>}</MobileCard>
        <MobileBottomSheet open={Boolean(editing)} onClose={() => setEditing(null)} title="Edit active rate"><form onSubmit={saveEdit} className="space-y-3"><MobileSelect label="Mode" value={editing?.mode || 'manual'} onChange={(event) => setEditing((current) => ({ ...current, mode: event.target.value }))} options={[{ value: 'manual', label: 'Manual' }, ...(selected?.type === 'item' ? [{ value: 'computed', label: 'Computed from recipe' }] : [])]} />{editing?.mode === 'manual' && <label className="text-xs font-semibold">Rate<input required min="0" step="any" type="number" value={editing?.rate ?? ''} onChange={(event) => setEditing((current) => ({ ...current, rate: event.target.value }))} className="mt-1 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 dark:border-gh-border dark:bg-gh-input" /></label>}<MobileDatePicker label="Effective from" value={editing?.effective_from || ''} onChange={(event) => setEditing((current) => ({ ...current, effective_from: event.target.value }))} /><MobileDatePicker label="Effective to" value={editing?.effective_to || ''} onChange={(event) => setEditing((current) => ({ ...current, effective_to: event.target.value }))} /><button disabled={pending} className="min-h-11 w-full rounded-xl bg-blue-600 text-sm font-bold text-white">Save active version</button></form></MobileBottomSheet>
        <MobileConfirmModal open={confirmClear} onClose={() => setConfirmClear(false)} onConfirm={clear} pending={pending} danger title={projectId ? 'Revert project rate?' : 'Clear manual rate?'} message={`The change becomes effective ${form.effective_from}.`} confirmLabel="Confirm revert" />
    </div>;
}
