import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Plus, Sparkles } from 'lucide-react';
import api from '../../../../services/api';
import { BUDGET_SECTIONS, PROJECT_DEFAULTS } from '../../../../pages/ProjectDetails/Contracts/Budget/budgetData';
import MobileBottomSheet from '../../../components/MobileBottomSheet';
import MobileCard, { MobileEntityCard, MobileStatCard } from '../../../components/MobileCard';
import MobileFAB from '../../../components/MobileFAB';
import MobileFormSection from '../../../components/MobileFormSection';
import MobilePageHeader from '../../../components/MobilePageHeader';
import MobileStickyActions from '../../../components/MobileStickyActions';
import MobileProjectContracts from './MobileProjectContracts';
import { budgetChartData, clone, computeBudgetSection, createM9RequestGuard, errorMessage, makeLocalId, updateSearch } from '../M9/mobileM9Model';

const field = (label, value, update, type = 'text') => <label className="block text-xs font-semibold">{label}<input type={type} value={value ?? ''} onChange={(event) => update(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-gray-200 bg-transparent px-3 text-sm dark:border-gh-border"/></label>;
const money = (value) => `₹${Math.round(Number(value) || 0).toLocaleString('en-IN')}`;

function Chart({ data, mode }) { return <MobileCard data-budget-chart={mode}><h3 className="text-sm font-black">{mode === 'distribution' ? 'Basic-cost distribution' : 'Section comparison'}</h3><p className="mt-1 text-xs text-gray-500">Derived immediately from current local section edits.</p>{data.map((section) => <div key={section.id} className="mt-3"><div className="flex justify-between gap-2 text-xs"><b className="truncate">{section.name}</b><span>{mode === 'distribution' ? `${section.share.toFixed(1)}%` : `${money(section.basic)} / ${money(section.consumed)}`}</span></div><div className="mt-1 h-3 rounded bg-gray-100 dark:bg-gh-hover"><span className="block h-full rounded bg-blue-600" style={{ width: `${mode === 'distribution' ? section.share : Math.min(100, section.basic ? (section.consumed / section.basic) * 100 : 0)}%` }}/></div></div>)}</MobileCard>; }

function Budget({ projectId, canWrite, services = {} }) {
    const [params, setParams] = useSearchParams(); const [sections, setSections] = useState(() => clone(BUDGET_SECTIONS)); const [editor, setEditor] = useState(null); const [ai, setAi] = useState({ state: 'idle', rows: [], error: '' }); const guard = useRef(createM9RequestGuard()); const sectionId = params.get('section');
    useEffect(() => { guard.current.invalidate(projectId); setSections(clone(BUDGET_SECTIONS)); setEditor(null); setAi({ state: 'idle', rows: [], error: '' }); }, [projectId]);
    const computed = useMemo(() => sections.map((section) => computeBudgetSection(section, PROJECT_DEFAULTS.slabArea, PROJECT_DEFAULTS.gstRate)), [sections]); const charts = budgetChartData(computed); const active = computed.find((section) => section.id === sectionId); const summary = sectionId === 'summary';
    const setSection = (value) => setParams(updateSearch(params, { section: value })); const updateFirstLine = (value) => { if (!canWrite || !active?.items[0]) return; setSections((current) => current.map((section) => section.id === active.id ? { ...section, items: section.items.map((item, index) => index ? item : { ...item, consumed: Math.max(0, Number(value)) }) } : section)); };
    const addSection = (event) => { event.preventDefault(); if (!canWrite || !editor?.name?.trim()) return; setSections((current) => [...current, { id: makeLocalId('budget-section'), name: editor.name, srNo: String(current.length + 1), iconKey: 'Package', desc: '', items: [] }]); setEditor(null); };
    const loadAi = async () => { const token = guard.current.begin(projectId); setAi({ state: 'loading', rows: [], error: '' }); try { const budgetData = active ? [sections.find((section) => section.id === active.id)] : sections; const response = await (services.ai?.budgetInsights ? services.ai.budgetInsights({ budgetData, slabArea: PROJECT_DEFAULTS.slabArea, gstRate: PROJECT_DEFAULTS.gstRate, sectionId: active?.id || 'all' }) : api.post('/ai/analyze-budget', { budgetData, slabArea: PROJECT_DEFAULTS.slabArea, gstRate: PROJECT_DEFAULTS.gstRate, sectionId: active?.id || 'all' }).then((result) => result.data)); if (guard.current.isCurrent(token, projectId)) setAi({ state: 'success', rows: response?.data?.insights || response?.insights || [], error: '' }); } catch (error) { if (guard.current.isCurrent(token, projectId)) setAi({ state: 'error', rows: [], error: errorMessage(error, 'AI budget insights could not be loaded.') }); } };
    if (active) return <div data-m9-view="budget-section" className="space-y-3 px-4 pb-28"><MobilePageHeader title={active.name} subtitle="Local budget section" onBack={() => setSection(null)}/><MobileStatCard label="Basic" value={money(active.basic)}/><MobileCard><h3 className="text-sm font-black">Local line items</h3>{active.items.map((item, index) => <div key={item.id} className="mt-3 rounded-xl bg-gray-50 p-3 text-xs dark:bg-gh-hover"><b>{item.srNo} · {item.description}</b><p>{item.quantity} {item.unit} · basic {money(item.basic)} · consumed {money(item.consumed)}</p>{canWrite && index === 0 && field('Consumed amount', item.consumed, updateFirstLine, 'number')}</div>)}</MobileCard><Chart data={charts.filter((item) => item.id === active.id)} mode="comparison"/><button type="button" onClick={loadAi} className="min-h-11 w-full rounded-xl bg-violet-600 text-xs font-bold text-white"><Sparkles size={15} className="mr-1 inline"/>AI insights</button><MobileBottomSheet open={ai.state !== 'idle'} onClose={() => { guard.current.invalidate(projectId); setAi({ state: 'idle', rows: [], error: '' }); }} title="AI Budget Insights">{ai.state === 'loading' ? <p role="status">Analysing budget…</p> : ai.state === 'error' ? <div className="space-y-3"><p>{ai.error}</p><button type="button" onClick={loadAi} className="min-h-11 rounded-xl bg-violet-600 px-4 font-bold text-white">Retry</button></div> : ai.rows.map((row, index) => <MobileCard key={index}>{row.title || row.message || String(row)}</MobileCard>)}</MobileBottomSheet></div>;
    if (summary) return <div data-m9-view="budget-summary" className="space-y-3 px-4 pb-28"><MobilePageHeader title="Budget Summary" subtitle="All local source sections" onBack={() => setSection(null)}/><Chart data={charts} mode="distribution"/><Chart data={charts} mode="comparison"/>{computed.map((section) => <MobileEntityCard key={section.id} title={section.name} subtitle={`${money(section.basic)} basic`} meta={`${section.items.length} lines · ${section.utilisation.toFixed(1)}% used`} onClick={() => setSection(section.id)}/>)}</div>;
    return <div data-m9-view="budget-landing" className="space-y-3 px-4 pb-28"><MobilePageHeader title="Project Budget" subtitle="Contracts-owned local budget"/><p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/30 dark:text-amber-200">Seeded budget values and edits are frontend-local. No durable ERP budget save contract exists in the source.</p><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setSection('summary')} className="min-h-11 rounded-xl border text-xs font-bold dark:border-gh-border">Summary & charts</button><button type="button" onClick={loadAi} className="min-h-11 rounded-xl bg-violet-600 text-xs font-bold text-white">AI insights</button></div><Chart data={charts} mode="distribution"/><Chart data={charts} mode="comparison"/>{computed.map((section) => <MobileEntityCard key={section.id} title={section.name} subtitle={`${section.items.length} lines · ${money(section.basic)}`} meta={`${charts.find((row) => row.id === section.id)?.share.toFixed(1)}% of basic`} onClick={() => setSection(section.id)}/>) }{canWrite && <MobileFAB label="New section" extended onClick={() => setEditor({ name: '' })}/>}<MobileBottomSheet open={Boolean(editor)} onClose={() => setEditor(null)} title="New budget section" footer={<MobileStickyActions><button form="budget-new-section" className="min-h-11 flex-1 rounded-xl bg-blue-600 font-bold text-white">Apply local change</button></MobileStickyActions>}><form id="budget-new-section" onSubmit={addSection}><MobileFormSection title="Local section">{field('Name', editor?.name, (value) => setEditor((current) => ({ ...current, name: value })))}</MobileFormSection></form></MobileBottomSheet><MobileBottomSheet open={ai.state !== 'idle'} onClose={() => { guard.current.invalidate(projectId); setAi({ state: 'idle', rows: [], error: '' }); }} title="AI Budget Insights">{ai.state === 'loading' ? <p role="status">Analysing budget…</p> : ai.state === 'error' ? <div className="space-y-3"><p>{ai.error}</p><button type="button" onClick={loadAi} className="min-h-11 rounded-xl bg-violet-600 px-4 font-bold text-white">Retry</button></div> : ai.rows.map((row, index) => <MobileCard key={index}>{row.title || row.message || String(row)}</MobileCard>)}</MobileBottomSheet></div>;
}

export default function MobileProjectContractsParity(props) { const [params] = useSearchParams(); return params.get('report') === 'budget' || params.get('section') ? <Budget {...props}/> : <MobileProjectContracts {...props}/>; }
