import React, { useEffect, useRef, useState } from 'react';
import { Plus } from 'lucide-react';
import { MobileCard } from '../../../components/MobileCard';
import MobileBottomSheet from '../../../components/MobileBottomSheet';
import MobileConfirmModal from '../../../components/MobileConfirmModal';
import MobileEmptyState from '../../../components/MobileEmptyState';
import MobileFAB from '../../../components/MobileFAB';
import { createGeneralDocumentsRequestGuard, summaryPayload } from './mobileGeneralDocumentsModel';
const field = 'mt-1 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm dark:border-gh-border dark:bg-gh-input dark:text-gh-text';
export default function MobileProjectSummary({ projectId, canWrite, api }) {
    const [rows, setRows] = useState([]); const [editor, setEditor] = useState(null); const [confirm, setConfirm] = useState(null); const [pending, setPending] = useState(false); const [error, setError] = useState(''); const guard = useRef(createGeneralDocumentsRequestGuard()); const activeProject = useRef(projectId); const current = (origin) => String(activeProject.current) === String(origin);
    const refresh = async (origin = projectId) => { const token = guard.current.begin(origin, 'summary'); if (current(origin)) setError(''); try { const response = await api.getSummaries(origin); if (current(origin) && guard.current.isCurrent(token)) setRows(response.summaries || []); } catch (err) { if (current(origin) && guard.current.isCurrent(token)) setError(err?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : 'Project summary could not be loaded.'); } };
    useEffect(() => { activeProject.current = projectId; setRows([]); setEditor(null); setConfirm(null); setPending(false); refresh(projectId); }, [projectId]);
    const save = async (event) => { event.preventDefault(); const origin = projectId; if (!canWrite || !current(origin)) return; const editing = editor; const value = Object.fromEntries(new FormData(event.currentTarget).entries()); setPending(true); try { if (editing?.id) await api.updateSummaries(origin, [summaryPayload(value, editing.id)]); else await api.addSummaries(origin, [summaryPayload(value)]); if (!current(origin)) return; setEditor(null); await refresh(origin); } catch { if (current(origin)) setError('Summary milestone could not be saved.'); } finally { if (current(origin)) setPending(false); } };
    const remove = async () => { const origin = projectId; const target = confirm; if (!canWrite || !target || !current(origin)) return; setPending(true); try { await api.deleteSummaries(origin, [target.id]); if (!current(origin)) return; setConfirm(null); await refresh(origin); } catch { if (current(origin)) setError('Summary milestone could not be deleted.'); } finally { if (current(origin)) setPending(false); } };
    return <div data-m6-view="summary" className="space-y-3 px-4 pb-28">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="space-y-3 border-l-2 border-blue-200 pl-4 dark:border-blue-900">{rows.map((row) => <MobileCard key={row.id} className="relative"><span className="absolute -left-[1.45rem] top-5 h-3 w-3 rounded-full bg-blue-600" /><button type="button" className="w-full text-left" onClick={() => canWrite && setEditor(row)}><p className="text-[10px] font-bold uppercase text-blue-600">{row.status || 'No status'} · {row.date || 'No date'}</p><h3 className="mt-1 text-sm font-bold">{row.title || 'Untitled milestone'}</h3>{row.details && <p className="mt-2 text-xs leading-5 text-gray-600 dark:text-gh-muted">{row.details}</p>}</button>{canWrite && <button type="button" onClick={() => setConfirm(row)} className="mt-3 text-xs font-bold text-red-600">Delete</button>}</MobileCard>)}{rows.length === 0 && <MobileEmptyState title="No summary milestones" />}</div>{canWrite && <MobileFAB extended label="Add milestone" icon={Plus} onClick={() => setEditor({ title: '', date: '', status: 'in_progress', details: '' })} />}<MobileBottomSheet open={editor !== null} onClose={() => !pending && setEditor(null)} closeDisabled={pending} title={editor?.id ? 'Edit milestone' : 'Add milestone'} footer={<div className="flex gap-2"><button type="button" onClick={() => setEditor(null)} className="min-h-11 flex-1 rounded-xl border">Cancel</button><button form="summary-form" type="submit" disabled={pending} className="min-h-11 flex-1 rounded-xl bg-blue-600 font-bold text-white">Save</button></div>}><form id="summary-form" onSubmit={save} className="space-y-4"><label className="block text-xs font-semibold">Title<input required name="title" defaultValue={editor?.title || ''} className={field} /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-semibold">Date<input type="date" name="date" defaultValue={editor?.date?.slice?.(0, 10) || ''} className={field} /></label><label className="block text-xs font-semibold">Status<input name="status" defaultValue={editor?.status || ''} className={field} /></label></div><label className="block text-xs font-semibold">Details<textarea name="details" defaultValue={editor?.details || ''} className={`${field} min-h-24 py-2`} /></label></form></MobileBottomSheet><MobileConfirmModal open={confirm !== null} pending={pending} danger title="Delete milestone" message={`Delete ${confirm?.title || 'this milestone'}?`} confirmLabel="Delete" onClose={() => setConfirm(null)} onConfirm={remove} /></div>;
}
