import React, { useEffect, useRef, useState } from 'react';
import { Plus } from 'lucide-react';
import { MobileCard } from '../../../components/MobileCard';
import MobileBottomSheet from '../../../components/MobileBottomSheet';
import MobileConfirmModal from '../../../components/MobileConfirmModal';
import MobileEmptyState from '../../../components/MobileEmptyState';
import MobileFAB from '../../../components/MobileFAB';
import MobileSearchBar from '../../../components/MobileSearchBar';
import { createGeneralDocumentsRequestGuard, directoryPayload, normalizeDirectory } from './mobileGeneralDocumentsModel';
const blank = { contactPerson: '', designation: '', responsibilities: '', mobileNo: '', email: '', addressLine: '', partyId: '' }; const field = 'mt-1 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm dark:border-gh-border dark:bg-gh-input dark:text-gh-text';
export default function MobileProjectDirectory({ projectId, canWrite, api }) {
    const [contacts, setContacts] = useState([]); const [parties, setParties] = useState([]); const [query, setQuery] = useState(''); const [editor, setEditor] = useState(null); const [confirm, setConfirm] = useState(null); const [pending, setPending] = useState(false); const [error, setError] = useState(''); const guard = useRef(createGeneralDocumentsRequestGuard()); const activeProject = useRef(projectId); const current = (origin) => String(activeProject.current) === String(origin);
    const refresh = async (origin = projectId) => { const token = guard.current.begin(origin, 'directory'); if (current(origin)) setError(''); try { const [directory, partyData] = await Promise.all([api.getDirectory(origin), api.getParties(origin)]); if (current(origin) && guard.current.isCurrent(token)) { setContacts(normalizeDirectory(directory)); setParties(partyData.parties || []); } } catch (err) { if (current(origin) && guard.current.isCurrent(token)) setError(err?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : 'Project directory could not be loaded.'); } };
    useEffect(() => { activeProject.current = projectId; setEditor(null); setConfirm(null); setPending(false); setContacts([]); setParties([]); refresh(projectId); }, [projectId]);
    const save = async (event) => { event.preventDefault(); const origin = projectId; if (!canWrite || !current(origin)) return; const editing = editor; const value = Object.fromEntries(new FormData(event.currentTarget).entries()); setPending(true); try { const payload = directoryPayload(value); if (editing?.id) await api.updateDirectoryItem(origin, editing.id, payload); else await api.addDirectoryItem(origin, payload); if (!current(origin)) return; setEditor(null); await refresh(origin); } catch { if (current(origin)) setError('Directory contact could not be saved.'); } finally { if (current(origin)) setPending(false); } };
    const remove = async () => { const origin = projectId; const target = confirm; if (!canWrite || !target || !current(origin)) return; setPending(true); try { await api.deleteDirectoryItem(origin, target.id); if (!current(origin)) return; setConfirm(null); await refresh(origin); } catch { if (current(origin)) setError('Directory contact could not be deleted.'); } finally { if (current(origin)) setPending(false); } };
    const visible = contacts.filter((contact) => [contact.companyName, contact.contactPerson, contact.designation, contact.mobileNo, contact.email].join(' ').toLowerCase().includes(query.toLowerCase()));
    return <div data-m6-view="directory" className="space-y-3 px-4 pb-28">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<MobileSearchBar value={query} onChange={setQuery} placeholder="Search directory" /><div className="space-y-3">{visible.map((contact) => <MobileCard key={contact.id}><button type="button" className="w-full text-left" onClick={() => canWrite && setEditor(contact)}><p className="text-sm font-bold">{contact.contactPerson || 'Unnamed contact'}</p><p className="mt-1 text-xs text-gray-500">{[contact.companyName, contact.designation].filter(Boolean).join(' · ') || 'No organisation'}</p><p className="mt-2 text-xs text-gray-600 dark:text-gh-muted">{contact.mobileNo || 'No mobile'}{contact.email ? ` · ${contact.email}` : ''}</p></button>{canWrite && <button type="button" onClick={() => setConfirm(contact)} className="mt-3 text-xs font-bold text-red-600">Delete</button>}</MobileCard>)}{visible.length === 0 && <MobileEmptyState title="No directory contacts" description="Add a contact linked to an existing project party." />}</div>{canWrite && <MobileFAB extended label="Add contact" icon={Plus} onClick={() => setEditor(blank)} />}<MobileBottomSheet open={editor !== null} onClose={() => !pending && setEditor(null)} closeDisabled={pending} title={editor?.id ? 'Edit directory contact' : 'Add directory contact'} footer={<div className="flex gap-2"><button type="button" onClick={() => setEditor(null)} className="min-h-11 flex-1 rounded-xl border">Cancel</button><button form="directory-contact-form" disabled={pending} type="submit" className="min-h-11 flex-1 rounded-xl bg-blue-600 font-bold text-white">Save</button></div>}><form id="directory-contact-form" onSubmit={save} className="space-y-4"><label className="block text-xs font-semibold">Project party<select name="partyId" defaultValue={editor?.partyId || ''} className={field}><option value="">No linked party</option>{parties.map((party) => <option key={party.id || party.pv_id} value={party.id || party.pv_id}>{party.name}</option>)}</select></label>{[['contactPerson', 'Contact person'], ['designation', 'Designation'], ['responsibilities', 'Responsibilities'], ['mobileNo', 'Mobile number'], ['email', 'Email'], ['addressLine', 'Address']].map(([name, label]) => <label key={name} className="block text-xs font-semibold">{label}{name === 'responsibilities' || name === 'addressLine' ? <textarea name={name} defaultValue={editor?.[name] || ''} className={`${field} min-h-20 py-2`} /> : <input name={name} defaultValue={editor?.[name] || ''} className={field} />}</label>)}</form></MobileBottomSheet><MobileConfirmModal open={confirm !== null} pending={pending} danger title="Delete directory contact" message={`Delete ${confirm?.contactPerson || 'this contact'}?`} onClose={() => setConfirm(null)} onConfirm={remove} confirmLabel="Delete" /></div>;
}
