import React, { useEffect, useRef, useState } from 'react';
import { CalendarPlus } from 'lucide-react';
import { MobileCard } from '../../../components/MobileCard';
import MobileConfirmModal from '../../../components/MobileConfirmModal';
import MobileEmptyState from '../../../components/MobileEmptyState';
import MobileFAB from '../../../components/MobileFAB';
import MobileLoadingState from '../../../components/MobileLoadingState';
import MobileMeetingEditor from './MobileMeetingEditor';
import { createGeneralDocumentsRequestGuard, meetingPayload } from './mobileGeneralDocumentsModel';

export default function MobileProjectMeetings({ projectId, canWrite, api }) {
    const [meetings, setMeetings] = useState([]); const [directory, setDirectory] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editor, setEditor] = useState(null); const [confirm, setConfirm] = useState(null); const [pending, setPending] = useState(false); const guard = useRef(createGeneralDocumentsRequestGuard()); const activeProject = useRef(projectId);
    const current = (origin) => String(activeProject.current) === String(origin);
    const refresh = async (origin = projectId) => { const token = guard.current.begin(origin, 'meetings'); if (current(origin)) { setLoading(true); setError(''); } try { const [meetingResponse, directoryResponse] = await Promise.all([api.getMeetings(origin), api.getDirectory(origin)]); if (current(origin) && guard.current.isCurrent(token)) { setMeetings(meetingResponse.meetings || []); setDirectory(directoryResponse.directory || []); } } catch (err) { if (current(origin) && guard.current.isCurrent(token)) setError(err?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : 'Project meetings could not be loaded.'); } finally { if (current(origin) && guard.current.isCurrent(token)) setLoading(false); } };
    useEffect(() => { activeProject.current = projectId; setEditor(null); setConfirm(null); setPending(false); setMeetings([]); setDirectory([]); refresh(projectId); }, [projectId]);
    const open = async (meeting) => { const origin = projectId; if (!meeting?.id && !meeting?.meeting_id) { if (canWrite && current(origin)) setEditor({}); return; } const token = guard.current.begin(origin, 'meeting-detail'); if (current(origin)) setPending(true); try { const response = await api.getMeeting(origin, meeting.id || meeting.meeting_id); if (current(origin) && guard.current.isCurrent(token)) setEditor(response.meeting || meeting); } catch { if (current(origin) && guard.current.isCurrent(token)) setError('Meeting details could not be loaded.'); } finally { if (current(origin) && guard.current.isCurrent(token)) setPending(false); } };
    const save = async (value) => { const origin = projectId; if (!canWrite || !current(origin)) return; const editing = editor; setPending(true); try { const payload = meetingPayload(value); if (editing?.id || editing?.meeting_id) await api.updateMeeting(origin, editing.id || editing.meeting_id, payload); else await api.createMeeting(origin, payload); if (!current(origin)) return; setEditor(null); await refresh(origin); } catch { if (current(origin)) setError('Meeting could not be saved.'); } finally { if (current(origin)) setPending(false); } };
    const remove = async () => { const origin = projectId; const target = confirm; if (!canWrite || !target || !current(origin)) return; setPending(true); try { await api.deleteMeeting(origin, target.id || target.meeting_id); if (!current(origin)) return; setConfirm(null); await refresh(origin); } catch { if (current(origin)) setError('Meeting could not be deleted.'); } finally { if (current(origin)) setPending(false); } };
    if (loading) return <div className="px-4 pb-28"><MobileLoadingState label="Loading meetings" rows={3} /></div>;
    return <div data-m6-view="meetings" className="space-y-3 px-4 pb-28">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="space-y-3">{meetings.map((meeting) => <MobileCard key={meeting.id || meeting.meeting_id}><button type="button" className="w-full text-left" onClick={() => open(meeting)}><p className="text-[10px] font-bold uppercase text-blue-600">Meeting {meeting.meeting_no || '—'}</p><h3 className="mt-1 text-sm font-bold">{meeting.subject || 'Untitled meeting'}</h3><p className="mt-2 text-xs text-gray-600 dark:text-gh-muted">{[meeting.date, meeting.time, meeting.venue].filter(Boolean).join(' · ') || 'No date or venue'}</p><p className="mt-2 text-xs text-gray-500">{meeting.participants_count || 0} participants · {meeting.agenda_count || 0} agenda points · {meeting.mom_count || 0} minutes</p></button>{canWrite && <button type="button" className="mt-3 text-xs font-bold text-red-600" onClick={() => setConfirm(meeting)}>Delete</button>}</MobileCard>)}{meetings.length === 0 && <MobileEmptyState title="No project meetings" description="Meetings created for this project will appear here." />}</div>{canWrite && <MobileFAB extended label="New meeting" icon={CalendarPlus} onClick={() => open(null)} />}<MobileMeetingEditor open={editor !== null} meeting={editor} directory={directory} pending={pending} readOnly={!canWrite} onClose={() => setEditor(null)} onSave={save} /><MobileConfirmModal open={confirm !== null} pending={pending} danger title="Delete meeting" message={`Delete ${confirm?.subject || 'this meeting'}?`} confirmLabel="Delete" onClose={() => setConfirm(null)} onConfirm={remove} /></div>;
}
