import React, { useEffect, useRef, useState } from 'react';
import { ChevronDown, ChevronRight, Users } from 'lucide-react';
import { MobileCard } from '../../../components/MobileCard';
import MobileBottomSheet from '../../../components/MobileBottomSheet';
import MobileEmptyState from '../../../components/MobileEmptyState';
import MobileLoadingState from '../../../components/MobileLoadingState';
import { createGeneralDocumentsRequestGuard, normalizeDirectory } from './mobileGeneralDocumentsModel';

export default function MobileOrganisationChart({ projectId, api }) {
    const [chart, setChart] = useState(null); const [expanded, setExpanded] = useState(null); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const guard = useRef(createGeneralDocumentsRequestGuard());
    useEffect(() => { const token = guard.current.begin(projectId, 'organisation'); setChart(null); setExpanded(null); setSelected(null); setError(''); api.getOrgChart(projectId).then((response) => { if (guard.current.isCurrent(token)) setChart({ ...response, directory: normalizeDirectory(response) }); }).catch((err) => { if (guard.current.isCurrent(token)) setError(err?.response?.status === 403 ? 'Access denied by the current ERP permission policy.' : 'Organisation chart could not be loaded.'); }); }, [api, projectId]);
    if (!chart && !error) return <div className="px-4 pb-28"><MobileLoadingState label="Loading organisation chart" rows={3} /></div>;
    const parties = chart?.parties || []; const directory = chart?.directory || [];
    return <div data-m6-view="organisation" className="space-y-3 px-4 pb-28">{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<MobileCard className="border-blue-200 bg-blue-50 dark:border-blue-900 dark:bg-blue-950/20"><p className="text-[10px] font-bold uppercase text-blue-600">Project organisation</p><h3 className="mt-1 text-base font-bold">{chart?.project_name || 'Project'}</h3><p className="mt-1 text-xs text-gray-600 dark:text-gh-muted">{[chart?.client_name, chart?.project_location].filter(Boolean).join(' · ') || 'No client or location returned.'}</p></MobileCard><div className="space-y-3">{parties.map((party) => { const id = party.id || party.pv_id || party.party_id; const children = directory.filter((contact) => String(contact.partyId) === String(id)); const open = expanded === id; return <MobileCard key={id}><button type="button" onClick={() => setExpanded(open ? null : id)} className="flex min-h-11 w-full items-center justify-between text-left"><span><span className="block text-sm font-bold">{party.name || 'Unnamed party'}</span><span className="text-xs text-gray-500">{party.category || 'Project party'} · {children.length} contacts</span></span>{open ? <ChevronDown size={18} /> : <ChevronRight size={18} />}</button>{open && <div className="mt-3 space-y-2 border-t pt-3 dark:border-gh-border">{children.map((contact) => <button key={contact.id} type="button" onClick={() => setSelected(contact)} className="block min-h-11 w-full rounded-xl bg-gray-50 p-3 text-left text-xs dark:bg-gh-input"><span className="block font-bold text-sm">{contact.contactPerson || contact.companyName || 'Directory contact'}</span><span className="text-gray-500">{[contact.designation, contact.email].filter(Boolean).join(' · ') || 'No contact details'}</span></button>)}{children.length === 0 && <p className="text-xs text-gray-500">No directory contacts linked to this party.</p>}</div>}</MobileCard>; })}{parties.length === 0 && !error && <MobileEmptyState icon={Users} title="No organisation entries" description="The current ERP returned no parties for this project." />}</div><MobileBottomSheet open={selected !== null} onClose={() => setSelected(null)} title={selected?.contactPerson || selected?.companyName || 'Directory contact'}><dl className="space-y-3 text-sm"><div><dt className="text-xs text-gray-500">Company</dt><dd>{selected?.companyName || '—'}</dd></div><div><dt className="text-xs text-gray-500">Designation</dt><dd>{selected?.designation || '—'}</dd></div><div><dt className="text-xs text-gray-500">Email</dt><dd>{selected?.email || '—'}</dd></div><div><dt className="text-xs text-gray-500">Mobile</dt><dd>{selected?.mobileNo || '—'}</dd></div></dl></MobileBottomSheet></div>;
}
