import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ThemeProvider } from 'next-themes';
import '../../src/index.css';
import { AuthProvider } from '../../src/context/AuthContext';
import MobileMainLayout from '../../src/mobile/layout/MobileMainLayout';
import MobilePilotLayout from '../../src/mobile/routing/MobilePilotLayout';
import ResponsiveRoute from '../../src/mobile/routing/ResponsiveRoute';
import MobileProjectShell from '../../src/mobile/pages/ProjectDetails/MobileProjectShell';

const params = new URLSearchParams(window.location.search);
const frame = params.get('frame') === '1'; const declaredWidth = Number(params.get('width') || 390); const access = params.get('access') || 'write'; const exercise = params.get('exercise') || ''; const caseId = params.get('case') || `${declaredWidth}-${exercise}`; const initialView = params.get('view') || 'hub'; const projectParam = params.get('project') || '42';
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); const clone = (value) => JSON.parse(JSON.stringify(value));
const realNetwork = []; window.fetch = (input) => { realNetwork.push(`fetch ${String(input)}`); return Promise.reject(new Error('M6 harness blocks network')); }; XMLHttpRequest.prototype.open = function blocked(method, url) { realNetwork.push(`${method} ${url}`); throw new Error('M6 harness blocks network'); };
const deferred = {}; const defer = (key) => { let resolve; const promise = new Promise((done) => { resolve = done; }); deferred[key] = { promise, resolve }; return deferred[key]; };
const counts = { projects: [], reads: [], mutations: [], agent: 0, loads: 0 };
const partyFor = (id) => ({ id: Number(id) * 10 + 1, pv_id: Number(id) * 10 + 1, name: `Party ${id}`, category: 'Consultant', contact_person: `Contact ${id}`, email: `party${id}@fixture.test` });
const directoryFor = (id) => ({ pd_id: Number(id) * 100 + 7, party_id: Number(id) * 10 + 1, company_name: `Party ${id}`, contact_person: `Directory ${id}`, designation: 'Lead', responsibilities: 'Review', mobile_no: '9999999999', email: `directory${id}@fixture.test`, address_line: 'Fixture Lane' });
const meetingFor = (id) => ({ id: Number(id) * 1000 + 1, meeting_no: Number(id), subject: `Meeting ${id}`, date: '2026-01-02', time: '10:00', venue: 'Fixture room', participants: [{ pd_id: Number(id) * 100 + 7, attended: false }], content: { attendance: { [Number(id) * 100 + 7]: 'absent' } }, agenda_points: [{ sl_no: 1, point: 'Review' }], mom_points: [{ sl_no: 1, point: 'Approved' }] });
const projectFor = (id) => ({ id: Number(id), name: `Synthetic Project ${id}`, project_code: `SYN-${id}`, status: 'active', location: 'Fixture City', metadata: {} });
const readResponse = async (kind, id, value) => { counts.reads.push([kind, Number(id)]); if (exercise === 'loading') await wait(300); if (exercise === 'generic-error') throw new Error('Synthetic read failure'); if (exercise === 'docs-403') throw { response: { status: 403 } }; if (exercise === 'party-race' && String(id) === '42' && kind === 'parties') { const gate = deferred.partyA || defer('partyA'); return gate.promise; } if (exercise === 'meeting-race' && String(id) === '42' && (kind === 'meetings' || kind === 'meeting-detail')) { const gate = deferred.meetingA || defer('meetingA'); return gate.promise; } return exercise === 'empty' ? (kind === 'parties' ? { parties: [], count: 0 } : kind === 'directory' ? { directory: [], count: 0 } : kind === 'summaries' ? { summaries: [] } : kind === 'meetings' ? { meetings: [], count: 0 } : value) : value; };
const docsService = {
    getParties: (id) => readResponse('parties', id, { parties: [partyFor(id)], count: 1 }),
    getAvailableParties: (id) => readResponse('available-parties', id, { available_parties: [{ id: 900 + Number(id), name: `Candidate ${id}`, category: 'Vendor' }] }),
    addParties: async (id, partyIds) => { counts.mutations.push(['addParties', Number(id), clone(partyIds)]); if (exercise === 'mutation-race' && String(id) === '42') return (deferred.mutationA || defer('mutationA')).promise; return { success: true }; },
    deleteParty: async (id, ppId) => { counts.mutations.push(['deleteParty', Number(id), ppId]); return { success: true }; },
    getDirectory: (id) => readResponse('directory', id, { directory: [directoryFor(id)], count: 1 }),
    addDirectoryItem: async (id, payload) => { counts.mutations.push(['addDirectoryItem', Number(id), clone(payload)]); return { success: true }; },
    updateDirectoryItem: async (id, pdId, payload) => { counts.mutations.push(['updateDirectoryItem', Number(id), pdId, clone(payload)]); return { success: true }; },
    deleteDirectoryItem: async (id, pdId) => { counts.mutations.push(['deleteDirectoryItem', Number(id), pdId]); return { success: true }; },
    getSummaries: (id) => readResponse('summaries', id, { summaries: [{ id: Number(id) * 100 + 3, title: `Summary ${id}`, date: '2026-01-01', status: 'open', details: 'Fixture milestone' }] }),
    addSummaries: async (id, payload) => { counts.mutations.push(['addSummaries', Number(id), clone(payload)]); return { success: true }; },
    updateSummaries: async (id, payload) => { counts.mutations.push(['updateSummaries', Number(id), clone(payload)]); return { success: true }; },
    deleteSummaries: async (id, ids) => { counts.mutations.push(['deleteSummaries', Number(id), clone(ids)]); return { success: true }; },
    getMeetings: (id) => readResponse('meetings', id, { meetings: [{ ...meetingFor(id), participants_count: 1, agenda_count: 1, mom_count: 1 }] }),
    getMeeting: (id, meetingId) => readResponse('meeting-detail', id, { meeting: { ...meetingFor(id), id: meetingId } }),
    createMeeting: async (id, payload) => { counts.mutations.push(['createMeeting', Number(id), clone(payload)]); return { success: true }; },
    updateMeeting: async (id, meetingId, payload) => { counts.mutations.push(['updateMeeting', Number(id), meetingId, clone(payload)]); return { success: true }; },
    deleteMeeting: async (id, meetingId) => { counts.mutations.push(['deleteMeeting', Number(id), meetingId]); return { success: true }; },
    getOrgChart: (id) => readResponse('organisation', id, { project_name: `Synthetic Project ${id}`, client_name: 'Synthetic Client', parties: [partyFor(id)], directory: [directoryFor(id)] }),
};
const projectService = { getProject: async (id) => { counts.projects.push(Number(id)); return { success: true, project: projectFor(id), projectPermissions: Object.fromEntries(['General Documents'].map((key) => [key, access === 'read' ? 1 : 2])) }; }, getProjectMembers: async () => ({ members: [] }) };
const authOverride = { user: { id: 7, user_id: 7, user_type: access === 'admin' ? 'admin' : 'employee' }, isAdmin: access === 'admin' };
function DesktopLayout() { return <div data-layout-branch="desktop"><div data-agent-contract="desktop" /><Outlet /></div>; }
function DesktopProjectDetails() { return <div data-desktop-page="project-details">Existing desktop ProjectDetails sentinel</div>; }
function LocationProbe() { const location = useLocation(); return <span hidden data-route={location.pathname} data-search={location.search} />; }
function SwitchDriver() { const navigate = useNavigate(); const scheduled = useRef(false); useEffect(() => { if (scheduled.current || !['party-race', 'meeting-race', 'mutation-race', 'state-switch'].includes(exercise)) return undefined; scheduled.current = true; const switchDelay = exercise === 'mutation-race' ? 620 : 70; const timer = setTimeout(() => navigate(`/projects/43?tab=General%20Documents&view=${initialView}&foo=preserved`), switchDelay); if (exercise === 'party-race') setTimeout(() => deferred.partyA?.resolve({ parties: [partyFor(42)], count: 1 }), 180); if (exercise === 'meeting-race') setTimeout(() => deferred.meetingA?.resolve({ meetings: [{ ...meetingFor(42), participants_count: 1, agenda_count: 1 }] }), 180); if (exercise === 'mutation-race') setTimeout(() => deferred.mutationA?.resolve({ success: true }), 1100); return () => clearTimeout(timer); }, [navigate]); return null; }
function ClickButton(text, root = document) { return [...root.querySelectorAll('button')].find((button) => button.textContent.trim().includes(text)); }
function ClickLast(text, root = document) { return [...root.querySelectorAll('button')].reverse().find((button) => button.textContent.trim() === text || button.textContent.trim().includes(text)); }
function setValue(input, value) { if (!input) return; const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set || Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')?.set; setter?.call(input, value); input.dispatchEvent(new Event('input', { bubbles: true })); input.dispatchEvent(new Event('change', { bubbles: true })); }
function FrameChecks() {
    const location = useLocation(); const navigate = useNavigate(); const [rows, setRows] = useState([]); const reported = useRef(false);
    useEffect(() => { let stopped = false; const check = (label, pass, detail = '') => ({ label, pass: Boolean(pass), detail }); const run = async () => {
        await wait(exercise === 'loading' ? 80 : 420); if (stopped) return; const result = []; const mobile = window.innerWidth <= 1023; const search = document.querySelector('[data-search]')?.getAttribute('data-search') || '';
        result.push(check('Exact viewport', window.innerWidth === declaredWidth, `${window.innerWidth}/${declaredWidth}`)); result.push(check('Exactly one presentation branch', document.querySelectorAll('[data-layout-branch]').length === 1)); result.push(check('Correct responsive branch', mobile ? Boolean(document.querySelector('[data-layout-branch="mobile"]')) : Boolean(document.querySelector('[data-layout-branch="desktop"]'))));
        if (!mobile) { result.push(check('Desktop ProjectDetails sentinel only', Boolean(document.querySelector('[data-desktop-page="project-details"]')) && !document.querySelector('[data-mobile-page="project-shell"]'))); result.push(check('No mobile Agent at desktop boundary', !document.querySelector('[data-agent-contract="mobile"]'))); }
        else { result.push(check('Mobile layout mounts once', document.querySelectorAll('[data-layout-branch="mobile"]').length === 1)); result.push(check('Mobile project shell mounts once', document.querySelectorAll('[data-mobile-page="project-shell"]').length === 1)); result.push(check('General Documents outlet mounts once', document.querySelectorAll('[data-m6-module="General Documents"]').length === 1)); result.push(check('Mobile Agent mounts once', document.querySelectorAll('[data-agent-contract="mobile"]').length === 1)); result.push(check('Desktop sentinel absent', !document.querySelector('[data-desktop-page]'))); result.push(check('No horizontal overflow', document.documentElement.scrollWidth <= window.innerWidth, `${document.documentElement.scrollWidth}/${window.innerWidth}`)); result.push(check('No real ERP or Agent network', realNetwork.length === 0, realNetwork.join(', ')));
            if (!['party-race', 'meeting-race', 'mutation-race', 'state-switch', 'loading', 'generic-error', 'docs-403'].includes(exercise)) { result.push(check('Requested child view mounts once', document.querySelectorAll(`[data-m6-view="${initialView}"]`).length === 1)); result.push(check('General Documents tab and unrelated query persist', search.includes('tab=General+Documents') && search.includes('foo=preserved'), search)); }
            if (exercise === 'history') { ClickButton('Project Parties')?.click(); await wait(100); const childSearch = document.querySelector('[data-search]')?.getAttribute('data-search') || ''; result.push(check('Hub navigation preserves unrelated query', childSearch.includes('view=parties') && childSearch.includes('foo=preserved'), childSearch)); navigate(-1); await wait(100); const backSearch = document.querySelector('[data-search]')?.getAttribute('data-search') || ''; result.push(check('Back returns child view to hub', !backSearch.includes('view=') && backSearch.includes('foo=preserved'), backSearch)); navigate(1); await wait(100); result.push(check('Forward restores child view', (document.querySelector('[data-search]')?.getAttribute('data-search') || '').includes('view=parties'))); }
            if (exercise === 'party-workflow') { ClickButton('Link contacts')?.click(); await wait(80); document.querySelector('input[type="checkbox"]')?.click(); ClickButton('Link selected')?.click(); await wait(100); const link = counts.mutations.find((item) => item[0] === 'addParties'); result.push(check('Party link uses project-scoped args', link?.[1] === 42 && Array.isArray(link?.[2]) && link[2].length === 1, JSON.stringify(link))); ClickButton('Party 42', document.querySelector('[data-m6-view="parties"]'))?.click(); await wait(80); ClickButton('Remove from project', document.querySelector('[role="dialog"]'))?.click(); await wait(60); ClickLast('Remove', document.querySelectorAll('[role="dialog"]')[1] || document)?.click(); await wait(100); const remove = counts.mutations.find((item) => item[0] === 'deleteParty'); result.push(check('Party remove uses existing scalar contract', remove?.[1] === 42 && remove?.[2] != null, JSON.stringify(remove))); }
            if (exercise === 'directory-workflow') { ClickButton('Add contact')?.click(); await wait(60); setValue(document.querySelector('input[name="contactPerson"]'), 'Created directory contact'); ClickButton('Save', document.querySelector('[role="dialog"]'))?.click(); await wait(100); const add = counts.mutations.find((item) => item[0] === 'addDirectoryItem'); result.push(check('Directory create payload is project scoped', add?.[1] === 42 && add?.[2]?.contact_person === 'Created directory contact', JSON.stringify(add))); ClickButton('Delete', document.querySelector('[data-m6-view="directory"]'))?.click(); await wait(60); ClickLast('Delete', document.querySelectorAll('[role="dialog"]')[0] || document)?.click(); await wait(100); result.push(check('Directory delete uses pd_id', counts.mutations.some((item) => item[0] === 'deleteDirectoryItem' && item[1] === 42), JSON.stringify(counts.mutations))); }
            if (exercise === 'summary-workflow') { ClickButton('Add milestone')?.click(); await wait(50); setValue(document.querySelector('input[name="title"]'), 'Created summary'); ClickButton('Save', document.querySelector('[role="dialog"]'))?.click(); await wait(100); const add = counts.mutations.find((item) => item[0] === 'addSummaries'); result.push(check('Summary create uses existing array contract', add?.[1] === 42 && Array.isArray(add?.[2]) && add[2][0]?.title === 'Created summary', JSON.stringify(add))); ClickButton('Delete', document.querySelector('[data-m6-view="summary"]'))?.click(); await wait(60); ClickLast('Delete', document.querySelectorAll('[role="dialog"]')[0] || document)?.click(); await wait(100); result.push(check('Summary delete uses ID array', counts.mutations.some((item) => item[0] === 'deleteSummaries' && Array.isArray(item[2])), JSON.stringify(counts.mutations))); }
            if (exercise === 'meeting-workflow') { ClickButton('Meeting 42', document.querySelector('[data-m6-view="meetings"]'))?.click(); await wait(100); const dialog = document.querySelector('[role="dialog"]'); const attendance = dialog?.querySelector('select[aria-label^="Attendance"]'); attendance && (attendance.value = 'present', attendance.dispatchEvent(new Event('change', { bubbles: true }))); ClickButton('Save meeting', dialog)?.click(); await wait(120); const update = counts.mutations.find((item) => item[0] === 'updateMeeting'); const payload = update?.[3]; result.push(check('Meeting detail fetch occurred', counts.reads.some((item) => item[0] === 'meeting-detail' && item[1] === 42), JSON.stringify(counts.reads))); result.push(check('Meeting preserves participant membership', Array.isArray(payload?.participants) && payload.participants[0]?.pd_id === 4207, JSON.stringify(payload))); result.push(check('Meeting sends present/absent separately', payload?.content?.attendance?.[4207] === 'present', JSON.stringify(payload?.content))); result.push(check('Meeting preserves agenda and MoM structure', Array.isArray(payload?.agenda_points) && Array.isArray(payload?.mom_points), JSON.stringify(payload))); ClickButton('Delete', document.querySelector('[data-m6-view="meetings"]'))?.click(); await wait(60); ClickLast('Delete', document.querySelectorAll('[role="dialog"]')[0] || document)?.click(); await wait(100); result.push(check('Meeting delete is project scoped', counts.mutations.some((item) => item[0] === 'deleteMeeting' && item[1] === 42), JSON.stringify(counts.mutations))); }
            if (exercise === 'readonly') { if (initialView === 'meetings') document.querySelector('[data-m6-view="meetings"] article button')?.click(); await wait(60); result.push(check('Read-only mutation controls absent', !document.body.textContent.includes('Save meeting') && !document.body.textContent.includes('Add contact') && !document.body.textContent.includes('Add milestone') && !document.body.textContent.includes('Link contacts'))); result.push(check('Read-only sends zero mutations', counts.mutations.length === 0, JSON.stringify(counts.mutations))); }
            if (exercise === 'loading') { result.push(check('Loading starts every permitted hub read', counts.reads.length === 5, JSON.stringify(counts.reads))); result.push(check('Loading state appears before response', document.body.textContent.includes('Loading'))); } if (exercise === 'empty') result.push(check('Empty state is visible', document.body.textContent.includes('No'))); if (exercise === 'generic-error') result.push(check('Generic error state is visible', document.body.textContent.includes('could not be loaded') || document.body.textContent.includes('unavailable'))); if (exercise === 'docs-403') result.push(check('403 access state is visible', document.body.textContent.includes('Access denied')));
            if (exercise === 'party-race') { await wait(260); result.push(check('B starts party request', counts.reads.some((item) => item[0] === 'parties' && item[1] === 43), JSON.stringify(counts.reads))); result.push(check('Late A parties cannot overwrite B', document.body.textContent.includes('Party 43') && !document.body.textContent.includes('Party 42'))); }
            if (exercise === 'meeting-race') { await wait(260); result.push(check('B starts meeting request', counts.reads.some((item) => item[0] === 'meetings' && item[1] === 43), JSON.stringify(counts.reads))); result.push(check('Late A meetings cannot overwrite B', document.body.textContent.includes('Meeting 43') && !document.body.textContent.includes('Meeting 42'))); }
            if (exercise === 'mutation-race') { ClickButton('Link contacts')?.click(); await wait(50); document.querySelector('input[type="checkbox"]')?.click(); ClickButton('Link selected')?.click(); await wait(500); result.push(check('A mutation started before switch', counts.mutations.some((item) => item[0] === 'addParties' && item[1] === 42), JSON.stringify(counts.mutations))); result.push(check('Project switch clears A link sheet', !document.body.textContent.includes('Link CRM contacts'))); const bReadsBeforeACompletion = counts.reads.filter((item) => item[0] === 'parties' && item[1] === 43).length; result.push(check('B starts its own party request before A completion', bReadsBeforeACompletion > 0, JSON.stringify(counts.reads))); result.push(check('B shows no A party before A completion', document.body.textContent.includes('Party 43') && !document.body.textContent.includes('Party 42'))); result.push(check('A link mutation remains pending until resolved', counts.mutations.filter((item) => item[0] === 'addParties' && item[1] === 42).length === 1, JSON.stringify(counts.mutations))); await wait(350); result.push(check('Stale A mutation does not refresh B', counts.reads.filter((item) => item[0] === 'parties' && item[1] === 43).length === bReadsBeforeACompletion && document.body.textContent.includes('Party 43'), JSON.stringify(counts.reads))); result.push(check('Mutation remains scoped to A', counts.mutations.every((item) => item[1] === 42), JSON.stringify(counts.mutations))); }
            if (exercise === 'sheet-smoke') { ClickButton('Meeting 42', document.querySelector('[data-m6-view="meetings"]'))?.click(); await wait(100); const dialog = document.querySelector('[role="dialog"][aria-modal="true"]'); result.push(check('Representative sheet dialog mounts', Boolean(dialog))); result.push(check('Sheet contains focus', document.activeElement?.closest('[role="dialog"]') === dialog)); window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true })); await wait(60); result.push(check('Escape closes representative sheet', !document.querySelector('[role="dialog"][aria-modal="true"]'))); }
        }
        if (!stopped && !reported.current) { reported.current = true; setRows(result); window.__M6_HARNESS_RESULT__ = { caseId, rows: result, counts: clone(counts) }; parent.postMessage({ type: 'mano-m6-results', caseId, rows: result }, location.origin); }
    }; run(); return () => { stopped = true; }; }, []);
    return <ol aria-label="M6 frame checks" className="fixed left-1 top-1 z-[100] max-h-40 overflow-auto bg-white p-2 text-[9px]">{rows.map((row) => <li key={row.label}>{row.pass ? 'PASS' : 'FAIL'} {row.label}</li>)}</ol>;
}
function Frame() { const initial = `/projects/${projectParam}?${new URLSearchParams({ tab: 'General Documents', ...(initialView !== 'hub' ? { view: initialView } : {}), foo: 'preserved' })}`; return <ThemeProvider attribute="class" defaultTheme={params.get('theme') || 'light'} enableSystem={false}><AuthProvider><MemoryRouter initialEntries={[initial]}><LocationProbe /><SwitchDriver /><FrameChecks /><Routes><Route path="/" element={<MobilePilotLayout mobile={<MobileMainLayout loadProjects={async () => { counts.loads += 1; return { projects: [] }; }} />} desktop={<DesktopLayout />} />}><Route path="projects/:id" element={<ResponsiveRoute mobile={<MobileProjectShell authOverride={authOverride} projectService={projectService} moduleServices={{ projects: projectService, docs: docsService }}/>} desktop={<DesktopProjectDetails />} />} /></Route></Routes></MemoryRouter></AuthProvider></ThemeProvider>; }
const cases = [
    { id: 'mobile-360-light', width: 360 }, { id: 'mobile-390-light', width: 390 }, { id: 'mobile-430-dark', width: 430, theme: 'dark' }, { id: 'mobile-768-light', width: 768 }, { id: 'mobile-1023-light', width: 1023 }, { id: 'desktop-1024', width: 1024 },
    ...['hub', 'parties', 'directory', 'summary', 'meetings', 'organisation'].map((view) => ({ id: `view-${view}`, width: 390, view })), { id: 'history', width: 390, exercise: 'history' },
    { id: 'party-workflow', width: 390, view: 'parties', exercise: 'party-workflow' }, { id: 'directory-workflow', width: 390, view: 'directory', exercise: 'directory-workflow' }, { id: 'summary-workflow', width: 390, view: 'summary', exercise: 'summary-workflow' }, { id: 'meeting-workflow', width: 390, view: 'meetings', exercise: 'meeting-workflow' },
    ...['parties', 'directory', 'summary', 'meetings'].map((view) => ({ id: `readonly-${view}`, width: 390, view, access: 'read', exercise: 'readonly' })), { id: 'party-race', width: 390, view: 'parties', exercise: 'party-race' }, { id: 'meeting-race', width: 390, view: 'meetings', exercise: 'meeting-race' }, { id: 'mutation-race', width: 390, view: 'parties', exercise: 'mutation-race' },
    { id: 'loading', width: 390, exercise: 'loading' }, { id: 'empty', width: 390, view: 'parties', exercise: 'empty' }, { id: 'generic-error', width: 390, exercise: 'generic-error' }, { id: 'docs-403', width: 390, exercise: 'docs-403' }, { id: 'sheet-smoke', width: 390, view: 'meetings', exercise: 'sheet-smoke' },
];
function Parent() { const [reports, setReports] = useState({}); const index = Object.keys(reports).length; const item = cases[index]; useEffect(() => { const receive = (event) => { if (event.origin === location.origin && event.data?.type === 'mano-m6-results') setReports((current) => current[event.data.caseId] ? current : { ...current, [event.data.caseId]: event.data.rows }); }; addEventListener('message', receive); return () => removeEventListener('message', receive); }, []); const rows = Object.values(reports).flat(); const pass = rows.filter((row) => row.pass).length; const fail = rows.length - pass; return <main className="min-h-screen bg-gray-100 p-4 text-gray-900"><h1>M6 General Documents integration harness</h1><p data-harness-summary>Completed {index}/{cases.length}; PASS {pass}; FAIL {fail}.</p><ul>{Object.entries(reports).flatMap(([id, result]) => result.filter((row) => !row.pass).map((row) => <li key={`${id}-${row.label}`}>FAIL {id}: {row.label} {row.detail}</li>))}</ul>{item && <iframe key={item.id} title={item.id} width={item.width} height="760" style={{ border: 0, display: 'block' }} src={`./m6-harness.html?${new URLSearchParams({ frame: '1', case: item.id, width: String(item.width), project: item.project || '42', view: item.view || 'hub', access: item.access || 'write', ...(item.exercise ? { exercise: item.exercise } : {}), ...(item.theme ? { theme: item.theme } : {}) })}`} />}</main>; }
createRoot(document.getElementById('root')).render(frame ? <Frame /> : <Parent />);
