import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ThemeProvider } from 'next-themes';
import '../../src/index.css';
import { AuthProvider } from '../../src/context/AuthContext';
import MobileMainLayout from '../../src/mobile/layout/MobileMainLayout';
import MobilePilotLayout from '../../src/mobile/routing/MobilePilotLayout';
import ResponsiveRoute from '../../src/mobile/routing/ResponsiveRoute';
import MobileProjectShell from '../../src/mobile/pages/ProjectDetails/MobileProjectShell';

const params = new URLSearchParams(location.search); const frame = params.get('frame') === '1'; const width = Number(params.get('width') || 390); const tab = params.get('tab') || 'Quality'; const access = params.get('access') || 'write'; const exercise = params.get('exercise') || 'render'; const caseId = params.get('case') || `${width}-${tab}-${exercise}`;
const network = []; const opens = []; const calls = { project: [], quality: [], resource: [], mutations: 0 };
const deferred = () => { let resolve; let reject; const promise = new Promise((nextResolve, nextReject) => { resolve = nextResolve; reject = nextReject; }); return { promise, resolve, reject }; };
const race = { qualityReadA: exercise === 'quality-read-race' ? deferred() : null, qualityMutationA: exercise === 'quality-mutation-race' ? deferred() : null, materialReadA: exercise === 'material-read-race' ? deferred() : null, materialMutationA: exercise === 'material-mutation-race' ? deferred() : null };
window.fetch = (input) => { network.push(String(input)); return Promise.reject(new Error('M7 harness blocks application network')); };
XMLHttpRequest.prototype.open = function blocked(method, url) { network.push(`${method}:${url}`); throw new Error('M7 harness blocks application network'); };
window.open = (url) => { opens.push(url); return null; };
HTMLAnchorElement.prototype.click = function observedDownload() { calls.resource.push(['anchorClick', this.href, this.download]); };
const pause = (ms = 20) => new Promise((resolve) => setTimeout(resolve, ms));
const waitFor = async (predicate, label) => { for (let attempt = 0; attempt < 300; attempt += 1) { if (predicate()) return; await pause(); } throw new Error(`Timed out: ${label}`); };
const button = (text, root = document) => [...root.querySelectorAll('button')].find((item) => item.textContent.trim() === text || item.textContent.includes(text));
const click = async (text, root = document) => { await waitFor(() => button(text, root), `button ${text}`); const target = button(text, root); target.click(); await pause(); return target; };
const clickLast = async (text) => { await waitFor(() => [...document.querySelectorAll('button')].filter((item) => item.textContent.includes(text)).length > 0, `last button ${text}`); const target = [...document.querySelectorAll('button')].filter((item) => item.textContent.includes(text)).at(-1); target.click(); await pause(); return target; };
const inputValue = (element, value) => { const prototype = element instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; const setter = Object.getOwnPropertyDescriptor(prototype, 'value')?.set; setter.call(element, value); element.dispatchEvent(new Event('input', { bubbles: true })); element.dispatchEvent(new Event('change', { bubbles: true })); };
const permissions = Object.fromEntries(['Quality', 'Safety', 'Material Management'].map((key) => [key, access === 'read' ? 1 : 2]));
const projectRows = (id) => [{ id: Number(id) === 43 ? 731 : 701, resource_id: Number(id) === 43 ? 731 : 701, name: Number(id) === 43 ? 'B Project Item' : 'A Project Item', code: 'ITEM', type: 'item', base_unit_code: 'kg' }, { id: Number(id) === 43 ? 732 : 702, resource_id: Number(id) === 43 ? 732 : 702, name: Number(id) === 43 ? 'B Project Sand' : 'A Project Sand', code: 'SAND', type: 'material', base_unit_code: 'kg' }];
const projectService = {
    getProject: async (id) => { calls.project.push(['getProject', id]); return { success: true, project: { id: Number(id), name: Number(id) === 43 ? 'M7 Project B' : 'M7 Project A', project_code: `M7-${id}`, status: 'active' }, projectPermissions: permissions }; },
    listProjectResources: async (id) => { calls.project.push(['listProjectResources', id]); if (race.materialReadA && Number(id) === 42) return race.materialReadA.promise; return { resources: projectRows(id) }; },
    getResolvedResourceRates: async (id, ids) => { calls.project.push(['getResolvedResourceRates', id, ids]); return { rates: ids.map((resource_id) => ({ resource_id, rate: 100 })) }; },
    importResource: async (...args) => { calls.mutations += 1; calls.project.push(['importResource', ...args]); if (race.materialMutationA && Number(args[0]) === 42) return race.materialMutationA.promise; return { success: true }; },
    importResourcesBatch: async (...args) => { calls.mutations += 1; calls.project.push(['importResourcesBatch', ...args]); return { success: true }; },
    removeProjectResource: async (...args) => { calls.mutations += 1; calls.project.push(['removeProjectResource', ...args]); return { success: true }; },
    getProjectCompositionHistory: async (...args) => { calls.project.push(['getProjectCompositionHistory', ...args]); return { compositions: [] }; },
    setProjectCompositions: async (...args) => { calls.mutations += 1; calls.project.push(['setProjectCompositions', ...args]); return { success: true }; },
    getResolvedResourceRate: async (...args) => { calls.project.push(['getResolvedResourceRate', ...args]); return { rate: 100, unit_code: 'kg' }; },
    getResourceRateHistory: async (...args) => { calls.project.push(['getResourceRateHistory', ...args]); return { rates: [{ id: 8, mode: 'manual', rate: 98, unit_code: 'kg', effective_from: '2026-01-01', remarks: 'Synthetic' }] }; },
    addResourceRate: async (...args) => { calls.mutations += 1; calls.project.push(['addResourceRate', ...args]); return { success: true }; },
    updateResourceRate: async (...args) => { calls.mutations += 1; calls.project.push(['updateResourceRate', ...args]); return { success: true }; },
    clearResourceRate: async (...args) => { calls.mutations += 1; calls.project.push(['clearResourceRate', ...args]); return { success: true }; },
};
const quality = {
    getObservations: async (id) => { calls.quality.push(['getObservations', id]); if (exercise === 'quality-403') { const error = new Error('forbidden'); error.status = 403; throw error; } if (race.qualityReadA && Number(id) === 42) return race.qualityReadA.promise; return { observations: [{ id: Number(id), location: Number(id) === 43 ? 'B level' : 'A level', before_note: 'Synthetic defect', before_photos: ['https://example.test/before.jpg'], status: ['quality-approve', 'quality-failure'].includes(exercise) ? 'FIXED' : 'PENDING' }] }; },
    createObservation: async (projectId, form) => { calls.mutations += 1; calls.quality.push(['createObservation', projectId, form]); if (race.qualityMutationA && Number(projectId) === 42) return race.qualityMutationA.promise; return { success: true }; }, updateObservation: async (projectId, id, form) => { calls.mutations += 1; calls.quality.push(['updateObservation', projectId, id, form]); return { success: true }; }, submitFix: async (...args) => { calls.mutations += 1; calls.quality.push(['submitFix', ...args]); return { success: true }; }, approveFix: async (...args) => { calls.mutations += 1; calls.quality.push(['approveFix', ...args]); if (exercise === 'quality-failure') throw new Error('Synthetic approval failure'); return { success: true }; }, deleteObservation: async (...args) => { calls.mutations += 1; calls.quality.push(['deleteObservation', ...args]); return { success: true }; },
    getMethodologies: async (...args) => { calls.quality.push(['getMethodologies', ...args]); return { methodologies: [{ id: 12, title: 'Method statement', uploaded_by_name: 'QA', file_name: 'method.pdf', file_type: 'PDF', file_url: 'https://example.test/method.pdf' }, { id: 14, title: 'Hidden method', file_name: 'hidden.pdf', file_type: 'PDF', file_url: 'https://example.test/hidden.pdf' }] }; }, uploadMethodology: async (...args) => { calls.mutations += 1; calls.quality.push(['uploadMethodology', ...args]); return { success: true }; }, deleteMethodology: async (...args) => { calls.mutations += 1; calls.quality.push(['deleteMethodology', ...args]); return { success: true }; },
    getChecklists: async (...args) => { calls.quality.push(['getChecklists', ...args]); return { checklists: [{ id: 13, title: 'Inspection checklist', uploaded_by_name: 'QA', file_name: 'check.docx', file_type: 'DOCX', file_url: 'https://example.test/check.docx' }, { id: 15, title: 'Hidden checklist', file_name: 'hidden.docx', file_type: 'DOCX', file_url: 'https://example.test/hidden.docx' }] }; }, uploadChecklist: async (...args) => { calls.mutations += 1; calls.quality.push(['uploadChecklist', ...args]); return { success: true }; }, deleteChecklist: async (...args) => { calls.mutations += 1; calls.quality.push(['deleteChecklist', ...args]); return { success: true }; },
};
const resources = {
    getResources: async () => ({ resources: [{ id: 800, name: 'Master cement', code: 'CEM', type: 'material', base_unit_code: 'kg' }, { id: 801, name: 'Master labour', code: 'LAB', type: 'labour', base_unit_code: 'hr' }] }),
    getResourceById: async (...args) => { calls.resource.push(['getResourceById', ...args]); return { resource: { id: args[0], conversions: [] } }; },
    createResource: async (...args) => { calls.mutations += 1; calls.resource.push(['createResource', ...args]); return { resource: { id: 901 } }; }, updateResource: async (...args) => { calls.mutations += 1; calls.resource.push(['updateResource', ...args]); return { success: true }; }, addConversion: async (...args) => { calls.mutations += 1; calls.resource.push(['addConversion', ...args]); return { success: true }; }, removeConversion: async (...args) => { calls.mutations += 1; calls.resource.push(['removeConversion', ...args]); return { success: true }; },
};
const authOverride = { isAdmin: access === 'admin', user: { id: 7, user_id: 7, user_type: access === 'admin' ? 'admin' : 'employee' } };
function DesktopLayout() { return <div data-layout-branch="desktop"><Outlet /></div>; }
function Desktop() { return <div data-desktop-sentinel>Existing desktop ProjectDetails</div>; }
function Probe() { const loc = useLocation(); const navigate = useNavigate(); window.__m7Navigate = navigate; return <span hidden data-query={loc.search} data-path={loc.pathname} />; }
async function runDocumentWorkflow(check, kind) { const checklist = kind === 'checklist'; const title = checklist ? 'Inspection checklist' : 'Method statement'; const url = checklist ? 'https://example.test/check.docx' : 'https://example.test/method.pdf'; const uploadName = checklist ? 'uploadChecklist' : 'uploadMethodology'; const deleteName = checklist ? 'deleteChecklist' : 'deleteMethodology'; const root = document.querySelector(`[data-m7-quality-documents="${kind}"]`); const search = root.querySelector('input[type="search"], input'); inputValue(search, checklist ? 'Inspection' : 'Method'); await pause(); check(`${kind} search filters unrelated document`, root.textContent.includes(title) && !root.textContent.includes('Hidden')); await click('Preview', root); check(`${kind} preview uses file_url`, opens.some((value) => value === url || value.includes(encodeURIComponent(url)))); await click('Download', root); check(`${kind} download uses file_url`, calls.resource.some((row) => row[0] === 'anchorClick' && row[1] === url)); await click('Upload document', root); const sheet = document.querySelector('[role="dialog"]') || document; const fields = sheet.querySelectorAll('input'); inputValue([...fields].find((field) => field.type !== 'file'), `${title} upload`); const fileInput = [...fields].find((field) => field.type === 'file'); const file = new File(['m7'], checklist ? 'check.pdf' : 'method.pdf', { type: 'application/pdf' }); Object.defineProperty(fileInput, 'files', { configurable: true, value: [file] }); fileInput.dispatchEvent(new Event('change', { bubbles: true })); await clickLast('Upload document'); await waitFor(() => calls.quality.some((row) => row[0] === uploadName), `${kind} upload`); const upload = calls.quality.find((row) => row[0] === uploadName); check(`${kind} upload preserves project and FormData`, String(upload[1]) === '42' && upload[2].get('title') === `${title} upload` && upload[2].get('file')?.name === file.name); await click('Delete', root); await clickLast('Delete document'); await waitFor(() => calls.quality.some((row) => row[0] === deleteName), `${kind} delete`); const remove = calls.quality.find((row) => row[0] === deleteName); check(`${kind} delete preserves project and document ID`, String(remove[1]) === '42' && String(remove[2]) === String(checklist ? 13 : 12)); }

async function runExercise(check) {
    if (exercise === 'quality-create') {
        await click('New observation'); const editor = document.querySelector('[data-m7-observation-editor]'); const [location] = editor.querySelectorAll('input'); inputValue(location, 'Level 8'); inputValue(editor.querySelector('textarea'), 'Created in harness'); await click('Create observation'); await waitFor(() => calls.quality.some((row) => row[0] === 'createObservation'), 'quality create'); check('Quality create uses current project multipart', String(calls.quality.find((row) => row[0] === 'createObservation')[1]) === '42');
    }
    if (exercise === 'quality-edit') {
        await click('A level'); await click('Edit observation'); await waitFor(() => document.querySelector('[data-m7-observation-editor]'), 'quality editor'); const editor = document.querySelector('[data-m7-observation-editor]'); inputValue(editor.querySelector('textarea'), 'Text only edit'); await click('Save observation'); await waitFor(() => calls.quality.some((row) => row[0] === 'updateObservation'), 'quality update'); check('Quality edit keeps existing photo unless explicitly cleared', String(calls.quality.find((row) => row[0] === 'updateObservation')[1]) === '42');
    }
    if (exercise === 'quality-clear') {
        await click('A level'); await click('Edit observation'); await waitFor(() => document.querySelector('[data-m7-observation-editor] input[type="checkbox"]'), 'quality clear editor'); const checkbox = document.querySelector('[data-m7-observation-editor] input[type="checkbox"]'); checkbox.click(); await click('Save observation'); await waitFor(() => calls.quality.some((row) => row[0] === 'updateObservation'), 'quality clear'); const payload = calls.quality.find((row) => row[0] === 'updateObservation')[3]; check('Quality explicit photo clear sends clearPhotos', payload.get('clearPhotos') === 'true');
    }
    if (exercise === 'quality-approve') { await click('A level'); await click('Approve fix'); await waitFor(() => calls.quality.some((row) => row[0] === 'approveFix'), 'quality approve'); check('Quality approval closes stale detail', !document.body.textContent.includes('Status: FIXED')); }
    if (exercise === 'quality-docs') { await click('Preview'); check('Quality documents use actual preview URL', opens.includes('https://example.test/method.pdf')); check('Read actions do not mutate', calls.mutations === 0); }
    if (exercise === 'quality-matrix') { check('Quality matrix contains full local sample', document.body.textContent.includes('R/F Steel') && document.body.textContent.includes('Kota / Jaisalmer')); await click('Ordinary Portland Cement'); await click('Edit local matrix row'); check('Matrix editor is local only', calls.mutations === 0 && network.length === 0); }
    if (exercise === 'material-batch') { await click('Import multiple'); await waitFor(() => document.querySelector('input[type="checkbox"]'), 'batch checkbox'); document.querySelector('input[type="checkbox"]').click(); await click('Import 1 selected'); await waitFor(() => calls.project.some((row) => row[0] === 'importResourcesBatch'), 'batch import'); const args = calls.project.find((row) => row[0] === 'importResourcesBatch'); check('Material batch uses existing batch contract', String(args[1]) === '42' && args[2] && args[2].length === 1); }
    if (exercise === 'material-rates') { await waitFor(() => document.querySelector('[data-m7-material-rates] input[type="number"]'), 'rate input'); inputValue(document.querySelector('[data-m7-material-rates] input[type="number"]'), '120'); await click('Save rate version'); await waitFor(() => calls.project.some((row) => row[0] === 'addResourceRate'), 'rate add'); check('Project rate payload keeps existing fields', Object.hasOwn(calls.project.find((row) => row[0] === 'addResourceRate')[3], 'effective_to')); }
    if (exercise === 'material-conversions') { await waitFor(() => document.querySelectorAll('[data-m7-material-conversions] input').length >= 2, 'conversion inputs'); const inputs = document.querySelectorAll('[data-m7-material-conversions] input'); inputValue(inputs[0], 'Bag'); inputValue(inputs[1], '50'); await click('Add conversion'); await waitFor(() => calls.resource.some((row) => row[0] === 'addConversion'), 'conversion add'); check('Conversion uses selected resource and compatible unit', String(calls.resource.find((row) => row[0] === 'addConversion')[1]) === '701'); }
    if (exercise === 'quality-read-race') { await waitFor(() => calls.quality.some((row) => row[0] === 'getObservations' && String(row[1]) === '42'), 'quality A read'); window.__m7Navigate('/projects/43?tab=Quality&view=control&foo=preserved'); await waitFor(() => document.body.textContent.includes('B level'), 'quality B read'); check('Quality B is visible before A resolves', document.body.textContent.includes('B level') && !document.body.textContent.includes('A level')); race.qualityReadA.resolve({ observations: [{ id: 42, location: 'A level', before_note: 'late A', status: 'PENDING' }] }); await pause(); check('Late Quality A cannot overwrite B', document.body.textContent.includes('B level') && !document.body.textContent.includes('late A')); check('Quality race stays on project B', document.querySelector('[data-path]')?.dataset.path === '/projects/43'); }
    if (exercise === 'quality-mutation-race') { await click('New observation'); const editor = document.querySelector('[data-m7-observation-editor]'); inputValue(editor.querySelector('input'), 'A mutation'); inputValue(editor.querySelector('textarea'), 'held'); await click('Create observation'); await waitFor(() => calls.quality.some((row) => row[0] === 'createObservation'), 'quality A mutation'); const args = calls.quality.find((row) => row[0] === 'createObservation'); window.__m7Navigate('/projects/43?tab=Quality&view=control&foo=preserved'); await waitFor(() => document.body.textContent.includes('B level'), 'quality mutation B'); race.qualityMutationA.resolve({ success: true }); await pause(); check('Quality mutation keeps A project ID', String(args[1]) === '42'); check('Quality A completion leaves B intact', document.body.textContent.includes('B level') && !document.querySelector('[data-m7-observation-editor]')); }
    if (exercise === 'material-read-race') { await waitFor(() => calls.project.some((row) => row[0] === 'listProjectResources' && String(row[1]) === '42'), 'material A read'); window.__m7Navigate('/projects/43?tab=Material%20Management&matTab=grid&resourceId=731&foo=preserved'); await waitFor(() => document.body.textContent.includes('B Project Item'), 'material B read'); race.materialReadA.resolve({ resources: projectRows(42) }); await pause(); check('Late Material A cannot overwrite B', document.body.textContent.includes('B Project Item') && !document.body.textContent.includes('A Project Item')); check('Material race stays on B resource', document.querySelector('[data-path]')?.dataset.path === '/projects/43'); }
    if (exercise === 'material-mutation-race') { await click('Master cement'); await click('Import to project'); await waitFor(() => calls.project.some((row) => row[0] === 'importResource'), 'material A mutation'); const args = calls.project.find((row) => row[0] === 'importResource'); window.__m7Navigate('/projects/43?tab=Material%20Management&matTab=grid&resourceId=731&foo=preserved'); await waitFor(() => document.body.textContent.includes('B Project Item'), 'material mutation B'); const bReads = calls.project.filter((row) => row[0] === 'listProjectResources' && String(row[1]) === '43').length; race.materialMutationA.resolve({ success: true }); await pause(); check('Material mutation keeps A project ID', String(args[1]) === '42'); check('Material A completion does not reload B', calls.project.filter((row) => row[0] === 'listProjectResources' && String(row[1]) === '43').length === bReads); check('Material A sheet is absent in B', !button('Import to project') && document.body.textContent.includes('B Project Item')); }
    if (exercise === 'quality-history') { check('Quality starts at hub with preserved query', document.querySelector('[data-query]')?.dataset.query.includes('tab=Quality') && document.querySelector('[data-query]')?.dataset.query.includes('foo=preserved')); await click('QA/QC Control'); await waitFor(() => document.querySelector('[data-m7-quality-control]'), 'quality control'); check('Quality control uses a singular outlet', document.querySelectorAll('[data-m7-module="Quality"]').length === 1 && document.querySelector('[data-query]')?.dataset.query.includes('view=control')); window.__m7Navigate(-1); await waitFor(() => !document.querySelector('[data-m7-quality-control]'), 'quality history back'); check('Quality Back restores hub', document.body.textContent.includes('QA/QC Control') && document.querySelector('[data-query]')?.dataset.query.includes('foo=preserved')); window.__m7Navigate(1); await waitFor(() => document.querySelector('[data-m7-quality-control]'), 'quality history forward'); check('Quality Forward restores control without transient state', document.querySelector('[data-query]')?.dataset.query.includes('view=control') && !document.querySelector('[data-m7-observation-editor]')); }
    if (exercise === 'material-history') { await waitFor(() => document.querySelector('[data-m7-material-recipes]'), 'material recipes'); check('Material deep link retains resource and foo', document.querySelector('[data-query]')?.dataset.query.includes('matTab=recipes') && document.querySelector('[data-query]')?.dataset.query.includes('resourceId=701') && document.querySelector('[data-query]')?.dataset.query.includes('foo=preserved')); await click('Rates'); await waitFor(() => document.querySelector('[data-m7-material-rates]'), 'material rates'); await click('Conversions'); await waitFor(() => document.querySelector('[data-m7-material-conversions]'), 'material conversions'); window.__m7Navigate(-1); await waitFor(() => document.querySelector('[data-m7-material-rates]'), 'material history back rates'); check('Material Back restores Rates', document.querySelector('[data-query]')?.dataset.query.includes('matTab=rates')); window.__m7Navigate(-1); await waitFor(() => document.querySelector('[data-m7-material-recipes]'), 'material history back recipes'); window.__m7Navigate(1); await waitFor(() => document.querySelector('[data-m7-material-rates]'), 'material history forward'); check('Material history preserves unrelated query and singular module', document.querySelector('[data-query]')?.dataset.query.includes('foo=preserved') && document.querySelectorAll('[data-m7-module="Material Management"]').length === 1); }
    if (exercise === 'admin') { await click('Change'); await waitFor(() => document.body.textContent.includes('Material Management'), 'admin module selector'); check('Admin sees M7 modules through project shell', document.body.textContent.includes('Quality') && document.body.textContent.includes('Safety') && document.body.textContent.includes('Material Management')); await click('Quality'); await click('QA/QC Control'); await waitFor(() => button('New observation'), 'admin quality control'); check('Admin Quality write control is available', Boolean(button('New observation'))); }
    if (exercise === 'methodology-workflow') await runDocumentWorkflow(check, 'methodology');
    if (exercise === 'checklist-workflow') await runDocumentWorkflow(check, 'checklist');
    if (exercise === 'quality-403') { await waitFor(() => document.body.textContent.includes('Access denied by the current ERP permission policy.'), 'quality access denial'); check('Quality 403 keeps shell and singular module', document.querySelectorAll('[data-mobile-page="project-shell"]').length === 1 && document.querySelectorAll('[data-m7-module="Quality"]').length === 1 && calls.mutations === 0); }
    if (exercise === 'quality-failure') { await click('A level'); await click('Approve fix'); await waitFor(() => document.body.textContent.includes('Synthetic approval failure'), 'quality mutation failure'); check('Quality failed mutation retains existing row and clears pending', document.body.textContent.includes('A level') && !button('Saving…') && document.querySelector('[data-path]')?.dataset.path === '/projects/42'); }
}

function Checks() {
    const [rows, setRows] = useState([]);
    useEffect(() => { let cancelled = false; (async () => { try { await waitFor(() => document.querySelector('[data-layout-branch]'), 'layout'); await pause(80); const result = []; const check = (label, pass, detail = '') => result.push({ label, pass: Boolean(pass), detail }); const mobile = innerWidth <= 1023; check('Exact declared viewport', innerWidth === width, `${innerWidth}/${width}`); check('Exactly one presentation branch', document.querySelectorAll('[data-layout-branch]').length === 1); check('Correct responsive branch', mobile ? Boolean(document.querySelector('[data-layout-branch="mobile"]')) : Boolean(document.querySelector('[data-layout-branch="desktop"]'))); if (mobile) { check('Mobile layout once', document.querySelectorAll('[data-layout-branch="mobile"]').length === 1); check('Project shell once', document.querySelectorAll('[data-mobile-page="project-shell"]').length === 1); check('Mobile Agent once', document.querySelectorAll('[data-agent-contract="mobile"]').length === 1); check('M7 outlet once', document.querySelectorAll(`[data-m7-module="${tab}"]`).length === 1); check('No desktop sentinel', !document.querySelector('[data-desktop-sentinel]')); check('No horizontal overflow', document.documentElement.scrollWidth <= innerWidth, `${document.documentElement.scrollWidth}/${innerWidth}`); if (tab === 'Safety') check('Safety stays static and network-free', document.body.textContent.includes('HS Plan') && document.body.textContent.includes('Safety Guideline') && calls.quality.length === 0 && calls.project.filter((row) => row[0] === 'listProjectResources').length === 0); if (access === 'read') check('Read-only has no mutation controls', !document.body.textContent.includes('New observation') && !document.body.textContent.includes('Create resource') && calls.mutations === 0); await runExercise(check); } else check('Desktop sentinel only', Boolean(document.querySelector('[data-desktop-sentinel]')) && !document.querySelector('[data-mobile-page="project-shell"]') && !document.querySelector('[data-agent-contract="mobile"]')); check('No real ERP or Agent network', network.length === 0, network.join(',')); if (!cancelled) { setRows(result); parent.postMessage({ type: 'm7-results', caseId, rows: result }, location.origin); } } catch (error) { const result = [{ label: 'Harness exercise completed', pass: false, detail: error.message }]; if (!cancelled) { setRows(result); parent.postMessage({ type: 'm7-results', caseId, rows: result }, location.origin); } } })(); return () => { cancelled = true; }; }, []);
    return <ol>{rows.map((row) => <li key={row.label}>{row.pass ? 'PASS' : 'FAIL'} {row.label}</li>)}</ol>;
}
function Frame() { const qualityView = ['quality-create', 'quality-edit', 'quality-clear', 'quality-approve', 'quality-read-race', 'quality-mutation-race', 'quality-403', 'quality-failure'].includes(exercise) ? 'control' : ['quality-docs', 'methodology-workflow'].includes(exercise) ? 'methodology' : exercise === 'checklist-workflow' ? 'check-snag' : exercise === 'quality-matrix' ? 'matrix' : 'hub'; const matTab = exercise === 'material-rates' ? 'rates' : exercise === 'material-conversions' ? 'conversions' : exercise === 'material-history' ? 'recipes' : 'grid'; const initial = `/projects/42?tab=${encodeURIComponent(tab)}&foo=preserved${tab === 'Quality' ? `&view=${qualityView}` : tab === 'Material Management' ? `&matTab=${matTab}&resourceId=701` : ''}`; return <ThemeProvider attribute="class" defaultTheme={params.get('theme') || 'light'} enableSystem={false}><AuthProvider><MemoryRouter initialEntries={[initial]}><Probe /><Checks /><Routes><Route path="/" element={<MobilePilotLayout mobile={<MobileMainLayout loadProjects={async () => ({ projects: [] })} />} desktop={<DesktopLayout />} />}><Route path="projects/:id" element={<ResponsiveRoute mobile={<MobileProjectShell authOverride={authOverride} projectService={projectService} moduleServices={{ quality, projects: projectService, resources }} />} desktop={<Desktop />} />} /></Route></Routes></MemoryRouter></AuthProvider></ThemeProvider>; }
const cases = [
    { id: 'quality-360', width: 360, tab: 'Quality' }, { id: 'safety-390', width: 390, tab: 'Safety' }, { id: 'material-430', width: 430, tab: 'Material Management' }, { id: 'quality-768-dark', width: 768, tab: 'Quality', theme: 'dark' }, { id: 'material-1023', width: 1023, tab: 'Material Management' }, { id: 'desktop-1024', width: 1024, tab: 'Quality' },
    { id: 'quality-create', width: 390, tab: 'Quality', exercise: 'quality-create' }, { id: 'quality-edit-photo-retention', width: 430, tab: 'Quality', exercise: 'quality-edit' }, { id: 'quality-explicit-photo-clear', width: 430, tab: 'Quality', exercise: 'quality-clear' }, { id: 'quality-approve-refresh', width: 390, tab: 'Quality', exercise: 'quality-approve' }, { id: 'quality-documents', width: 390, tab: 'Quality', exercise: 'quality-docs' }, { id: 'quality-matrix-local', width: 390, tab: 'Quality', exercise: 'quality-matrix' },
    { id: 'material-batch-import', width: 390, tab: 'Material Management', exercise: 'material-batch' }, { id: 'material-rate-contract', width: 430, tab: 'Material Management', exercise: 'material-rates' }, { id: 'material-conversion-contract', width: 430, tab: 'Material Management', exercise: 'material-conversions' }, { id: 'quality-read-only', width: 390, tab: 'Quality', access: 'read' }, { id: 'material-read-only', width: 390, tab: 'Material Management', access: 'read' },
    { id: 'quality-project-switch-read', width: 390, tab: 'Quality', exercise: 'quality-read-race' }, { id: 'quality-project-switch-mutation', width: 390, tab: 'Quality', exercise: 'quality-mutation-race' }, { id: 'material-project-switch-read', width: 430, tab: 'Material Management', exercise: 'material-read-race' }, { id: 'material-project-switch-mutation', width: 430, tab: 'Material Management', exercise: 'material-mutation-race' },
    { id: 'quality-back-forward', width: 390, tab: 'Quality', exercise: 'quality-history' }, { id: 'material-back-forward', width: 430, tab: 'Material Management', exercise: 'material-history' }, { id: 'admin-project-shell', width: 390, tab: 'Quality', exercise: 'admin', access: 'admin' },
    { id: 'methodology-workflow', width: 390, tab: 'Quality', exercise: 'methodology-workflow' }, { id: 'checklist-workflow', width: 390, tab: 'Quality', exercise: 'checklist-workflow' }, { id: 'quality-read-403', width: 390, tab: 'Quality', exercise: 'quality-403' }, { id: 'quality-mutation-failure', width: 390, tab: 'Quality', exercise: 'quality-failure' },
];
function Parent() { const [reports, setReports] = useState({}); const completed = Object.keys(reports).length; const item = cases[completed]; useEffect(() => { const receive = (event) => { if (event.origin === location.origin && event.data?.type === 'm7-results') setReports((current) => current[event.data.caseId] ? current : { ...current, [event.data.caseId]: event.data.rows }); }; addEventListener('message', receive); return () => removeEventListener('message', receive); }, []); const resultRows = Object.values(reports).flat(); return <main><h1>M7 harness</h1><p data-harness-summary>Completed {completed}/{cases.length}; PASS {resultRows.filter((row) => row.pass).length}; FAIL {resultRows.filter((row) => !row.pass).length}.</p><ul data-harness-failures>{Object.entries(reports).flatMap(([id, result]) => result.filter((row) => !row.pass).map((row) => <li key={`${id}-${row.label}`}>{id}: {row.label} {row.detail}</li>))}</ul>{item && <iframe key={item.id} title={item.id} width={item.width} height="880" src={`./m7-harness.html?${new URLSearchParams({ frame: '1', case: item.id, width: item.width, tab: item.tab, access: item.access || 'write', exercise: item.exercise || 'render', ...(item.theme ? { theme: item.theme } : {}) })}`} />}</main>; }
createRoot(document.getElementById('root')).render(frame ? <Frame /> : <Parent />);
