import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MemoryRouter, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ThemeProvider } from 'next-themes';
import '../../src/index.css';
import { AuthProvider } from '../../src/context/AuthContext';
import MobileMainLayout from '../../src/mobile/layout/MobileMainLayout';
import MobilePilotLayout from '../../src/mobile/routing/MobilePilotLayout';
import ResponsiveRoute from '../../src/mobile/routing/ResponsiveRoute';
import MobileProjectShell from '../../src/mobile/pages/ProjectDetails/MobileProjectShell';

const params=new URLSearchParams(location.search);const frame=params.get('frame')==='1';const width=Number(params.get('width')||390);const physicalWidth=Number(params.get('physicalWidth')||width);const caseId=params.get('case')||'m9';const exercise=params.get('exercise')||'planning-hub';const access=params.get('access')||'write';const moduleName=params.get('module')||'Planning';const theme=params.get('theme')||'light';
const wait=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));const waitFor=async(predicate,label,timeout=5000)=>{const start=Date.now();while(Date.now()-start<timeout){if(predicate())return;await wait(20);}throw new Error(`Timed out: ${label}`);};const clone=(value)=>JSON.parse(JSON.stringify(value));
const network=[];window.fetch=(input)=>{network.push(`fetch ${String(input)}`);return Promise.reject(new Error('M9 harness blocks network'));};XMLHttpRequest.prototype.open=function block(method,url){network.push(`${method} ${url}`);throw new Error('M9 harness blocks network');};HTMLAnchorElement.prototype.click=function observe(){counters.downloads.push(this.download);};
const counters={loads:0,reads:[],mutations:[],downloads:[],ai:[]};const deferred={};const defer=(key)=>{let resolve,reject;const promise=new Promise((done,fail)=>{resolve=done;reject=fail;});return(deferred[key]={promise,resolve,reject});};
const users=[{user_id:7,user_name:'Ada Admin',user_type:'admin'},{user_id:8,user_name:'Lin Engineer',user_type:'employee'},{user_id:9,user_name:'Sam Reviewer',user_type:'employee'}];
const project=(id)=>({id:Number(id),name:Number(id)===43?'Project B':'Project A',project_code:`SYN-${id}`,org_id:3,status:'active',metadata:{}});
const permissionLevel=access==='read'?1:2;
const projectService={getProject:async(id)=>{counters.reads.push(['project',Number(id)]);return{success:true,project:project(id),projectPermissions:{Planning:permissionLevel,Contracts:permissionLevel,Billing:permissionLevel,Approvals:permissionLevel}};},getProjectMembers:async(id)=>{counters.reads.push(['members',Number(id)]);return{success:true,members:[{user_id:8,user_name:`Lin ${id}`,user_type:'employee',project_permissions:{Planning:'write',Approvals:'view'}}]};},assignProjectMember:async(id,payload)=>{counters.mutations.push(['assignProjectMember',Number(id),clone(payload)]);return{success:true};},removeProjectMember:async(id,userId)=>{counters.mutations.push(['removeProjectMember',Number(id),Number(userId)]);return{success:true};}};
const templateRows=(id)=>[{document_id:Number(id)*10+1,name:'Tasks',project_id:Number(id),doc_type:'singleton'},{document_id:Number(id)*10+2,name:'Agenda of Meeting',project_id:Number(id),doc_type:'episodic'}];
const detailFor=(documentId)=>({success:true,template:{document_id:documentId,name:String(documentId).endsWith('2')?'Agenda of Meeting':'Tasks',document_roles:[{id:501,user_id:7,role:'reporter',level_id:null},{id:502,user_id:8,role:'approver',level_id:601}],approval_levels:[{level_id:601,label:'Engineer Review',level_order:1}]}});
const workflow={getTemplates:async(id)=>{counters.reads.push(['templates',Number(id)]);if(exercise==='approval-error')throw new Error('Synthetic workflow read failure');if(exercise==='approval-403')throw{response:{status:403}};if(exercise==='approval-race'&&String(id)==='42')return(deferred.templatesA||defer('templatesA')).promise;return{success:true,templates:templateRows(id)};},getTemplate:async(id)=>{counters.reads.push(['template',Number(id)]);return detailFor(id);},createTemplate:async(payload)=>{counters.mutations.push(['createTemplate',clone(payload)]);return{success:true,document_id:777};},removeRole:async(...args)=>{counters.mutations.push(['removeRole',...clone(args)]);},removeLevel:async(...args)=>{counters.mutations.push(['removeLevel',...clone(args)]);},addLevel:async(...args)=>{counters.mutations.push(['addLevel',...clone(args)]);return{success:true,level_id:888};},assignRole:async(...args)=>{counters.mutations.push(['assignRole',...clone(args)]);if(exercise==='approval-mutation-race')return(deferred.mutationA||defer('mutationA')).promise;return{success:true};}};
const admin={getUsers:async()=>{counters.reads.push(['users']);return{success:true,users};},getPermissionTemplates:async()=>({success:true,templates:[{id:90,name:'Read Template',type:'project',permissions:{Planning:'view',Approvals:'view'}}]}),createPermissionTemplate:async(payload)=>{counters.mutations.push(['createPermissionTemplate',clone(payload)]);return{success:true};},updatePermissionTemplate:async(id,payload)=>{counters.mutations.push(['updatePermissionTemplate',id,clone(payload)]);return{success:true};},deletePermissionTemplate:async(id)=>{counters.mutations.push(['deletePermissionTemplate',id]);return{success:true};}};
const ai={scheduleInsights:async(payload)=>{counters.ai.push(['schedule',clone(payload)]);if(exercise==='schedule-ai-error')throw new Error('Synthetic schedule AI failure');if(exercise==='schedule-ai-race')return(deferred.scheduleA||defer('scheduleA')).promise;return{data:{insights:[{title:'Sequence review',body:'Review the critical path.'}]}};},budgetInsights:async(payload)=>{counters.ai.push(['budget',clone(payload)]);if(exercise==='budget-ai-error')throw new Error('Synthetic budget AI failure');if(exercise==='budget-ai-race')return(deferred.budgetA||defer('budgetA')).promise;return{data:{insights:[{title:'Cost review',body:'Verify the largest cost section.'}]}};}};
const authOverride={user:{user_id:7,user_type:access==='admin'?'admin':'employee'},isAdmin:access==='admin'};
function DesktopLayout(){return <div data-layout-branch="desktop"><Outlet/></div>}function DesktopPage(){return <div data-desktop-page="project-details">Existing desktop ProjectDetails sentinel</div>}function Probe(){const current=useLocation();return <span hidden data-path={current.pathname} data-search={current.search}/>}
function HistoryDriver(){const navigate=useNavigate();return <div hidden><button type="button" aria-label="Harness back" onClick={()=>navigate(-1)}/><button type="button" aria-label="Harness forward" onClick={()=>navigate(1)}/></div>}
function SwitchDriver(){const navigate=useNavigate();const once=useRef(false);useEffect(()=>{if(once.current)return;if(!['schedule-ai-race','budget-ai-race','approval-race','approval-mutation-race'].includes(exercise))return;once.current=true;const delay=exercise==='approval-mutation-race'?1300:300;setTimeout(()=>navigate(`/projects/43?tab=${moduleName}&foo=keep${exercise.startsWith('budget')?'&report=budget':''}`),delay);setTimeout(()=>{deferred.scheduleA?.resolve({data:{insights:[{title:'Project A stale',body:'Must not render'}]}});deferred.budgetA?.resolve({data:{insights:[{title:'Project A stale',body:'Must not render'}]}});deferred.templatesA?.resolve({success:true,templates:templateRows(42)});deferred.mutationA?.resolve({success:true});},delay+350);},[navigate]);return null;}
const button=(text,root=document)=>[...root.querySelectorAll('button')].find((item)=>item.textContent.trim().includes(text));const exact=(text,root=document)=>[...root.querySelectorAll('button')].find((item)=>item.textContent.trim()===text);const setValue=(element,value)=>{if(!element)return;const proto=element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')?.set?.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}));};
async function exerciseUi(rows){const check=(label,pass,detail='')=>rows.push({label,pass:Boolean(pass),detail});
    if(exercise==='planning-hub')check('Planning hub exposes five planning workspaces and Contracts-owned Budget',document.body.textContent.includes('Project Planning & Bar Chart')&&document.body.textContent.includes('Events / Hindrance Report')&&document.body.textContent.includes('Owned by Contracts'));
    if(exercise==='planning-query'){check('Project Planning query mounts schedule workspace',Boolean(document.querySelector('[data-m9-view="project-planning"]')));check('Unrelated query preserved',document.querySelector('[data-search]')?.dataset.search.includes('foo=keep'));}
    if(exercise==='planning-write'){check('Write schedule exposes local edit controls',Boolean(button('Add phase'))&&Boolean(button('Add task')));button('Design Approval')?.click();await waitFor(()=>document.querySelector('[role="dialog"]'),'task detail');check('Task detail uses shared sheet',Boolean(document.querySelector('[data-testid="mobile-bottom-sheet-layer"]')));check('Task contract shows original schedule and flags',document.querySelector('[role="dialog"]')?.textContent.includes('High priority'));exact('Close',document.querySelector('[role="dialog"]'))?.click();}
    if(exercise==='planning-read'){check('Read schedule hides mutation controls',!button('Add phase')&&!button('Add task')&&!button('Edit phase')&&!button('Delete'));}
    if(exercise.startsWith('schedule-ai')){button('AI insights')?.click();await waitFor(()=>exercise==='schedule-ai-error'?Boolean(button('Retry'))&&document.body.textContent.includes('Synthetic schedule AI failure'):exercise==='schedule-ai'?document.body.textContent.includes('Sequence review'):Boolean(counters.ai.length),'schedule AI state');check('Schedule AI receives phases and macro',counters.ai[0]?.[0]==='schedule'&&Array.isArray(counters.ai[0]?.[1]?.phases)&&counters.ai[0]?.[1]?.macro===false,JSON.stringify(counters.ai));if(exercise==='schedule-ai')check('Schedule AI success visible',document.body.textContent.includes('Sequence review'));if(exercise==='schedule-ai-error')check('Schedule AI error and retry visible',document.body.textContent.includes('Synthetic schedule AI failure')&&Boolean(button('Retry')));if(exercise==='schedule-ai-race'){await wait(750);check('Project B mounts after AI race',document.body.textContent.includes('Project B'));check('Late Project A AI result ignored',!document.body.textContent.includes('Project A stale'));}}
    if(exercise==='material'){await waitFor(()=>document.body.textContent.includes('Cement')&&Boolean(button('Export CSV')),'material generated plan');check('Material demo disclosure visible',document.body.textContent.includes('not live procurement'));check('Material cards and CSV present',document.body.textContent.includes('Cement')&&button('Export CSV'));}
    if(exercise==='manpower-query'){check('Manpower planning query mounts',Boolean(button('Import from Project Plan'))&&document.querySelector('[data-search]')?.dataset.search.includes('mpView=planning'));button('Histogram')?.click();await wait(50);check('Manpower view updates URL preserving foo',!document.querySelector('[data-search]')?.dataset.search.includes('mpView=')&&document.querySelector('[data-search]')?.dataset.search.includes('foo=keep'));document.querySelector('[aria-label="Harness back"]')?.click();await wait(60);check('Browser Back restores manpower planning',document.querySelector('[data-search]')?.dataset.search.includes('mpView=planning'));}
    if(exercise==='manpower-read'){check('Read-only manpower planning hides imports and add controls',!button('Import Project Plan')&&!button('Add phase'));button('Excavation')?.click();await wait(50);check('Allocation detail is read-only',Boolean(document.querySelector('[role="dialog"]'))&&!button('Apply allocation',document.querySelector('[role="dialog"]')));}
    if(exercise==='logistic'){await waitFor(()=>button('OPC 53 Cement'),'delivery card');await wait(80);check('Local delivery and equipment tabs present',button('Deliveries')&&button('Equipment'));button('OPC 53 Cement').click();await waitFor(()=>[...document.querySelectorAll('[role="dialog"]')].some((dialog)=>dialog.textContent.includes('PO-2026-001')),'delivery detail');const detailDialog=[...document.querySelectorAll('[role="dialog"]')].find((dialog)=>dialog.textContent.includes('PO-2026-001'));check('Delivery detail opens',Boolean(detailDialog));detailDialog?.querySelector('[aria-label="Close"]')?.click();await waitFor(()=>![...document.querySelectorAll('[role="dialog"]')].some((dialog)=>dialog.textContent.includes('PO-2026-001')),'delivery detail close');button('Summary')?.click();await waitFor(()=>[...document.querySelectorAll('[role="dialog"]')].some((dialog)=>dialog.textContent.includes('Local Logistics Summary')),'logistics summary');check('Heuristic summary is labelled local',[...document.querySelectorAll('[role="dialog"]')].some((dialog)=>dialog.textContent.includes('Local Logistics Summary')));}
    if(exercise==='logistic-read'){check('Logistic read-only hides local mutation controls',!button('Add delivery'));button('OPC 53 Cement')?.click();await wait(40);check('Read detail has no Edit or Delete',!button('Edit local item',document.querySelector('[role="dialog"]'))&&!button('Delete',document.querySelector('[role="dialog"]')));}
    if(exercise==='hindrance'){check('Computed delays visible',document.body.textContent.includes('Start +1d'));button('Mobilisation of Excavator')?.click();await wait(40);check('Hindrance detail exposes computed read-only fields',document.querySelector('[role="dialog"]')?.textContent.includes('Computed delays'));}
    if(exercise==='hindrance-read')check('Read-only hindrance hides add control',!button('Add hindrance'));
    if(exercise==='contracts'){check('Contracts categories stay truthful and noninteractive',document.body.textContent.includes('Quantity Survey')&&document.body.textContent.includes('Unavailable in current source'));check('Budget is the only reachable Contracts child',Boolean(button('Budget')));}
    if(exercise==='budget'){check('Budget landing uses all 11 source sections',document.body.textContent.includes('Civil Works')&&document.body.textContent.includes('Contingency'));button('Civil Works')?.click();await wait(60);check('Budget section query set and unrelated key preserved',document.querySelector('[data-search]')?.dataset.search.includes('section=civil')&&document.querySelector('[data-search]')?.dataset.search.includes('foo=keep'));check('Budget cards replace spreadsheet',Boolean(document.querySelector('[data-m9-view="budget-section"]'))&&!document.querySelector('table'));}
    if(exercise==='budget-read'){check('Read-only Budget hides new section',!button('New section'));button('Civil Works')?.click();await wait(40);check('Read-only Budget hides add/delete/reorder actions',!button('Add budget line')&&!button('Delete line')&&!document.querySelector('[aria-label="Move line up"]'));}
    if(exercise.startsWith('budget-ai')){button('AI insights')?.click();await waitFor(()=>exercise==='budget-ai-error'?Boolean(button('Retry')):exercise==='budget-ai'?document.body.textContent.includes('Cost review'):Boolean(counters.ai.length),'budget AI state');check('Budget AI receives source payload',counters.ai[0]?.[0]==='budget'&&Array.isArray(counters.ai[0]?.[1]?.budgetData));if(exercise==='budget-ai')check('Budget AI success visible',document.body.textContent.includes('Cost review'));if(exercise==='budget-ai-error')check('Budget AI retry visible',Boolean(button('Retry')));if(exercise==='budget-ai-race'){await wait(750);check('Late Project A budget AI ignored',document.body.textContent.includes('Project B')&&!document.body.textContent.includes('Project A stale'));}}
    if(exercise==='billing')check('Billing is a truthful noninteractive source hub',document.body.textContent.includes('Invoice – Materials')&&document.body.textContent.includes('No reachable invoice'));
    if(exercise==='approval-hub'){await waitFor(()=>document.body.textContent.includes('Tasks')&&document.body.textContent.includes('Configured'),'workflow hub');check('Workflow hub loads actual template state',document.body.textContent.includes('Tasks')&&document.body.textContent.includes('Configured'));button('General Documents')?.click();await waitFor(()=>document.body.textContent.includes('Project Vendor List')&&document.body.textContent.includes('Daily Progress Report (DPR)'),'General Documents workflows');check('General Documents drills into eight source workflows',document.body.textContent.includes('Project Vendor List')&&document.body.textContent.includes('Daily Progress Report (DPR)'));}
    if(exercise==='approval-edit'){await waitFor(()=>Boolean(button('Tasks')),'Tasks workflow');button('Tasks')?.click();await waitFor(()=>document.body.textContent.includes('Ada Admin')&&document.body.textContent.includes('Lin Engineer'),'loaded workflow roles');check('Loaded roles map by user_id',document.body.textContent.includes('Ada Admin')&&document.body.textContent.includes('Lin Engineer'));button('Save workflow')?.click();await waitFor(()=>counters.mutations.some((item)=>item[0]==='removeRole'),'workflow rebuild');check('Destructive rebuild removes roles before levels',counters.mutations.findIndex((item)=>item[0]==='removeRole')>=0&&counters.mutations.findIndex((item)=>item[0]==='removeRole')<counters.mutations.findIndex((item)=>item[0]==='removeLevel'),JSON.stringify(counters.mutations));check('Role payload uses user_id',counters.mutations.filter((item)=>item[0]==='assignRole').every((item)=>item[2]?.user_id));}
    if(exercise==='approval-read'){button('Tasks')?.click();await wait(50);check('Read-only workflow hides mutation controls',!button('Save workflow')&&!button('Assign')&&!button('Stage'));check('Read-only workflow issues zero mutations',counters.mutations.length===0);}
    if(exercise==='approval-admin'){await waitFor(()=>Boolean(button('Member Permissions'))&&Boolean(button('Approval Workflows')),'admin Approval tabs');check('Admin receives both Approval tabs',button('Member Permissions')&&button('Approval Workflows'));button('Member Permissions')?.click();await waitFor(()=>document.body.textContent.includes('Lin 42')&&document.body.textContent.includes('Read Template'),'admin permissions workspace');check('Admin member permission workspace loads real user_id member',document.body.textContent.includes('Lin 42')&&document.body.textContent.includes('Read Template'));}
    if(exercise==='approval-error'||exercise==='approval-403'){const expected=exercise==='approval-403'?'Access denied':'Synthetic workflow read failure';await waitFor(()=>document.body.textContent.includes(expected),'approval failure state');check('Approval failure state is truthful',document.body.textContent.includes(expected));}
    if(exercise==='approval-race'){await wait(900);check('Project B starts own workflow read',counters.reads.some((item)=>item[0]==='templates'&&item[1]===43));check('Late A read cannot overwrite B',document.body.textContent.includes('Project B'));}
    if(exercise==='query-history'){await waitFor(()=>Boolean(button('Logistic Plan')),'planning logistic card');button('Logistic Plan')?.click();await waitFor(()=>Boolean(document.querySelector('[data-m9-view="logistic-plan"]')),'planning child');check('Planning child query preserves unrelated key',document.querySelector('[data-search]')?.dataset.search.includes('report=logistic-plan')&&document.querySelector('[data-search]')?.dataset.search.includes('foo=keep'));document.querySelector('[aria-label="Harness back"]')?.click();await waitFor(()=>Boolean(document.querySelector('[data-m9-view="planning-hub"]')),'planning Back');check('Back returns child to hub',Boolean(document.querySelector('[data-m9-view="planning-hub"]')));document.querySelector('[aria-label="Harness forward"]')?.click();await waitFor(()=>Boolean(document.querySelector('[data-m9-view="logistic-plan"]')),'planning Forward');check('Forward restores child',Boolean(document.querySelector('[data-m9-view="logistic-plan"]')));}
}
function Checks(){const[result,setResult]=useState(null);useEffect(()=>{let active=true;(async()=>{window.parent.postMessage({type:'mano-m9-viewport',caseId,physicalWidth,declared:width,actual:innerWidth},location.origin);if(innerWidth!==width)return;const rows=[];const check=(label,pass,detail='')=>rows.push({label,pass:Boolean(pass),detail});try{await waitFor(()=>document.querySelector('[data-layout-branch]')||document.querySelector('[data-desktop-page]'),'presentation branch');check('Actual viewport equals declared width',innerWidth===width,`${innerWidth} !== ${width}`);if(width>=1024){check('Desktop sentinel only',Boolean(document.querySelector('[data-desktop-page]'))&&!document.querySelector('[data-layout-branch="mobile"]'));check('Desktop has no mobile Agent',!document.querySelector('[data-agent-contract="mobile"]'));check('Exactly one presentation branch',document.querySelectorAll('[data-layout-branch]').length===1);}else{await waitFor(()=>document.querySelector('[data-mobile-page="project-shell"]'),'mobile project shell');check('Mobile branch only',Boolean(document.querySelector('[data-layout-branch="mobile"]'))&&!document.querySelector('[data-desktop-page]'));check('Exactly one MobileMainLayout',document.querySelectorAll('[data-layout-branch="mobile"]').length===1);check('Exactly one project shell',document.querySelectorAll('[data-mobile-page="project-shell"]').length===1);check('Exactly one Agent',document.querySelectorAll('[data-agent-contract="mobile"]').length===1);check('No viewport horizontal overflow',document.documentElement.scrollWidth<=innerWidth+1,`${document.documentElement.scrollWidth}/${innerWidth}`);check('No real network',network.length===0,JSON.stringify(network));await exerciseUi(rows);}}catch(error){check('Frame execution',false,error.stack||error.message);}if(active){window.__M9_HARNESS_RESULT__={caseId,rows,counters:clone(counters)};window.parent.postMessage({type:'mano-m9-results',caseId,physicalWidth,rows},location.origin);setResult(rows);}})();return()=>{active=false};},[]);return result?<ol className="fixed left-0 top-0 z-[100] max-h-40 overflow-auto bg-white p-2 text-[9px]">{result.map((row)=><li key={row.label}>{row.pass?'PASS':'FAIL'} {row.label}</li>)}</ol>:null;}
function Frame(){let query={tab:moduleName,foo:'keep'};if(exercise.startsWith('planning-')&&exercise!=='planning-hub')query.report='project-planning';if(exercise.startsWith('schedule-ai'))query.report='project-planning';if(exercise==='material')query.report='material-histogram';if(exercise.startsWith('manpower')){query.report='manpower-histogram';query.mpView='planning';}if(exercise.startsWith('logistic'))query.report='logistic-plan';if(exercise.startsWith('hindrance'))query.report='hindrance-report';if(exercise.startsWith('budget'))query.report='budget';const initial=`/projects/42?${new URLSearchParams(query)}`;return <ThemeProvider attribute="class" defaultTheme={theme} enableSystem={false}><AuthProvider><MemoryRouter initialEntries={[initial]}><Probe/><HistoryDriver/><SwitchDriver/><Checks/><Routes><Route path="/" element={<MobilePilotLayout mobile={<MobileMainLayout loadProjects={async()=>{counters.loads+=1;return{projects:[]}}}/>} desktop={<DesktopLayout/>}/>}><Route path="projects/:id" element={<ResponsiveRoute mobile={<MobileProjectShell authOverride={authOverride} projectService={projectService} moduleServices={{projects:projectService,admin,workflow,ai}}/>} desktop={<DesktopPage/>}/>} /></Route></Routes></MemoryRouter></AuthProvider></ThemeProvider>}
const allCases=[
{id:'m9-360-light',width:360},{id:'m9-390-light',width:390},{id:'m9-430-dark',width:430,theme:'dark'},{id:'m9-768',width:768},{id:'m9-1023',width:1023},{id:'m9-1024-desktop',width:1024},
{id:'planning-query',width:390,exercise:'planning-query'},{id:'planning-write',width:390,exercise:'planning-write'},{id:'planning-read',width:390,exercise:'planning-read',access:'read'},{id:'schedule-ai',width:390,exercise:'schedule-ai'},{id:'schedule-ai-error',width:390,exercise:'schedule-ai-error'},{id:'schedule-ai-race',width:390,exercise:'schedule-ai-race'},
{id:'material',width:390,exercise:'material'},{id:'manpower-query',width:390,exercise:'manpower-query'},{id:'manpower-read',width:390,exercise:'manpower-read',access:'read'},{id:'logistic',width:390,exercise:'logistic'},{id:'logistic-read',width:390,exercise:'logistic-read',access:'read'},{id:'hindrance',width:390,exercise:'hindrance'},{id:'hindrance-read',width:390,exercise:'hindrance-read',access:'read'},
{id:'contracts',width:390,exercise:'contracts',module:'Contracts'},{id:'budget',width:390,exercise:'budget',module:'Contracts'},{id:'budget-read',width:390,exercise:'budget-read',module:'Contracts',access:'read'},{id:'budget-ai',width:390,exercise:'budget-ai',module:'Contracts'},{id:'budget-ai-error',width:390,exercise:'budget-ai-error',module:'Contracts'},{id:'budget-ai-race',width:390,exercise:'budget-ai-race',module:'Contracts'},
{id:'billing',width:390,exercise:'billing',module:'Billing'},{id:'approval-hub',width:390,exercise:'approval-hub',module:'Approvals'},{id:'approval-edit',width:390,exercise:'approval-edit',module:'Approvals'},{id:'approval-read',width:390,exercise:'approval-read',module:'Approvals',access:'read'},{id:'approval-admin',width:390,exercise:'approval-admin',module:'Approvals',access:'admin'},{id:'approval-error',width:390,exercise:'approval-error',module:'Approvals'},{id:'approval-403',width:390,exercise:'approval-403',module:'Approvals'},{id:'approval-race',width:390,exercise:'approval-race',module:'Approvals'},{id:'query-history',width:390,exercise:'query-history'}];
const start=Math.max(0,Number(params.get('start')||0));const limit=Math.max(1,Number(params.get('limit')||allCases.length));const cases=allCases.slice(start,start+limit);
const url=(item,frameWidth)=>`./m9-harness.html?${new URLSearchParams({frame:'1',case:item.id,width:String(item.width),physicalWidth:String(frameWidth),exercise:item.exercise||'planning-hub',module:item.module||'Planning',access:item.access||'write',theme:item.theme||'light'})}`;
function Parent(){const[reports,setReports]=useState({});const item=cases[Object.keys(reports).length];const[frameWidth,setFrameWidth]=useState(item?.width||390);const itemId=item?.id;useEffect(()=>{if(item)setFrameWidth(item.width);},[itemId]);useEffect(()=>{const receive=(event)=>{if(event.origin!==location.origin||event.data?.caseId!==itemId||event.data?.physicalWidth!==frameWidth)return;if(event.data.type==='mano-m9-viewport'&&event.data.actual!==event.data.declared)setFrameWidth((current)=>Math.max(320,current+(event.data.declared-event.data.actual)));if(event.data.type==='mano-m9-results')setReports((current)=>current[event.data.caseId]?current:{...current,[event.data.caseId]:event.data.rows});};addEventListener('message',receive);return()=>removeEventListener('message',receive);},[itemId,frameWidth]);const rows=Object.values(reports).flat();return <main className="min-h-screen bg-gray-100 p-4"><h1>M9 Planning, Contracts, Billing and Approvals harness</h1><p data-harness-summary>Completed {Object.keys(reports).length}/{cases.length}; PASS {rows.filter((row)=>row.pass).length}; FAIL {rows.filter((row)=>!row.pass).length}.</p><ul>{Object.entries(reports).flatMap(([id,result])=>result.filter((row)=>!row.pass).map((row)=><li key={`${id}-${row.label}`}>FAIL {id}: {row.label} — {row.detail}</li>))}</ul>{item&&<iframe key={`${item.id}-${frameWidth}`} title={item.id} width={frameWidth} height="820" scrolling="no" style={{border:0,display:'block',width:`${frameWidth}px`}} src={url(item,frameWidth)}/>}</main>}
createRoot(document.getElementById('root')).render(frame?<Frame/>:<Parent/>);
