import test from 'node:test';
import assert from 'node:assert/strict';
import { buildAssigneePayload, buildCategoryPayload, buildTaskCsv, buildTaskFieldPayload, buildTaskPayload, buildTaskReorderPayload, createAndAssignTask, filterTaskCategories, flattenTaskCategories, normalizeMember, taskStats, TASK_PRIORITIES, TASK_STATUSES } from '../../src/mobile/pages/ProjectDetails/Tasks/mobileTaskModel.js';
import { buildPhasesProjectPayload, phaseMetrics, phaseStatus } from '../../src/mobile/pages/ProjectDetails/Phases/mobilePhaseModel.js';
import { buildProjectSettingsPayload, PROJECT_STATUS_OPTIONS, projectSettingsForm, saveProjectSettingsWorkflow, validateProjectLogo } from '../../src/mobile/pages/ProjectDetails/Settings/mobileProjectSettingsModel.js';
import { projectDashboardSummary, STATIC_FINANCIAL_SUMMARY } from '../../src/mobile/pages/ProjectDetails/Dashboard/mobileProjectDashboardModel.js';

const categories = [{ id: 3, listName: 'Site', tasks: [{ id: 9, task_code: 'T-9', name: 'Excavate', status: 'in progress', priority: 'High', startDate: '2026-09-01', dueDate: '2026-09-02', assigneeIds: [7] }, { id: 10, name: 'Close', status: 'completed', priority: 'Low', assigneeIds: [] }] }];

test('M5 uses exact task workflow enum values', () => { assert.deepEqual(TASK_STATUSES, ['open', 'in progress', 'on hold', 'completed', 'cancelled']); assert.deepEqual(TASK_PRIORITIES, ['High', 'Medium', 'Low', 'None']); });
test('task create and field update payloads preserve API names', () => { assert.deepEqual(buildTaskPayload({ categoryId: '3', name: ' Work ', status: 'open', priority: 'Medium', startDate: '2026-09-01', dueDate: '2026-09-03' }), { category_id: 3, name: 'Work', status: 'open', priority: 'Medium', start_date: '2026-09-01', due_date: '2026-09-03', duration: 3 }); assert.deepEqual(buildTaskFieldPayload('dueDate', '2026-09-04', { startDate: '2026-09-01' }), { due_date: '2026-09-04', duration: 4 }); });
test('real project member identifiers normalize from user_id', () => { assert.deepEqual(normalizeMember({ user_id: 7, user_name: 'Dani' }), { user_id: 7, id: 7, user_name: 'Dani', name: 'Dani' }); });
test('dashboard derives task KPIs from nested task categories', () => { const summary = projectDashboardSummary({ metadata: '{}' }, categories); assert.equal(summary.taskStats.total, 2); assert.equal(summary.taskStats.completed, 1); assert.equal(summary.taskStats.inProgress, 1); assert.equal(summary.taskStats.highPriority, 1); assert.equal(summary.completion, 45); assert.equal(STATIC_FINANCIAL_SUMMARY.contractValue, '$ 4,850,000'); });
test('task filters search real assignee shape and preserve grouping', () => { const result = filterTaskCategories(categories, { query: 'dani', members: [normalizeMember({ user_id: 7, user_name: 'Dani' })] }); assert.deepEqual(flattenTaskCategories(result).map((item) => item.id), [9]); });
test('task CSV preserves the current export columns', () => { const csv = buildTaskCsv(categories); assert.match(csv, /"Section","Task Code","Task Name","Status","Priority","Start Date","Due Date","Duration"/); assert.match(csv, /"Site","T-9","Excavate"/); });
test('phase metrics and status use existing weighted completion semantics', () => { const phases = [{ progress: 50, weight: 40 }, { progress: 100, weight: 60 }]; assert.deepEqual(phaseMetrics(phases), { totalWeight: 100, completion: 80, completed: 1 }); assert.equal(phaseStatus(phases[0]), 'IN_PROGRESS'); });
test('phase payload preserves all metadata and project identity fields', () => { const project = { name: 'P', project_code: 'P-1', location: 'L', status: 'active', start_date: '2026-01-01', end_date: null, metadata: JSON.stringify({ issues: 'Risk', tags: ['a'] }) }; const phases = [{ id: 1, name: 'A', progress: 25, weight: 100 }]; assert.deepEqual(buildPhasesProjectPayload(project, phases), { name: 'P', project_code: 'P-1', location: 'L', status: 'active', start_date: '2026-01-01', end_date: null, metadata: { issues: 'Risk', tags: ['a'], phases, completion: 25 } }); });
test('settings payload preserves metadata and exact lifecycle values', () => { const project = { id: 4, name: 'Old', status: 'active', metadata: { tags: ['safe'] } }; const form = { ...projectSettingsForm(project), name: 'New', projectCode: 'N-1', description: 'D', location: '', startDate: '', endDate: '', status: 'archived' }; assert.deepEqual(buildProjectSettingsPayload(project, form), { name: 'New', project_code: 'N-1', location: null, status: 'archived', start_date: null, end_date: null, metadata: { tags: ['safe'], description: 'D' } }); assert.deepEqual(PROJECT_STATUS_OPTIONS.map((item) => item.value), ['active', 'completed', 'on-hold', 'archived']); });
test('settings logo validation enforces current type and 5MB limits', () => { assert.equal(validateProjectLogo({ type: 'image/png', size: 1024 }), ''); assert.match(validateProjectLogo({ type: 'text/plain', size: 1 }), /PNG/); assert.match(validateProjectLogo({ type: 'image/png', size: 5 * 1024 * 1024 + 1 }), /5MB/); });
test('task stats operate on actual nested response shape', () => { assert.equal(taskStats(categories).total, 2); });
test('category, assignment, and ordering payloads are exact', () => { assert.deepEqual(buildCategoryPayload(' Site '), { name: 'Site' }); assert.deepEqual(buildAssigneePayload([7, 8]), { assigneeIds: [7, 8] }); assert.deepEqual(buildTaskReorderPayload([{ id: 9 }, { id: 10 }]), { type: 'task', items: [{ id: 9, sort_order: 10 }, { id: 10, sort_order: 20 }] }); });
test('WIP create-and-assign awaits both existing task calls', async () => { const calls = []; const service = { createTask: async (...args) => { calls.push(['createTask', ...args]); return { success: true, task: { id: 99 } }; }, updateTaskAssignees: async (...args) => { calls.push(['updateTaskAssignees', ...args]); return { success: true }; } }; assert.deepEqual(await createAndAssignTask(service, 42, { name: 'A' }, 7), { task: { id: 99, assigneeIds: [7] }, assigned: true, assignmentError: null }); assert.deepEqual(calls, [['createTask', 42, { name: 'A' }], ['updateTaskAssignees', 42, 99, { assigneeIds: [7] }]]); });
test('WIP preserves a created task as unassigned when assignment fails', async () => { const failure = new Error('assignment denied'); const service = { createTask: async () => ({ success: true, task: { id: 100, name: 'Created' } }), updateTaskAssignees: async () => { throw failure; } }; const result = await createAndAssignTask(service, 42, { name: 'Created' }, 7); assert.deepEqual(result.task, { id: 100, name: 'Created', assigneeIds: [] }); assert.equal(result.assigned, false); assert.equal(result.assignmentError, failure); });
test('phase payload for a switched project contains only the new project identity and phases', () => { const projectB = { id: 43, name: 'B', project_code: 'B-43', status: 'active', metadata: { phases: [{ id: 'b', name: 'B phase', progress: 20, weight: 100 }] } }; const payload = buildPhasesProjectPayload(projectB, projectB.metadata.phases); assert.equal(payload.name, 'B'); assert.equal(payload.project_code, 'B-43'); assert.deepEqual(payload.metadata.phases.map((phase) => phase.id), ['b']); });
test('settings reports logo failure as partial only after base save succeeds', async () => { const calls = []; const service = { updateProject: async (...args) => { calls.push(['update', ...args]); return { success: true }; }, uploadProjectLogo: async (...args) => { calls.push(['logo', ...args]); throw new Error('upload failed'); } }; const project = { id: 4, name: 'P', status: 'active', metadata: {} }; const form = projectSettingsForm(project); const logo = { name: 'x.png' }; const result = await saveProjectSettingsWorkflow({ project, form, logoFile: logo, projectService: service }); assert.equal(result.success, true); assert.equal(result.partial, true); assert.equal(calls[0][0], 'update'); assert.deepEqual(calls[1], ['logo', 4, logo]); });
