import React, { useEffect, useMemo, useState } from 'react';
import MobileBottomSheet from '../../components/MobileBottomSheet';
import MobileFormSection from '../../components/MobileFormSection';
import MobileSelect from '../../components/MobileSelect';
import MobilePermissionTree from './MobilePermissionTree';
import { defaultSystemPermissions } from './mobileAdminModel';

const EMPTY = { name: '', email: '', phone_no: '', dept_id: '', desg_id: '', user_type: 'employee', password: '', system_permissions: defaultSystemPermissions(), project_ids: [] };
export default function MobileEmployeeEditor({ open, onClose, employee, projects = [], templates = [], onSave, pending }) {
    const [step, setStep] = useState(0); const [form, setForm] = useState(EMPTY); const [error, setError] = useState('');
    useEffect(() => { if (!open) return; setStep(0); setError(''); setForm(employee ? { ...EMPTY, ...employee, phone_no: employee.phone, dept_id: employee.departmentId, desg_id: employee.designationId, user_type: employee.role, system_permissions: employee.systemPermissions, project_ids: employee.projectIds } : { ...EMPTY, system_permissions: defaultSystemPermissions() }); }, [employee, open]);
    const steps = ['Account', 'System Access', 'Project Membership', 'Review'];
    const title = employee ? 'Edit employee access' : 'Create employee';
    const validAccount = useMemo(() => form.name.trim() && form.email.trim() && (employee || form.password), [employee, form]);
    const submit = async () => { if (!validAccount) { setError('Name, email, and an explicit password are required.'); setStep(0); return; } const result = await onSave?.(form); if (result?.success) onClose?.(); };
    const field = (id, label, type = 'text', required = false) => <label className="block text-xs font-semibold" htmlFor={id}>{label}<input id={id} type={type} required={required} value={form[id] || ''} onChange={(event) => setForm((state) => ({ ...state, [id]: event.target.value }))} className="mt-1.5 min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm outline-none focus:border-blue-500 dark:border-gh-border dark:bg-gh-input" /></label>;
    const footer = <div className="flex gap-2"><button type="button" disabled={pending} onClick={() => step === 0 ? onClose?.() : setStep((value) => value - 1)} className="min-h-11 flex-1 rounded-xl border border-gray-200 px-3 text-sm font-bold dark:border-gh-border">{step === 0 ? 'Cancel' : 'Back'}</button><button type="button" disabled={pending} onClick={() => step === 3 ? submit() : setStep((value) => value + 1)} className="min-h-11 flex-1 rounded-xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-50">{step === 3 ? (pending ? 'Saving…' : 'Save Employee') : 'Continue'}</button></div>;
    return <MobileBottomSheet open={open} onClose={onClose} closeDisabled={pending} title={title} description={`Step ${step + 1} of 4 · ${steps[step]}`} footer={footer}>
        <div data-mobile-employee-editor>{error && <p role="alert" className="mb-3 rounded-xl bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/40 dark:text-red-300">{error}</p>}
            {step === 0 && <MobileFormSection title="Account" description="Direct creation requires an explicit password."><MobileSelect label="Account type" value={form.user_type} onChange={(event) => setForm((state) => ({ ...state, user_type: event.target.value }))} options={[{ value: 'employee', label: 'Employee' }, { value: 'admin', label: 'Admin' }]} />{field('name', 'Name', 'text', true)}{field('email', 'Email', 'email', true)}{field('phone_no', 'Phone')}{field('dept_id', 'Department ID')}{field('desg_id', 'Designation ID')}{field('password', employee ? 'New password (optional)' : 'Password', 'password', !employee)}</MobileFormSection>}
            {step === 1 && <div className="space-y-3">{templates.length > 0 && <MobileSelect label="Prefill from template" value="" onChange={(event) => { const template = templates.find((item) => String(item.id) === event.target.value); if (template) setForm((state) => ({ ...state, system_permissions: template.permissions || template.system_permissions })); }} options={[{ value: '', label: 'Choose a template (optional)' }, ...templates.map((item) => ({ value: String(item.id), label: item.name }))]} />}<MobilePermissionTree value={form.system_permissions} onChange={(system_permissions) => setForm((state) => ({ ...state, system_permissions }))} /></div>}
            {step === 2 && <MobileFormSection title="Project membership" description="Membership is Access or No Access. It does not grant granular project-module permissions.">{projects.length ? projects.map((project) => { const selected = form.project_ids.map(String).includes(String(project.id)); return <label key={project.id} className="flex min-h-11 items-center gap-3 rounded-xl border border-gray-200 px-3 text-sm font-semibold dark:border-gh-border"><input type="checkbox" checked={selected} onChange={() => setForm((state) => ({ ...state, project_ids: selected ? state.project_ids.filter((id) => String(id) !== String(project.id)) : [...state.project_ids, project.id] }))} /><span>{project.name}</span><span className="ml-auto text-xs text-gray-500">{selected ? 'Access' : 'No Access'}</span></label>; }) : <p className="text-sm text-gray-500">No projects available.</p>}</MobileFormSection>}
            {step === 3 && <MobileFormSection title="Review" description="Confirm account, system access, and project membership before saving."><p className="text-sm"><strong>{form.name}</strong><br />{form.email}<br /><span className="capitalize">{form.user_type}</span></p><p className="text-xs text-gray-500">{form.project_ids.length} project membership{form.project_ids.length === 1 ? '' : 's'} selected.</p></MobileFormSection>}
        </div>
    </MobileBottomSheet>;
}
