import React, { useEffect, useState } from 'react';
import MobileBottomSheet from '../../components/MobileBottomSheet';
import { validateAdminImportFile } from './mobileAdminModel';

export default function MobileAdminBulkImport({ open, onClose, onImport, pending }) {
    const [file, setFile] = useState(null); const [error, setError] = useState(''); const [report, setReport] = useState(null);
    useEffect(() => { if (open) { setFile(null); setError(''); setReport(null); } }, [open]);
    const start = async () => { const validation = validateAdminImportFile(file); if (validation) { setError(validation); return; } setError(''); const result = await onImport?.(file); if (result?.report) setReport(result.report); };
    return <MobileBottomSheet open={open} onClose={onClose} closeDisabled={pending} title="Bulk user import" description="CSV / XLSX · imported accounts become employees" footer={!report && <div className="flex gap-2"><button type="button" disabled={pending} onClick={onClose} className="min-h-9 flex-1 rounded-lg border border-gray-200 text-xs font-semibold dark:border-gh-border">Cancel</button><button type="button" disabled={pending || !file} onClick={start} className="min-h-9 flex-1 rounded-lg bg-blue-600 px-3 text-xs font-semibold text-white disabled:opacity-50">{pending ? 'Processing…' : 'Start Import'}</button></div>}>
        <div className="space-y-3" data-mobile-admin-import>{!report ? <><p className="rounded-lg bg-gray-50 p-2.5 text-xs font-normal leading-relaxed text-gray-600 dark:bg-gh-hover dark:text-gh-muted">Required: Name, Email. Optional: Password, Department, Designation, Phone. Successful rows remain committed when another row fails.</p><label htmlFor="mobile-admin-import-file" className="block rounded-lg border border-dashed border-gray-300 p-4 text-center text-xs font-medium dark:border-gh-border">Choose CSV / XLSX<input id="mobile-admin-import-file" type="file" accept=".csv,.xlsx" onChange={(event) => { const selected = event.target.files?.[0] || null; setFile(selected); setError(validateAdminImportFile(selected)); }} className="mt-2 block w-full text-xs" /></label>{file && <p className="text-xs font-semibold">{file.name}</p>}{error && <p role="alert" className="text-xs text-red-600 dark:text-red-400">{error}</p>}</> : <section><h3 className="text-xs font-semibold text-gray-900 dark:text-gh-text">Import results</h3><dl className="mt-2 grid grid-cols-3 gap-1.5 text-center"><div className="rounded-lg bg-gray-100 p-2 dark:bg-gh-hover"><dt className="text-[10px] text-gray-500">Processed</dt><dd className="text-sm font-semibold">{report.total}</dd></div><div className="rounded-lg bg-emerald-50 p-2 text-emerald-700 dark:bg-emerald-950/30"><dt className="text-[10px]">Succeeded</dt><dd className="text-sm font-semibold">{report.succeeded}</dd></div><div className="rounded-lg bg-red-50 p-2 text-red-700 dark:bg-red-950/30"><dt className="text-[10px]">Failed</dt><dd className="text-sm font-semibold">{report.failed}</dd></div></dl>{report.errors.length > 0 && <ul className="mt-3 space-y-1.5 text-xs">{report.errors.map((item, index) => <li key={index} className="rounded-lg bg-red-50 p-2 text-xs font-normal text-red-700 dark:bg-red-950/30 dark:text-red-300">{typeof item === 'string' ? item : item.message || JSON.stringify(item)}</li>)}</ul>}<button type="button" onClick={onClose} className="mt-3 min-h-9 w-full rounded-lg bg-blue-600 text-xs font-semibold text-white">Done</button></section>}</div>
    </MobileBottomSheet>;
}
