import React, { useEffect, useState } from 'react';
import MobileBottomSheet from '../../components/MobileBottomSheet';
import { validateAdminImportFile } from './mobileAdminModel';

export default function MobileAdminBulkImport({ open, onClose, onImport, pending }) {
    const [file, setFile] = useState(null); const [error, setError] = useState(''); const [report, setReport] = useState(null);
    useEffect(() => { if (open) { setFile(null); setError(''); setReport(null); } }, [open]);
    const start = async () => { const validation = validateAdminImportFile(file); if (validation) { setError(validation); return; } setError(''); const result = await onImport?.(file); if (result?.report) setReport(result.report); };
    return <MobileBottomSheet open={open} onClose={onClose} closeDisabled={pending} title="Bulk user import" description="CSV / XLSX · imported accounts become employees" footer={!report && <div className="flex gap-2"><button type="button" disabled={pending} onClick={onClose} className="min-h-11 flex-1 rounded-xl border border-gray-200 font-bold dark:border-gh-border">Cancel</button><button type="button" disabled={pending || !file} onClick={start} className="min-h-11 flex-1 rounded-xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-50">{pending ? 'Processing…' : 'Start Import'}</button></div>}>
        <div className="space-y-4" data-mobile-admin-import>{!report ? <><p className="rounded-xl bg-gray-50 p-3 text-xs leading-5 text-gray-600 dark:bg-gh-hover dark:text-gh-muted">Required: Name, Email. Optional: Password, Department, Designation, Phone. Successful rows remain committed when another row fails.</p><label htmlFor="mobile-admin-import-file" className="block rounded-2xl border border-dashed border-gray-300 p-6 text-center text-sm font-semibold dark:border-gh-border">Choose CSV / XLSX<input id="mobile-admin-import-file" type="file" accept=".csv,.xlsx" onChange={(event) => { const selected = event.target.files?.[0] || null; setFile(selected); setError(validateAdminImportFile(selected)); }} className="mt-3 block w-full text-xs" /></label>{file && <p className="text-sm font-semibold">{file.name}</p>}{error && <p role="alert" className="text-sm text-red-600 dark:text-red-400">{error}</p>}</> : <section><h3 className="text-base font-bold">Import results</h3><dl className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-gray-100 p-3 dark:bg-gh-hover"><dt className="text-xs">Processed</dt><dd className="text-xl font-extrabold">{report.total}</dd></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-700 dark:bg-emerald-950/30"><dt className="text-xs">Succeeded</dt><dd className="text-xl font-extrabold">{report.succeeded}</dd></div><div className="rounded-xl bg-red-50 p-3 text-red-700 dark:bg-red-950/30"><dt className="text-xs">Failed</dt><dd className="text-xl font-extrabold">{report.failed}</dd></div></dl>{report.errors.length > 0 && <ul className="mt-4 space-y-2 text-xs">{report.errors.map((item, index) => <li key={index} className="rounded-xl bg-red-50 p-3 text-red-700 dark:bg-red-950/30 dark:text-red-300">{typeof item === 'string' ? item : item.message || JSON.stringify(item)}</li>)}</ul>}<button type="button" onClick={onClose} className="mt-4 min-h-11 w-full rounded-xl bg-blue-600 font-bold text-white">Done</button></section>}</div>
    </MobileBottomSheet>;
}
